"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";
type Check={ok:boolean;detail?:string}; type Result={ok:boolean;launchReady:boolean;checks:Record<string,Check>;duration_ms:number};
type User={id:string;nombre:string|null;empresa:string|null;pais_iso:string|null;tipo_usuario:string|null;created_at:string;active_company_id:string|null};
export default function AdminPage(){
 const [result,setResult]=useState<Result|null>(null),[users,setUsers]=useState<User[]>([]),[userCount,setUserCount]=useState(0),[companyCount,setCompanyCount]=useState(0),[opCount,setOpCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Vista general");
 async function run(){setLoading(true);setError("");try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Sesión no válida.");const [health,uc,cc,oc,ur]=await Promise.all([fetch("/api/health/launch",{headers:{Authorization:"Bearer "+session.access_token},cache:"no-store"}),supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("companies").select("id",{count:"exact",head:true}),supabase.from("operaciones").select("id",{count:"exact",head:true}),supabase.from("profiles").select("id,nombre,empresa,pais_iso,tipo_usuario,created_at,active_company_id").order("created_at",{ascending:false}).limit(6)]);const d=await health.json();if(!health.ok)throw new Error(d.error||"No autorizado.");if(ur.error)throw ur.error;setResult(d);setUserCount(uc.count||0);setCompanyCount(cc.count||0);setOpCount(oc.count||0);setUsers((ur.data||[]) as User[])}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar Administración.")}finally{setLoading(false)}}
 useEffect(()=>{void run()},[]);
 const countries=useMemo(()=>{const m=new Map<string,number>();users.forEach(u=>m.set(u.pais_iso||"Otros",(m.get(u.pais_iso||"Otros")||0)+1));return [...m.entries()]},[users]); const checks=result?Object.values(result.checks):[];
 const tabRoute:Record<string,string>={Usuarios:"/seguridad",Empresas:"/empresas","Roles y permisos":"/seguridad",Configuración:"/configuracion",Seguridad:"/seguridad",Auditoría:"/historial",Notificaciones:"/notificaciones",Integraciones:"/configuracion",Mantenimiento:"/configuracion"};
 const selectTab=(x:string)=>{setTab(x);if(tabRoute[x])window.location.href=tabRoute[x]};
 return <main className="admin-reference"><header className="admin-head"><div><h1>Administración</h1><p>Gestiona usuarios, configuraciones, seguridad y el funcionamiento general de la plataforma</p></div></header>{error&&<div className="admin-error">{error}</div>}
 <section className="admin-kpis"><AdminKpi icon="♟" value={userCount.toLocaleString("es-AR")} label="Usuarios totales" trend="↗ +12% este mes" tone="blue"/><AdminKpi icon="▦" value={companyCount.toLocaleString("es-AR")} label="Empresas registradas" trend="↗ +18% este mes" tone="green"/><AdminKpi icon="▤" value={opCount.toLocaleString("es-AR")} label="Operaciones activas" trend="↗ +24% este mes" tone="purple"/><AdminKpi icon="▤" value="4.2 TB" label="Almacenamiento" trend="↗ +8% este mes" tone="orange"/><AdminKpi icon="✓" value={result?.launchReady?"99,9%":"Verificar"} label="Disponibilidad" trend={result?.launchReady?"Operativo":"Revisión pendiente"} tone="green"/></section>
 <nav className="admin-tabs">{["Vista general","Usuarios","Empresas","Roles y permisos","Configuración","Seguridad","Auditoría","Notificaciones","Integraciones","Mantenimiento"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>selectTab(x)}>{x}</button>)}</nav>
 {loading?<div className="admin-loading">Cargando estado de administración…</div>:<section className="admin-main-grid"><div className="admin-left"><div className="admin-chart-row"><Panel title="Crecimiento de la plataforma"><GrowthChart/></Panel><Panel title="Usuarios por tipo"><UserDonut total={userCount}/></Panel><Panel title="Usuarios por país"><CountryList data={countries}/></Panel></div><div className="admin-lower-row"><Panel title="Últimos usuarios registrados"><UsersTable users={users}/></Panel><Panel title="Actividad del sistema"><Activity/></Panel></div><div className="admin-bottom-row"><Panel title="Estado de servidores"><ServerStatus checks={checks}/></Panel><Panel title="Uso de recursos"><Resources/></Panel><Panel title="Solicitudes de soporte"><Support/></Panel><Panel title="Mantenimiento y actualizaciones"><Maintenance ready={!!result?.launchReady}/></Panel></div></div></section>}
 <div className="admin-actions"><button onClick={()=>void run()} disabled={loading}>{loading?"Verificando…":"↻ Actualizar estado"}</button><Link href="/configuracion">Configuración →</Link><Link href="/reportes">Reportes →</Link></div></main>
}
function AdminKpi({icon,value,label,trend,tone}:{icon:string;value:string;label:string;trend:string;tone:string}){return <div className={"admin-kpi "+tone}><b>{icon}</b><span><strong>{value}</strong><small>{label}</small><i>{trend}</i></span></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="admin-panel"><h2>{title}</h2>{children}</section>}
function GrowthChart(){return <div className="growth-chart"><div className="growth-grid">{[2000,1500,1000,500,0].map(x=><span key={x}>{x.toLocaleString("es-AR")}</span>)}</div><svg viewBox="0 0 520 155"><polyline points="20,115 115,88 210,72 305,55 400,28 500,7" fill="none" stroke="#147bea" strokeWidth="3"/><polyline points="20,135 115,113 210,96 305,79 400,55 500,38" fill="none" stroke="#078d54" strokeWidth="3"/><polyline points="20,147 115,136 210,124 305,114 400,101 500,88" fill="none" stroke="#8c2be8" strokeWidth="3"/>{[["20","115"],["115","88"],["210","72"],["305","55"],["400","28"],["500","7"]].map(([x,y])=><circle key={x+y} cx={x} cy={y} r="4" fill="#147bea"/>)}</svg><div className="growth-months">{["Abr","May","Jun","Jul","Ago","Sep"].map(x=><span key={x}>{x}</span>)}</div><div className="chart-legend"><span>● Usuarios</span><span>● Empresas</span><span>● Operaciones</span></div></div>}
function UserDonut({total}:{total:number}){const types=["Productores","Acopios","Compradores","Intermediarios","Transportistas","Otros"];const colors=["#078d54","#f3b400","#147bea","#8c2be8","#f36b36","#aab3bd"];return <div className="admin-donut-wrap"><div className="admin-donut"><div><strong>{total.toLocaleString("es-AR")}</strong><small>Usuarios<br/>totales</small></div></div><div className="admin-legend">{types.map((x,i)=><p key={x}><span><i style={{background:colors[i]}}/> {x}</span><b>{[32,18,16,14,8,12][i]}%</b></p>)}</div></div>}
function CountryList({data}:{data:[string,number][]}){return <div className="country-list"><div className="world-map">🌎</div><div>{(data.length?data:[["AR",0],["BR",0],["US",0],["IT",0],["CN",0],["NL",0],["DE",0],["Otros",0]]).slice(0,8).map((x,i)=><p key={x[0]}><span>{x[0]==="AR"?"🇦🇷":x[0]==="BR"?"🇧🇷":x[0]==="US"?"🇺🇸":x[0]==="IT"?"🇮🇹":x[0]==="CN"?"🇨🇳":x[0]==="NL"?"🇳🇱":x[0]==="DE"?"🇩🇪":"●"}</span>{x[0]}<b>{Math.max(5,28-i*3)}%</b></p>)}</div></div>}
function UsersTable({users}:{users:User[]}){return <div className="users-table"><div className="user-row head"><span># NOMBRE</span><span>EMPRESA</span><span>PAÍS</span><span>TIPO</span><span>FECHA</span><span>ESTADO</span><span>ACCIONES</span></div>{users.slice(0,6).map(u=><div className="user-row" key={u.id}><span><b>{(u.nombre||"?").slice(0,2).toUpperCase()}</b>{u.nombre||"Usuario"}</span><span>{u.empresa||"—"}</span><span>{u.pais_iso||"—"}</span><span>{u.tipo_usuario||"Usuario"}</span><span>{new Date(u.created_at).toLocaleDateString("es-AR")}</span><em>Activo</em><button onClick={()=>window.location.href=`/perfil?usuario=${encodeURIComponent(u.id)}`}>Ver</button></div>)}</div>}
function Activity(){return <div className="activity"><p>👤 <b>Nuevo usuario registrado</b><small>Actividad reciente</small><time>Hace 5 min</time></p><p>▣ <b>Empresa verificada</b><small>Validación completada</small><time>Hace 12 min</time></p><p>● <b>Operación creada</b><small>Registro operativo</small><time>Hace 28 min</time></p><p>✎ <b>Contrato firmado</b><small>Firma digital registrada</small><time>Hace 45 min</time></p><p>▤ <b>Factura emitida</b><small>Comprobante registrado</small><time>Hace 1 hora</time></p></div>}
function ServerStatus({checks}:{checks:Check[]}){return <div className="server-list">{["Plataforma web","Base de datos","APIs externas","Servicios de IA","Backup"].map((x,i)=><p key={x}><i className={checks[i]?.ok===false?"bad":""}></i>{x}<b>{checks[i]?.ok===false?"Revisar":"Operativo"}</b></p>)}</div>}
function Resources(){return <div className="resource-list">{[["CPU",32],["Memoria RAM",58],["Almacenamiento",42],["Ancho de banda",28]].map(([x,v],i)=><p key={x}><span>{x}</span><i><b style={{width:v+"%"}} className={"r"+i}/></i><strong>{v}%</strong></p>)}</div>}
function Support(){return <div className="support"><p>🔴 <b>3</b> Pendientes</p><p>🟡 <b>2</b> En proceso</p><p>🟢 <b>12</b> Resueltas (hoy)</p><button onClick={()=>window.location.href="/ayuda?tema=soporte"}>Ver soporte</button></div>}
function Maintenance({ready}:{ready:boolean}){return <div className="maintenance"><strong>✓</strong><p><b>Sistema {ready?"actualizado":"en revisión"}</b><span>{ready?"Operativo":"Controles pendientes"}</span><small>Estado comprobado ahora</small></p><button onClick={()=>window.location.href="/configuracion?seccion=mantenimiento"}>⚙ Configurar mantenimiento</button></div>}
