"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";
type Check={ok:boolean;detail?:string}; type Result={ok:boolean;launchReady:boolean;checks:Record<string,Check>;duration_ms:number};
type User={id:string;nombre:string|null;empresa:string|null;pais_iso:string|null;tipo_usuario:string|null;created_at:string;active_company_id:string|null};
export default function AdminPage(){
 const [result,setResult]=useState<Result|null>(null),[users,setUsers]=useState<User[]>([]),[userCount,setUserCount]=useState(0),[companyCount,setCompanyCount]=useState(0),[opCount,setOpCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Vista general");
 async function run(){setLoading(true);setError("");try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Sesión no válida.");const [health,uc,cc,oc,ur]=await Promise.all([fetch("/api/health/launch",{headers:{Authorization:"Bearer "+session.access_token},cache:"no-store"}),supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("companies").select("id",{count:"exact",head:true}),supabase.from("operaciones").select("id",{count:"exact",head:true}),supabase.from("profiles").select("id,nombre,empresa,pais_iso,tipo_usuario,created_at,active_company_id").order("created_at",{ascending:false}).limit(6)]);const d=await health.json();if(ur.error)throw ur.error;if(d?.checks)setResult(d as Result);if(!health.ok){throw new Error(d?.error|| (d?.checks ? "Preflight de lanzamiento bloqueado: revisá los controles pendientes." : "No autorizado."));}setUserCount(uc.count||0);setCompanyCount(cc.count||0);setOpCount(oc.count||0);setUsers((ur.data||[]) as User[])}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar Administración.")}finally{setLoading(false)}}
 useEffect(()=>{void run()},[]);
 const countries=useMemo(()=>{const m=new Map<string,number>();users.forEach(u=>m.set(u.pais_iso||"Otros",(m.get(u.pais_iso||"Otros")||0)+1));return [...m.entries()]},[users]); const checks=result?Object.values(result.checks):[];
 const tabRoute:Record<string,string>={Usuarios:"/seguridad",Empresas:"/empresas","Roles y permisos":"/seguridad",Configuración:"/configuracion",Seguridad:"/seguridad",Auditoría:"/historial",Notificaciones:"/notificaciones",Integraciones:"/configuracion",Mantenimiento:"/configuracion"};
 const selectTab=(x:string)=>{setTab(x);if(tabRoute[x])window.location.href=tabRoute[x]};
 return <main className="admin-reference"><header className="admin-head"><div><h1>Administración</h1><p>Gestiona usuarios, configuraciones, seguridad y el funcionamiento general de la plataforma</p></div></header>{error&&<div className="admin-error">{error}</div>}
 <section className="admin-kpis"><AdminKpi icon="♟" value={userCount.toLocaleString("es-AR")} label="Usuarios totales" trend="Total actual" tone="blue"/><AdminKpi icon="▦" value={companyCount.toLocaleString("es-AR")} label="Empresas registradas" trend="Total actual" tone="green"/><AdminKpi icon="▤" value={opCount.toLocaleString("es-AR")} label="Operaciones activas" trend="Total actual" tone="purple"/><AdminKpi icon="▤" value="—" label="Almacenamiento" trend="Métrica no consultada" tone="orange"/><AdminKpi icon="✓" value={result?.launchReady?"OK":"Pendiente"} label="Preflight de lanzamiento" trend={result?.launchReady?"Todos los controles requeridos OK":"Hay controles pendientes"} tone="green"/></section>
 <nav className="admin-tabs">{["Vista general","Usuarios","Empresas","Roles y permisos","Configuración","Seguridad","Auditoría","Notificaciones","Integraciones","Mantenimiento"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>selectTab(x)}>{x}</button>)}</nav>
 {loading?<div className="admin-loading">Cargando estado de administración…</div>:<section className="admin-main-grid"><div className="admin-left"><div className="admin-chart-row"><Panel title="Crecimiento de la plataforma"><GrowthChart/></Panel><Panel title="Usuarios por tipo"><UserDonut total={userCount}/></Panel><Panel title="Usuarios por país"><CountryList data={countries}/></Panel></div><div className="admin-lower-row"><Panel title="Últimos usuarios registrados"><UsersTable users={users}/></Panel><Panel title="Actividad del sistema"><Activity/></Panel></div><div className="admin-bottom-row"><Panel title="Estado de servidores"><ServerStatus checks={checks}/></Panel><Panel title="Uso de recursos"><Resources/></Panel><Panel title="Solicitudes de soporte"><Support/></Panel><Panel title="Mantenimiento y actualizaciones"><Maintenance ready={!!result?.launchReady}/></Panel></div></div></section>}
 <div className="admin-actions"><button onClick={()=>void run()} disabled={loading}>{loading?"Verificando…":"↻ Actualizar estado"}</button><Link href="/configuracion">Configuración →</Link><Link href="/reportes">Reportes →</Link></div></main>
}
function AdminKpi({icon,value,label,trend,tone}:{icon:string;value:string;label:string;trend:string;tone:string}){return <div className={"admin-kpi "+tone}><b>{icon}</b><span><strong>{value}</strong><small>{label}</small><i>{trend}</i></span></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="admin-panel"><h2>{title}</h2>{children}</section>}
function GrowthChart(){return <div className="growth-chart"><div className="admin-empty">Serie histórica no disponible en esta vista. Se muestran únicamente métricas consultadas en tiempo real.</div></div>}
function UserDonut({total}:{total:number}){return <div className="admin-donut-wrap"><div className="admin-donut"><div><strong>{total.toLocaleString("es-AR")}</strong><small>Usuarios<br/>totales</small></div></div><div className="admin-empty">La distribución por tipo requiere una consulta agregada específica.</div></div>}
function CountryList({data}:{data:[string,number][]}){return <div className="country-list"><div className="world-map">🌎</div><div>{data.length?data.slice(0,8).map(x=><p key={x[0]}><span>●</span>{x[0]}<b>{x[1]}</b></p>):<p>Sin países registrados en la muestra consultada.</p>}</div></div>}
function UsersTable({users}:{users:User[]}){return <div className="users-table"><div className="user-row head"><span># NOMBRE</span><span>EMPRESA</span><span>PAÍS</span><span>TIPO</span><span>FECHA</span><span>ESTADO</span><span>ACCIONES</span></div>{users.slice(0,6).map(u=><div className="user-row" key={u.id}><span><b>{(u.nombre||"?").slice(0,2).toUpperCase()}</b>{u.nombre||"Usuario"}</span><span>{u.empresa||"—"}</span><span>{u.pais_iso||"—"}</span><span>{u.tipo_usuario||"Usuario"}</span><span>{new Date(u.created_at).toLocaleDateString("es-AR")}</span><em>Activo</em><button onClick={()=>window.location.href=`/perfil?usuario=${encodeURIComponent(u.id)}`}>Ver</button></div>)}</div>}
function Activity(){return <div className="activity"><p>No se consultó un feed de actividad reciente en esta pantalla.</p></div>}
function ServerStatus({checks}:{checks:Check[]}){return <div className="server-list">{["Plataforma web","Base de datos","APIs externas","Servicios de IA","Backup"].map((x,i)=><p key={x}><i className={checks[i]?.ok===false?"bad":""}></i>{x}<b>{checks[i]?.ok===false?"Revisar":"Operativo"}</b></p>)}</div>}
function Resources(){return <div className="resource-list"><p>Uso de recursos no disponible desde las fuentes consultadas.</p></div>}
function Support(){return <div className="support"><p>Las solicitudes de soporte no están conectadas a una fuente de datos en esta vista.</p><button onClick={()=>window.location.href="/ayuda?tema=soporte"}>Ver soporte</button></div>}
function Maintenance({ready}:{ready:boolean}){return <div className="maintenance"><strong>✓</strong><p><b>Sistema {ready?"actualizado":"en revisión"}</b><span>{ready?"Operativo":"Controles pendientes"}</span><small>Estado comprobado ahora</small></p><button onClick={()=>window.location.href="/configuracion?seccion=mantenimiento"}>⚙ Configurar mantenimiento</button></div>}
