"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase/client";

type Medio={id:string;empresa_id:string;tipo:"BANCO"|"FINANCIERA";nombre:string;titular:string|null;cuit_cuil:string|null;banco:string|null;cbu:string|null;alias:string|null;moneda_id:number|null;es_predeterminado:boolean;estado:string};
type Currency={id:number;codigo:string;nombre:string|null};

const methods=[
 {name:"Transferencia bancaria",desc:"Local e internacional",icon:"🏦",tone:"blue",status:"Disponible"},
 {name:"Transferencia SWIFT",desc:"Pagos internacionales",icon:"🌐",tone:"blue",status:"Disponible"},
 {name:"Carta de crédito (LC)",desc:"Comercio internacional",icon:"▤",tone:"blue",status:"Disponible"},
 {name:"Financiera",desc:"A través de entidades",icon:"▤",tone:"green",status:"Disponible"},
 {name:"Cuenta de garantía (Escrow)",desc:"Pago seguro con liberación",icon:"🤝",tone:"purple",status:"Disponible"},
 {name:"Criptomonedas",desc:"USDT, BTC, ETH",icon:"₿",tone:"amber",status:"En configuración"},
 {name:"PayPal",desc:"Pagos internacionales",icon:"P",tone:"paypal",status:"Disponible"},
 {name:"Otros métodos",desc:"Cheque, pagaré, etc.",icon:"▣",tone:"pink",status:"Disponible"}
];

export default function MediosCobroPage(){
 const[medios,setMedios]=useState<Medio[]>([]),[curr,setCurr]=useState<Currency[]>([]),[selected,setSelected]=useState<Medio|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[query,setQuery]=useState("");
 const[nombre,setNombre]=useState(""),[titular,setTitular]=useState(""),[cuit,setCuit]=useState(""),[banco,setBanco]=useState(""),[cbu,setCbu]=useState(""),[alias,setAlias]=useState(""),[moneda,setMoneda]=useState("");

 async function load(){setLoading(true);setError("");try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Necesitás iniciar sesión.");const{data:p,error:pe}=await supabase.from("profiles").select("active_company_id").eq("id",user.id).single();if(pe||!p?.active_company_id)throw new Error(pe?.message||"No se encontró una empresa activa.");const[{data:m,error:me},{data:c,error:ce}]=await Promise.all([supabase.from("medios_cobro").select("*").eq("empresa_id",p.active_company_id).neq("estado","INACTIVO").order("es_predeterminado",{ascending:false}),supabase.from("monedas").select("id,codigo,nombre").order("codigo")]);if(me)throw new Error(me.message);if(ce)throw new Error(ce.message);setMedios((m||[]) as Medio[]);setCurr((c||[]) as Currency[]);if(!selected&&m?.length)setSelected(m[0] as Medio);if(!moneda&&c?.length)setMoneda(String((c.find((x:any)=>x.codigo==="USD")||c[0]).id));}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar los métodos.");}finally{setLoading(false)}}useEffect(()=>{void load()},[]);

 const configuredNames=useMemo(()=>new Set(medios.map(m=>m.nombre.toLowerCase())),[medios]);\n const filtered=useMemo(()=>medios.filter(m=>[m.nombre,m.banco,m.titular,m.alias].join(" ").toLowerCase().includes(query.toLowerCase())),[medios,query]);
 const currency=(id:number|null)=>curr.find(x=>x.id===id)?.codigo||"USD";
 async function guardar(){try{if(!nombre||!titular||!cuit||!moneda){setError("Completá nombre, titular, CUIT/CUIL y moneda.");return}const{data:id,error:e}=await supabase.rpc("crear_medio_cobro",{p_datos:{tipo:"BANCO",nombre:nombre.trim(),titular:titular.trim(),cuit_cuil:cuit.trim(),banco:banco.trim()||null,cbu:cbu.trim()||null,alias:alias.trim()||null,moneda_id:Number(moneda)}});if(e||!id)throw new Error(e?.message||"No se pudo registrar el método.");setOpen(false);setNombre("");setTitular("");setCuit("");setBanco("");setCbu("");setAlias("");await load()}catch(e){setError(e instanceof Error?e.message:"No se pudo registrar el método.")}}
 return <main className="payment-methods-reference">
  <header className="pm-hero"><div><h1>Métodos de pago</h1><p>Configura y gestiona los métodos de pago disponibles para tus operaciones, comisiones y retiros.</p></div><button className="pm-primary" onClick={()=>setOpen(true)}>＋ Agregar método de pago</button></header>
  <nav className="pm-tabs">{["Métodos de pago","Pagos recibidos","Pagos enviados","Proveedores","Bancos","Monedas","Límites","Historial"].map((x,i)=><button key={x} className={i===0?"active":""}>{x}</button>)}</nav>
  <section className="pm-method-grid">{methods.map(m=>{const configured=Array.from(configuredNames).some(n=>n.includes(m.name.split(" ")[0].toLowerCase()));const state=configured?"Configurado":"Disponible";return <button key={m.name} className="pm-method-card" onClick={()=>{const found=medios.find(x=>x.nombre.toLowerCase().includes(m.name.split(" ")[0].toLowerCase()));if(found)setSelected(found)}}><span className={"pm-method-icon "+m.tone}>{m.icon}</span><div><b>{m.name}</b><small>{m.desc}</small><em className={"pm-state "+(configured?"active":"available")}>{state}</em></div></button>})}</section>
  {error&&<div className="pm-error">{error}</div>}
  <section className="pm-configured"><div className="pm-configured-title"><h2>Métodos de pago configurados</h2><div className="pm-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar métodos..."/></div></div><table><thead><tr><th>Método</th><th>Tipo</th><th>Moneda</th><th>País / Región</th><th>Estado</th><th>Límite por operación</th><th>Acciones</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="pm-empty">Cargando métodos…</td></tr>:filtered.map(m=><tr key={m.id} onClick={()=>setSelected(m)}><td><span className="pm-row-icon">▤</span><b>{m.nombre}</b></td><td>{m.tipo==="BANCO"?"Local":"Intermediado"}</td><td>{currency(m.moneda_id)}</td><td>🌐 Global</td><td><em className="pm-state active">Activo</em></td><td>Sin límite</td><td><button className="pm-dots">•••</button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={7} className="pm-empty">No hay métodos configurados.</td></tr>}</tbody></table></section>
  <aside className="pm-detail"><h2>Detalle del método de pago <button onClick={()=>setSelected(null)}>×</button></h2>{selected?<><div className="pm-detail-head"><span className="pm-method-icon blue">🏦</span><div><b>{selected.nombre}</b><small>Pagos locales e internacionales</small></div><em className="pm-state active">Activo</em></div><nav className="pm-detail-tabs"><span className="active">Información</span><span>Límites</span><span>Seguridad</span><span>Instrucciones</span></nav><dl><div><dt>Tipo</dt><dd>Transferencia bancaria</dd></div><div><dt>Moneda</dt><dd>{currency(selected.moneda_id)} - Peso Argentino</dd></div><div><dt>País</dt><dd>🇦🇷 Argentina</dd></div><div><dt>Titular de la cuenta</dt><dd>{selected.titular||"—"}</dd></div><div><dt>Banco</dt><dd>{selected.banco||selected.nombre}</dd></div><div><dt>CBU</dt><dd>{selected.cbu||"—"}</dd></div><div><dt>Alias</dt><dd>{selected.alias||"—"}</dd></div><div><dt>CUIT</dt><dd>{selected.cuit_cuil||"—"}</dd></div><div><dt>Estado</dt><dd><em className="pm-state active">● Activo</em></dd></div></dl><div className="pm-detail-actions"><button>✎ Editar</button><button>⏻ Desactivar</button></div></>:<p className="pm-empty">Seleccioná un método.</p>}
  <section className="pm-security"><h3>🛡 Seguridad y verificación</h3>{[["Registro en la plataforma",true],["Titular informado",!!selected.titular],["Datos bancarios informados",!!selected.banco||!!selected.cbu],["CUIT/CUIL informado",!!selected.cuit_cuil],["Verificación KYC",false]].map(([x,ok])=><p key={String(x)}>● <span>{String(x)}: {ok?"disponible":"no disponible"}</span></p>)}</section><div className="pm-info">ⓘ Todos los métodos de pago están protegidos con cifrado de datos y verificación de identidad.</div></aside>
  {open&&<div className="pm-modal"><div><button onClick={()=>setOpen(false)}>×</button><h2>Agregar método de pago</h2><div className="pm-form">{[["Nombre",nombre,setNombre],["Titular",titular,setTitular],["CUIT/CUIL",cuit,setCuit],["Banco",banco,setBanco],["CBU",cbu,setCbu],["Alias",alias,setAlias]].map(([l,v,s]:any)=><label key={l}>{l}<input value={v} onChange={e=>s(e.target.value)}/></label>)}<label>Moneda<select value={moneda} onChange={e=>setMoneda(e.target.value)}>{curr.map(c=><option key={c.id} value={c.id}>{c.codigo} · {c.nombre}</option>)}</select></label></div><button className="pm-primary" onClick={guardar}>Guardar método</button></div></div>}
 </main>
}