"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase/client";

type Medio = { id:string; empresa_id:string; tipo:"BANCO"|"FINANCIERA"; nombre:string; titular:string|null; cuit_cuil:string|null; banco:string|null; cbu:string|null; alias:string|null; moneda_id:number|null; es_predeterminado:boolean; estado:string };
const monedas: Record<number,string> = {1:"ARS",2:"USD",3:"EUR",4:"BRL"};

export default function MediosCobroPage() {
 const [medios,setMedios]=useState<Medio[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[open,setOpen]=useState(false);
 const [tipo,setTipo]=useState<"BANCO"|"FINANCIERA">("BANCO"),[nombre,setNombre]=useState(""),[titular,setTitular]=useState(""),[cuit,setCuit]=useState(""),[banco,setBanco]=useState(""),[cbu,setCbu]=useState(""),[alias,setAlias]=useState(""),[moneda,setMoneda]=useState("2"),[predeterminado,setPredeterminado]=useState(true);

 async function contexto(){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Necesitás iniciar sesión.");const {data,error}=await supabase.from("profiles").select("active_company_id").eq("id",user.id).single();if(error||!data?.active_company_id)throw new Error("No se encontró una empresa activa.");return {userId:user.id,empresaId:data.active_company_id};}
 async function cargar(){setLoading(true);setError("");try{const {empresaId}=await contexto();const {data,error}=await supabase.from("medios_cobro").select("*").eq("empresa_id",empresaId).neq("estado","INACTIVO").order("es_predeterminado",{ascending:false});if(error)throw new Error(error.message);setMedios((data||[]) as Medio[]);}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar los medios.");}finally{setLoading(false);}}
 async function guardar(){setError("");setMessage("");if(!nombre.trim()||!titular.trim()||!cuit.trim()){setError("Completá nombre, titular y CUIT/CUIL.");return;}if(tipo==="BANCO"&&!cbu.trim()&&!alias.trim()){setError("Ingresá CBU o Alias.");return;}setSaving(true);try{const {data:id,error}=await supabase.rpc("crear_medio_cobro",{p_datos:{tipo,nombre:nombre.trim(),titular:titular.trim(),cuit_cuil:cuit.trim(),banco:tipo==="BANCO"?banco.trim()||null:null,cbu:tipo==="BANCO"?cbu.trim()||null:null,alias:tipo==="BANCO"?alias.trim()||null:null,moneda_id:Number(moneda)}});if(error||!id)throw new Error(error?.message||"No se pudo registrar el medio.");if(predeterminado){const {error:rpcError}=await supabase.rpc("establecer_medio_cobro_predeterminado",{p_medio_id:id});if(rpcError)throw new Error(rpcError.message);}setMessage("Medio de cobro registrado correctamente.");setOpen(false);await cargar();}catch(e){setError(e instanceof Error?e.message:"No se pudo registrar el medio.");}finally{setSaving(false);}}
 async function hacerPredeterminado(id:string){setError("");setMessage("");try{await contexto();const {error}=await supabase.rpc("establecer_medio_cobro_predeterminado",{p_medio_id:id});if(error)throw new Error(error.message);setMessage("Medio predeterminado actualizado.");await cargar();}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar.");}}
 useEffect(()=>{cargar();},[]);
 return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-6xl space-y-6">
  <header className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h1 className="text-3xl font-bold">Medios de cobro</h1><p className="text-slate-600">Configurá dónde recibir tus comisiones.</p></div><button onClick={()=>setOpen(true)} className="rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white">+ Agregar medio</button></header>
  {error&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}{message&&<div className="rounded-xl bg-emerald-50 p-4 text-emerald-700">{message}</div>}
  {open&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="mb-5 text-xl font-bold">Nuevo medio de cobro</h2><div className="grid gap-4 md:grid-cols-2">
   <label>Tipo<select value={tipo} onChange={e=>setTipo(e.target.value as "BANCO"|"FINANCIERA")} className="mt-1 w-full rounded-xl border p-3"><option value="BANCO">Banco</option><option value="FINANCIERA">Financiera</option></select></label>
   <label>Nombre<input value={nombre} onChange={e=>setNombre(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label>Titular<input value={titular} onChange={e=>setTitular(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label>CUIT/CUIL<input value={cuit} onChange={e=>setCuit(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label>
   {tipo==="BANCO"&&<><label>Banco<input value={banco} onChange={e=>setBanco(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label>CBU<input value={cbu} onChange={e=>setCbu(e.target.value)} maxLength={22} className="mt-1 w-full rounded-xl border p-3"/></label><label>Alias<input value={alias} onChange={e=>setAlias(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label></>}
   <label>Moneda<select value={moneda} onChange={e=>setMoneda(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="1">ARS</option><option value="2">USD</option><option value="3">EUR</option><option value="4">BRL</option></select></label><label className="flex items-center gap-2"><input type="checkbox" checked={predeterminado} onChange={e=>setPredeterminado(e.target.checked)}/> Predeterminado</label>
  </div><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setOpen(false)} className="rounded-xl border px-5 py-3">Cancelar</button><button disabled={saving} onClick={guardar} className="rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white">{saving?"Guardando...":"Guardar"}</button></div></section>}
  <section><h2 className="mb-4 text-xl font-bold">Tus medios</h2>{loading?<div className="rounded-xl bg-white p-8">Cargando...</div>:medios.length===0?<div className="rounded-xl bg-white p-8 text-center">No tenés medios de cobro registrados.</div>:<div className="grid gap-4 md:grid-cols-2">{medios.map(m=><article key={m.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between"><h3 className="font-bold">{m.tipo==="BANCO"?"🏦":"💳"} {m.nombre}</h3>{m.es_predeterminado&&<span className="text-amber-700">★ Predeterminado</span>}</div><div className="mt-4 space-y-1 text-sm"><div><b>Titular:</b> {m.titular||"—"}</div><div><b>CUIT/CUIL:</b> {m.cuit_cuil||"—"}</div>{m.tipo==="BANCO"&&<><div><b>Banco:</b> {m.banco||"—"}</div><div><b>CBU:</b> {m.cbu?"•••• "+m.cbu.slice(-4):"—"}</div><div><b>Alias:</b> {m.alias||"—"}</div></>}<div><b>Moneda:</b> {m.moneda_id?monedas[m.moneda_id]:"—"}</div></div><div className="mt-4 flex justify-between border-t pt-3"><span>{m.estado}</span>{!m.es_predeterminado&&m.estado!=="INACTIVO"&&<button onClick={()=>hacerPredeterminado(m.id)} className="font-semibold">Usar como predeterminado</button>}</div></article>)}</div>}</section>
 </div></main>;
}