"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { supabase } from "@/lib/supabase/client";

const menu=[["Inicio","/dashboard","⌂"],["Mercado","/mercado","🌾"],["Marketplace","/marketplace","▤"],["Oportunidades IA","/oportunidades","✦"],["Publicaciones","/mis-publicaciones","▤"],["Ofertas recibidas","/ofertas-recibidas","↗"],["Documentos","/documentos","▧"],["Contratos","/contratos","▣"],["Facturación","/facturas","$"],["Operaciones","/operaciones","⇄"],["Comisiones","/comisiones","$"],["Pagos","/pagos","$"],["Reportes","/reportes","▥"],["Medios de cobro","/medios-cobro","▣"],["Retiros","/retiros-comisiones","↘"],["Mensajes","/mensajes","◌"],["Notificaciones","/notificaciones","♢"],["Empresas","/empresas","▦"],["Verificaciones","/verificaciones","✓"],["Videollamadas","/videollamadas","🎥"],["Ayuda","/ayuda","?"],["Términos","/terminos","§"],["Configuración","/configuracion","⚙"]] as const;

export default function Sidebar(){
 const pathname=usePathname(); const [mensajes,setMensajes]=useState(0); const [notificaciones,setNotificaciones]=useState(0);
 const [t,setT]=useState<Record<string,string>>({});
 const fallback:Record<string,string>={platform:"PLATAFORMA","status.operativo":"Mercado operativo"};
 useEffect(()=>{async function cargar(){const saved=localStorage.getItem("agrobrokeria.language")||document.documentElement.lang||"es";const language=["es","en","pt","it","fr","de"].includes(saved)?saved:"es";setLang(language);const {data}=await supabase.from("traducciones_ui").select("clave,texto").eq("idioma",language).eq("version",1);setT(Object.fromEntries((data||[]).map(x=>[x.clave,x.texto])))}void cargar()},[]);
 useEffect(()=>{async function cargar(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{count:m},{count:n}]=await Promise.all([supabase.from("mensajes_comerciales").select("id",{count:"exact",head:true}).eq("destinatario_profile_id",user.id).is("leido_at",null),supabase.from("notificaciones").select("id",{count:"exact",head:true}).or(`profile_id.eq.${user.id},cuenta_id.eq.${user.id}`).eq("leida",false)]);setMensajes(m||0);setNotificaciones(n||0)}void cargar()},[]);
 return <aside className="app-sidebar"><div className="sidebar-section-label">{t.platform||fallback.platform}</div><nav className="sidebar-nav">{menu.map(([nombre,ruta,icono])=>{ const keyMap:Record<string,string>={"Inicio":"nav.inicio","Mercado":"nav.mercado","Marketplace":"nav.marketplace","Oportunidades IA":"nav.oportunidades","Publicaciones":"nav.publicaciones","Ofertas recibidas":"nav.ofertas","Documentos":"nav.documentos","Contratos":"nav.contratos","Facturación":"nav.facturacion","Operaciones":"nav.operaciones","Comisiones":"nav.comisiones","Pagos":"nav.pagos","Reportes":"nav.reportes","Medios de cobro":"nav.medios_cobro","Retiros":"nav.retiros","Mensajes":"nav.mensajes","Notificaciones":"nav.notificaciones","Empresas":"nav.empresas","Verificaciones":"nav.verificaciones","Videollamadas":"nav.videollamadas","Ayuda":"nav.ayuda","Términos":"nav.terminos","Configuración":"nav.configuracion"}; const label=t[keyMap[nombre]]||nombre;const activo=pathname===ruta||(ruta!=="/dashboard"&&pathname.startsWith(ruta+"/"));const contador=ruta==="/mensajes"?mensajes:ruta==="/notificaciones"?notificaciones:0;return <Link key={ruta} href={ruta} className={`sidebar-link ${activo?"active":""}`}><span className="sidebar-icon">{icono}</span><span className="sidebar-label">{label}</span>{contador>0&&<span className="sidebar-badge">{contador>99?"99+":contador}</span>}</Link>})}</nav><div className="sidebar-status"><span className="status-dot"/><div><strong>AgroBroker IA</strong><small>{t["status.operativo"]||fallback["status.operativo"]}</small></div></div></aside>;
}