"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { supabase } from "@/lib/supabase/client";

const menu=[["Inicio","/dashboard","⌂"],["Mercado","/mercado","▥"],["Ofertas","/marketplace","▤"],["Demandas","/marketplace?tipo=DEMANDA","⌂"],["Oportunidades IA","/oportunidades","✦"],["Pizarra y Cotizaciones","/mercado","▦"],["Operaciones","/operaciones","⇄"],["Contratos","/contratos","▣"],["Documentos","/documentos","▧"],["Facturación","/facturas","▤"],["Logística","/logistica","⌁"],["Comisiones","/comisiones","$"],["Empresas","/empresas","▦"],["Mensajes","/mensajes","◌"],["Videollamadas","/videollamadas","◉"],["IA & Análisis","/oportunidades","✦"],["Reportes","/reportes","▥"],["Configuración","/configuracion","⚙"],["Ayuda","/ayuda","?"],["Términos & Condiciones","/terminos","§"],["Administración","/admin","▣"]] as const;
const keyMap:Record<string,string>={"Inicio":"nav.inicio","Mercado":"nav.mercado","Ofertas":"nav.marketplace","Demandas":"nav.marketplace","Oportunidades IA":"nav.oportunidades","Pizarra y Cotizaciones":"nav.mercado","Operaciones":"nav.operaciones","Contratos":"nav.contratos","Documentos":"nav.documentos","Facturación":"nav.facturacion","Logística":"nav.operaciones","Comisiones":"nav.comisiones","Empresas":"nav.empresas","Mensajes":"nav.mensajes","Videollamadas":"nav.videollamadas","IA & Análisis":"nav.oportunidades","Reportes":"nav.reportes","Configuración":"nav.configuracion","Ayuda":"nav.ayuda","Términos & Condiciones":"nav.terminos","Administración":"nav.administracion"};
export default function Sidebar(){
 const pathname=usePathname();const[mensajes,setMensajes]=useState(0);const[notificaciones,setNotificaciones]=useState(0);const[t,setT]=useState<Record<string,string>>({});
 async function cargarTraducciones(){const saved=localStorage.getItem("agrobrokeria.language")||document.documentElement.lang||"es";const language=["es","en","pt","it","fr","de"].includes(saved)?saved:"es";const{data}=await supabase.from("traducciones_ui").select("clave,texto").eq("idioma",language).eq("version",1);setT(Object.fromEntries((data||[]).map(x=>[x.clave,x.texto])));}
 useEffect(()=>{void cargarTraducciones();const onLanguage=()=>{void cargarTraducciones()};window.addEventListener("agrobrokeria:language-changed",onLanguage);return()=>window.removeEventListener("agrobrokeria:language-changed",onLanguage)},[]);
 useEffect(()=>{async function cargar(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const[{count:m},{count:n}]=await Promise.all([supabase.from("mensajes_comerciales").select("id",{count:"exact",head:true}).eq("destinatario_profile_id",user.id).is("leido_at",null),supabase.from("notificaciones").select("id",{count:"exact",head:true}).or(`profile_id.eq.${user.id},cuenta_id.eq.${user.id}`).eq("leida",false)]);setMensajes(m||0);setNotificaciones(n||0)}void cargar()},[]);
 const fallback={platform:"PLATAFORMA","status.operativo":"Mercado operativo"};
 return <aside className="app-sidebar">
  <Link href="/dashboard" className="sidebar-brand"><span className="sidebar-leaf">◒</span><span><strong>agrobroker<span>IA</span></strong><small>NEGOCIOS QUE CONECTAN EL CAMPO</small></span></Link>
  <nav className="sidebar-nav">{menu.map(([nombre,ruta,icono],index)=>{const href=ruta;const clean=ruta.split("?")[0];const label=t[keyMap[nombre]]||nombre;const activo=pathname===clean||(clean!=="/dashboard"&&pathname.startsWith(clean+"/"));const contador=nombre==="Mensajes"?mensajes:0;return <Link key={nombre+"-"+index} href={href} className={`sidebar-link ${activo?"active":""}`}><span className="sidebar-icon">{icono}</span><span className="sidebar-label">{label}</span>{nombre==="Oportunidades IA"&&<span className="sidebar-new">NUEVO</span>}{contador>0&&<span className="sidebar-badge">{contador>99?"99+":contador}</span>}</Link>})}</nav>
  <div className="sidebar-status"><span className="status-dot"/><div><strong>{t.platform||fallback.platform}</strong><small>{t["status.operativo"]||fallback["status.operativo"]}</small></div><span className="sidebar-status-count">{notificaciones>0?notificaciones:"✓"}</span></div>
  <Link href="/ayuda" className="sidebar-help"><span>?</span><div><strong>Centro de ayuda</strong><small>Preguntas frecuentes</small></div><b>›</b></Link>
 </aside>;
}