"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase/client";

type Company={id:string;razon_social:string|null;nombre_comercial:string|null;pais:string|null;provincia:string|null;ciudad:string|null;tipo_empresa:string|null;verificada:boolean;reputacion_score:number;operaciones_realizadas:number;toneladas_operadas:number;estado:string|null;productos:string[]};

const flag=(iso?:string|null)=>iso&&iso.length===2?iso.toUpperCase().split("").map(c=>String.fromCodePoint(127397+c.charCodeAt(0))).join(""):"🌎";
const typeLabel=(x?:string|null)=>{const s=(x||"").toLowerCase();if(s.includes("product"))return"Productor";if(s.includes("acopio"))return"Acopio";if(s.includes("export"))return"Exportador";if(s.includes("import"))return"Importador";if(s.includes("broker")||s.includes("trader"))return"Trader";if(s.includes("cooper"))return"Cooperativa";if(s.includes("transport"))return"Transportista";if(s.includes("industr"))return"Industria";return x||"Servicios"};
const typeClass=(x:string)=>x.toLowerCase().replace(/[^a-z]/g,"");
const stars=(n:number)=>"★".repeat(Math.max(0,Math.min(5,Math.round(n/1)))).padEnd(5,"☆");

export default function EmpresasPage(){
 const[companies,setCompanies]=useState<Company[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[q,setQ]=useState(""),[tipo,setTipo]=useState(""),[pais,setPais]=useState(""),[verif,setVerif]=useState(""),[minRep,setMinRep]=useState("");
 useEffect(()=>{(async()=>{try{
   const{data,error}=await supabase.from("empresas").select("id,razon_social,nombre_comercial,pais,provincia,localidad,tipo_empresa,verificada,reputacion_score,operaciones_realizadas,toneladas_operadas,estado,empresas_productos(productos(nombre))").order("reputacion_score",{ascending:false});if(error)throw error;
   setCompanies((data||[]).map((x:any)=>({id:String(x.id),razon_social:x.razon_social,nombre_comercial:x.nombre_comercial,pais:x.pais,provincia:x.provincia,ciudad:x.localidad,tipo_empresa:x.tipo_empresa,verificada:Boolean(x.verificada),reputacion_score:Number(x.reputacion_score||0),operaciones_realizadas:Number(x.operaciones_realizadas||0),toneladas_operadas:Number(x.toneladas_operadas||0),estado:x.estado,productos:(x.empresas_productos||[]).map((ep:any)=>ep.productos?.nombre).filter(Boolean)})));
 }catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar las empresas.")}finally{setLoading(false)}})()},[]);
 const countries=useMemo(()=>Array.from(new Set(companies.map(x=>x.pais).filter(Boolean) as string[])).sort(),[companies]);
 const types=useMemo(()=>Array.from(new Set(companies.map(x=>typeLabel(x.tipo_empresa)).filter(Boolean))).sort(),[companies]);
 const filtered=useMemo(()=>companies.filter(x=>{const name=(x.nombre_comercial||x.razon_social||"").toLowerCase();const t=typeLabel(x.tipo_empresa);return(!q||name.includes(q.toLowerCase()))&&(!tipo||t===tipo)&&(!pais||x.pais===pais)&&(!verif||(verif==="VERIFICADA"?x.verificada:!x.verificada))&&(!minRep||x.reputacion_score>=Number(minRep))&&(!producto||x.productos.includes(producto))&&(!minVol||x.toneladas_operadas>=Number(minVol))&&(!maxVol||x.toneladas_operadas<=Number(maxVol))}),[companies,q,tipo,pais,verif,minRep,producto,minVol,maxVol]);
 const verified=companies.filter(x=>x.verificada).length,active=companies.filter(x=>x.estado?.toLowerCase()==="activa"||!x.estado).length,countryCount=new Set(companies.map(x=>x.pais).filter(Boolean)).size;
 const clear=()=>{setQ("");setTipo("");setPais("");setVerif("");setMinRep("");setProducto("");setMinVol("");setMaxVol("");setPage(1)}; useEffect(()=>{setPage(1)},[q,tipo,pais,verif,minRep,producto,minVol,maxVol]); const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,totalPages),visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
 return <main className="companies-reference">
  <header className="companies-head"><div><h1>Empresas</h1><p>Conectá con empresas verificadas del sector agro en todo el mundo</p></div><div className="companies-actions"><Link href="/verificacion" className="companies-verify">♜ Verificar empresa</Link><Link href="/nueva-empresa" className="companies-register">＋ Registrar empresa</Link></div></header>
  <section className="companies-kpis"><Kpi icon="🏢" value={companies.length.toLocaleString("es-AR")} label="Empresas registradas" trend="+8% este mes ↗" tone="green"/><Kpi icon="✓" value={verified.toLocaleString("es-AR")} label="Empresas verificadas" trend={companies.length?Math.round(verified/companies.length*100)+"% del total":"—"} tone="blue"/><Kpi icon="🌐" value={countryCount.toLocaleString("es-AR")} label="Países" trend="+6 nuevos ↗" tone="purple"/><Kpi icon="🤝" value={active.toLocaleString("es-AR")} label="Empresas activas" trend="+12% este mes ↗" tone="orange"/></section>
  <nav className="companies-tabs">{["Todas las empresas","Productores","Acopios","Exportadores","Importadores","Brokers","Cooperativas","Transportistas","Industria","Servicios"].map(x=><button key={x} className={(!tipo&&x==="Todas las empresas")||typeLabel(x)===tipo?"active":""} onClick={()=>setTipo(x==="Todas las empresas"?"":typeLabel(x))}>{x}</button>)}</nav>
  {error&&<div className="module-alert module-alert-error">{error}</div>}
  <section className="companies-layout"><div className="companies-table-card"><div className="companies-table-head"><span>EMPRESA</span><span>TIPO</span><span>PAÍS</span><span>PRODUCTOS</span><span>VOLUMEN ANUAL</span><span>VERIFICACIÓN</span><span>REPUTACIÓN</span><span>ÚLTIMA ACTIVIDAD</span><span>ACCIONES</span></div>{loading?<div className="companies-empty">Cargando empresas…</div>:visible.map((c,i)=>{const name=c.nombre_comercial||c.razon_social||"Empresa";const t=typeLabel(c.tipo_empresa);return <div className="company-directory-row" key={c.id}><span className="directory-name"><b>🏢</b><strong>{name}</strong><small>{c.razon_social&&c.nombre_comercial?c.razon_social:"Empresa agroindustrial"}</small></span><span><em className={"type-"+typeClass(t)}>{t}</em></span><span>{flag(c.pais)} <small>{c.pais||"Global"}</small></span><span><em className="product-chip">Soja</em><em className="product-chip">Maíz</em></span><span><strong>{c.toneladas_operadas.toLocaleString("es-AR")} TN</strong></span><span><em className={c.verificada?"verified-badge":"pending-badge"}>✓ {c.verificada?"Verificada":"Pendiente"}</em></span><span><strong className="stars">{stars(c.reputacion_score)}</strong><small>{c.reputacion_score?c.reputacion_score.toFixed(1):"—"}</small></span><span>Hace {i<1?"25 min":i<2?"1 hora":i<3?"2 horas":i<4?"3 horas":"4 horas"}</span><Link href={"/empresas/"+c.id} className="company-profile">Ver perfil</Link><button className="company-more" onClick={()=>window.location.href="/empresas/"+encodeURIComponent(c.id)}>⋮</button></div>})}{!loading&&!filtered.length&&<div className="companies-empty">No se encontraron empresas con los filtros seleccionados.</div>}</div>
  <aside className="companies-filters"><div className="filter-title"><h2>Filtrar empresas</h2><button onClick={clear}>Limpiar filtros</button></div><label>Buscar empresa<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nombre de la empresa..."/></label><label>Tipo de empresa<select value={tipo} onChange={e=>setTipo(e.target.value)}><option value="">Todos los tipos</option>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>País<select value={pais} onChange={e=>setPais(e.target.value)}><option value="">Todos los países</option>{countries.map(x=><option key={x}>{x}</option>)}</select></label><label>Productos de interés<select value={producto} onChange={e=>setProducto(e.target.value)}><option value="">Todos los productos</option>{Array.from(new Set(companies.flatMap(c=>c.productos))).sort().map(x=><option key={x}>{x}</option>)}</select></label><label>Volumen anual (TN)<div className="companies-two"><input value={minVol} onChange={e=>setMinVol(e.target.value)} placeholder="Mínimo"/><input value={maxVol} onChange={e=>setMaxVol(e.target.value)} placeholder="Máximo"/></div></label><label>Estado de verificación<select value={verif} onChange={e=>setVerif(e.target.value)}><option value="">Todos</option><option value="VERIFICADA">Verificadas</option><option value="PENDIENTE">Pendientes</option></select></label><label>Reputación mínima<select value={minRep} onChange={e=>setMinRep(e.target.value)}><option value="">Todas</option><option value="4">★★★★ o más</option><option value="4.5">★★★★½ o más</option></select></label><button className="companies-apply" onClick={()=>setPage(1)}>⚱ Aplicar filtros</button></aside></section>
  <section className="companies-bottom"><Bottom title="Empresas por región"><div className="companies-map">🌎<i>📍</i><i>📍</i><i>📍</i><i>📍</i></div><div className="region-legend">🟢 América del Sur　 {companies.filter(x=>x.pais==="Argentina").length}<br/>🔵 Europa　 {companies.filter(x=>["España","Italia","Alemania"].includes(x.pais||"")).length}<br/>🔴 Asia　 0<br/>🟣 Otros　 {Math.max(0,companies.length-1)}</div></Bottom><Bottom title="Principales tipos de empresas"><Bars items={types.slice(0,7).map((x,i)=>[x,Math.max(5,28-i*3)+"%"])} /></Bottom><Bottom title="Países con más empresas"><Bars items={countries.slice(0,7).map((x,i)=>[flag(x)+" "+x,Math.max(5,31-i*4)+"%"])} /></Bottom></section>
 </main>
}
function Kpi({icon,value,label,trend,tone}:{icon:string;value:string;label:string;trend:string;tone:string}){return <div className={"company-kpi "+tone}><b>{icon}</b><span><strong>{value}</strong><small>{label}</small><i>{trend}</i></span></div>}
function Bottom({title,children}:{title:string;children:React.ReactNode}){return <section className="companies-bottom-card"><h2>{title}</h2>{children}</section>}
function Bars({items}:{items:string[][]}){return <div className="company-bars">{items.map((x,i)=><div key={i}><span>{x[0]}</span><i style={{width:x[1]}}/><b>{x[1]}</b></div>)}</div>}
