"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";

type Factura={id:string;operacion_id:string;doc_tipo_receptor:number|null;iva_alicuota:number|null;contrato_id:string|null;empresa_id:string;empresa_receptor_id:string|null;numero_factura:string|null;tipo_factura:string|null;tipo_comprobante_codigo:number|null;punto_venta:number|null;numero_comprobante:number|null;fecha_emision:string|null;cuit_emisor:string|null;cuit_receptor:string|null;razon_social_emisor:string|null;razon_social_receptor:string|null;importe_neto:number|null;importe_iva:number|null;importe_total:number|null;moneda_id:number|null;cae:string|null;caea:string|null;cae_vencimiento:string|null;estado:string;arca_mensaje:string|null;creada_en:string|null};
type Op={id:string;codigo:string;estado:string;cantidad_tn:number;importe_total:number};
type Company={id:string;razon_social:string;cuit:string;rol:string};


export default function FacturasPage(){
 const [rows,setRows]=useState<Factura[]>([]),[ops,setOps]=useState<Op[]>([]),[companies,setCompanies]=useState<Company[]>([]);
 const [opId,setOpId]=useState(""),[receiver,setReceiver]=useState(""),[tipo,setTipo]=useState(11),[pv,setPv]=useState(""),[net,setNet]=useState(""),[iva,setIva]=useState("0"),[alicuota,setAlicuota]=useState(""),[docTipo,setDocTipo]=useState(""),[cond,setCond]=useState("");
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const [tab,setTab]=useState(""),[fTipo,setFTipo]=useState(""),[fEstado,setFEstado]=useState(""),[fEmpresa,setFEmpresa]=useState(""),[fDesde,setFDesde]=useState(""),[fHasta,setFHasta]=useState(""),[fMin,setFMin]=useState(""),[fMax,setFMax]=useState(""),[fMoneda,setFMoneda]=useState(""),[page,setPage]=useState(1); const pageSize=8;

 async function load(){
   setLoading(true);setErr("");
   const [{data:f,error:fe},{data:o,error:oe},{data:m,error:me}]=await Promise.all([
     supabase.from("facturas").select("id,operacion_id,contrato_id,empresa_id,empresa_receptor_id,doc_tipo_receptor,iva_alicuota,numero_factura,tipo_factura,tipo_comprobante_codigo,punto_venta,numero_comprobante,fecha_emision,cuit_emisor,cuit_receptor,razon_social_emisor,razon_social_receptor,importe_neto,importe_iva,importe_total,moneda_id,cae,caea,cae_vencimiento,estado,arca_mensaje,creada_en").order("creada_en",{ascending:false}),
     supabase.from("operaciones").select("id,codigo,estado,cantidad_tn,importe_total").order("fecha_operacion",{ascending:false}),
     supabase.from("monedas").select("id,codigo")
   ]);
   if(fe||oe||me)setErr((fe||oe||me)?.message||"Error");
   setRows((f||[]) as Factura[]);setOps((o||[]) as Op[]);
   setCurrencies(Object.fromEntries(((m||[]) as any[]).map(x=>[String(x.id),String(x.codigo)])));
   setLoading(false);
 }

 useEffect(()=>{load()},[]);
 async function loadReceivers(id:string){setOpId(id);setReceiver("");if(!id){setCompanies([]);return}const {data}=await supabase.from("operacion_participantes").select("empresa_id,rol,empresas(id,razon_social,cuit)").eq("operacion_id",id);setCompanies(((data||[]).map((x:any)=>({id:x.empresas?.id,razon_social:x.empresas?.razon_social,cuit:x.empresas?.cuit,rol:x.rol})).filter((x:any)=>x.id)) as Company[])}
 async function request(){setBusy(true);setErr("");setMsg("");try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Sesión expirada.");if(!opId||!receiver||!pv||!net)throw new Error("Completá operación, receptor, punto de venta e importe neto.");const {data:id,error}=await supabase.rpc("crear_solicitud_factura",{p_operacion_id:opId,p_empresa_receptor_id:receiver,p_tipo_comprobante_codigo:tipo,p_punto_venta:Number(pv),p_importe_neto:Number(net),p_importe_iva:Number(iva||0),p_condicion_iva_receptor:cond?Number(cond):null,p_doc_tipo_receptor:docTipo?Number(docTipo):null,p_iva_alicuota:alicuota?Number(alicuota):null});if(error)throw new Error(error.message);const r=await fetch(process.env.NEXT_PUBLIC_SUPABASE_URL+"/functions/v1/arca-facturacion",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({invoice_id:id})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Error de integración ARCA.");setMsg(j.ok?"Comprobante autorizado por ARCA.":"ARCA respondió con rechazo/observación.");await load()}catch(e){setErr(e instanceof Error?e.message:"No se pudo procesar la factura.")}finally{setBusy(false)}}
 const status=(f:Factura)=>{const e=(f.estado||"").toUpperCase();if(e==="AUTORIZADA")return "Autorizada";if(e==="OBSERVADA")return "Observada";if(e==="RECHAZADA")return "Rechazada";if(e==="PENDIENTE_ARCA")return "Pendiente ARCA";if(e==="ERROR_INTEGRACION")return "Error integración";return f.estado||"Pendiente"};
 const filtered=useMemo(()=>rows.filter((f)=>{const s=status(f),date=(f.fecha_emision||f.creada_en||"").slice(0,10),empresa=f.razon_social_receptor||f.razon_social_emisor||"Empresa comercial";return (!tab||s===tab)&&(!fTipo||f.tipo_factura===fTipo)&&(!fEstado||s===fEstado)&&(!fEmpresa||empresa===fEmpresa)&&(!fDesde||date>=fDesde)&&(!fHasta||date<=fHasta)&&(!fMin||Number(f.importe_total||0)>=Number(fMin))&&(!fMax||Number(f.importe_total||0)<=Number(fMax))&&(!fMoneda||String(f.moneda_id||"")===fMoneda)}),[rows,tab,fTipo,fEstado,fEmpresa ,fDesde,fHasta,fMin,fMax,fMoneda]);
 useEffect(()=>{setPage(1)},[tab,fTipo,fEstado,fEmpresa,fDesde,fHasta,fMin,fMax,fMoneda]); const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,totalPages),visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize); const clear=()=>{setTab("");setFTipo("");setFEstado("");setFEmpresa("");setFDesde("");setFHasta("");setFMin("");setFMax("");setFMoneda("");setPage(1)};
 const total=rows.reduce((a,f)=>a+Number(f.importe_total||0),0),autorizadas=rows.filter(f=>status(f)==="Autorizada").reduce((a,f)=>a+Number(f.importe_total||0),0),pendientes=rows.filter(f=>status(f)==="Pendiente ARCA").reduce((a,f)=>a+Number(f.importe_total||0),0),rechazadas=rows.filter(f=>status(f)==="Rechazada").reduce((a,f)=>a+Number(f.importe_total||0),0);
 const amountLabel=(value:number)=>{const codes=[...new Set(rows.filter(f=>Number(f.importe_total||0)!==0).map(f=>currencies[String(f.moneda_id||"")]||"Moneda"))];return value.toLocaleString("es-AR",{maximumFractionDigits:0})+(codes.length===1?" "+codes[0]:codes.length>1?" · Varias monedas":"");};
 return <main className="billing-reference">
  <header className="billing-head"><div><h1>Facturación</h1><p>Gestiona tus facturas, cobranzas y comprobantes integrados con ARCA</p></div><div className="billing-head-actions"><Link href="/configuracion">◉ Configuración ARCA</Link><Link href="/configuracion">⚙ Configuración fiscal</Link><button className="billing-new" onClick={()=>document.getElementById("billing-emission")?.scrollIntoView({behavior:"smooth",block:"start"})}>＋ Nueva factura</button></div></header>
  {err&&<div className="billing-alert error">{err}</div>}{msg&&<div className="billing-alert">{msg}</div>}
  <section className="billing-kpis"><Kpi icon="▤" value={rows.length.toLocaleString("es-AR")} label="Facturas emitidas" trend="Datos registrados" tone="green"/><Kpi icon="▧" value={total.toLocaleString("es-AR",{minimumFractionDigits:0})} label="Monto facturado" trend="Importes registrados" tone="blue"/><Kpi icon="$" value={amountLabel(pendientes)} label="Pendientes ARCA" trend={rows.filter(f=>status(f)==="Pendiente ARCA").length+" facturas"} tone="orange"/><Kpi icon="▥" value={amountLabel(autorizadas)} label="Autorizadas" trend={total?Math.round(autorizadas/total*100)+"% del total":"0% del total"} tone="mint"/><Kpi icon="!" value={String(rows.filter(f=>status(f)==="Rechazada").length)} label="Rechazadas" trend={amountLabel(rechazadas)} tone="red"/></section>
  <div className="billing-tabs">{["Todas las facturas","Autorizadas","Observadas","Rechazadas","Pendiente ARCA","Error integración","Notas de crédito/débito","ARCA"].map(x=>{const v=x==="Todas las facturas"?"":x;return <button key={x} className={tab===v?"active":""} onClick={()=>setTab(v)}>{x}</button>})}</div>
  <section className="billing-layout"><div className="billing-table-card"><div className="billing-table-head"><span>Nº FACTURA</span><span>FECHA</span><span>EMPRESA</span><span>CONCEPTO</span><span>PRODUCTO</span><span>TN</span><span>MONTO</span><span>ESTADO</span><span>ACCIONES</span></div>{loading?<div className="billing-empty">Cargando facturación…</div>:visible.map((f)=>{const s=status(f),empresa=f.razon_social_receptor||f.razon_social_emisor||"Empresa comercial";return <div className="billing-row" key={f.id}><span className="invoice-code">{f.numero_factura||"Sin número ARCA"}</span><span>{f.fecha_emision?new Date(f.fecha_emision).toLocaleDateString("es-AR"):"—"}</span><span className="billing-company"><strong>{empresa}</strong></span><span>{f.tipo_factura||"Comprobante"}</span><span className="billing-product"><b>—</b>Según comprobante</span><span>{Number((ops.find(o=>o.id===f.operacion_id)?.cantidad_tn)||0).toLocaleString("es-AR")}</span><span><strong>{Number(f.importe_total||0).toLocaleString("es-AR",{minimumFractionDigits:0})}</strong> {f.moneda_id ? `(${f.moneda_id})` : ""}</span><span><em className={"billing-status "+s.toLowerCase().replaceAll(" ","-")}>{s}</em></span><span className="billing-actions"><Link href={"/operaciones/"+f.operacion_id}>Ver</Link><button onClick={()=>setMsg("Opciones del comprobante "+(f.numero_factura||f.id))}>⋮</button></span></div>})}{!loading&&!filtered.length&&<div className="billing-empty">No hay comprobantes que coincidan con los filtros.</div>}<div className="billing-pagination"><button disabled={safePage<=1} onClick={()=>setPage(Math.max(1,safePage-1))}>‹ Anterior</button><b>{safePage}</b><span>de {totalPages}</span><button disabled={safePage>=totalPages} onClick={()=>setPage(Math.min(totalPages,safePage+1))}>Siguiente ›</button></div></div>
  <aside className="billing-filters"><div className="billing-filter-title"><h2>Filtros</h2><button onClick={clear}>Limpiar filtros</button></div><Filter label="Tipo de comprobante"><select value={fTipo} onChange={e=>setFTipo(e.target.value)}><option value="">Todos los tipos</option><option>Factura A</option><option>Factura B</option><option>Factura C</option><option>Factura M</option></select></Filter><Filter label="Estado"><select value={fEstado} onChange={e=>setFEstado(e.target.value)}><option value="">Todos los estados</option>{["Autorizada","Observada","Rechazada","Pendiente ARCA","Error integración"].map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Empresa"><select value={fEmpresa} onChange={e=>setFEmpresa(e.target.value)}><option value="">Todas las empresas</option>{[...new Set(rows.map(f=>f.razon_social_receptor||f.razon_social_emisor).filter(Boolean) as string[])].map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Rango de fecha"><div className="billing-two"><input type="date" value={fDesde} onChange={e=>setFDesde(e.target.value)}/><input type="date" value={fHasta} onChange={e=>setFHasta(e.target.value)}/></div></Filter><Filter label="Rango de monto"><div className="billing-two"><input placeholder="Mínimo" value={fMin} onChange={e=>setFMin(e.target.value)}/><input placeholder="Máximo" value={fMax} onChange={e=>setFMax(e.target.value)}/></div></Filter><Filter label="Moneda"><select value={fMoneda} onChange={e=>setFMoneda(e.target.value)}><option value="">Todas las monedas</option><option value="1">ARS</option><option value="2">USD</option><option value="3">EUR</option><option value="4">BRL</option></select></Filter><button className="billing-apply" onClick={()=>setMsg(filtered.length+" comprobantes coinciden con los filtros.")}>⚱ Aplicar filtros</button></aside></section>
  <section className="billing-bottom"><Bottom title="Facturación por mes"><div className="billing-empty">La evolución mensual se habilitará cuando existan comprobantes reales con fecha e importe.</div></Bottom><Bottom title="Facturación registrada"><div className="billing-donut"><b>{total.toLocaleString("es-AR",{maximumFractionDigits:0})}<small>Total registrado</small></b></div><Bars items={[]}/></Bottom><Bottom title="Estado de cobranza"><Bars items={[["Autorizadas",total?Math.round(autorizadas/total*100)+"%":"0%"],["Pendientes ARCA",total?Math.round(pendientes/total*100)+"%":"0%"],["Rechazadas",total?Math.round(rechazadas/total*100)+"%":"0%"],["Otros estados",total?Math.max(0,100-Math.round((autorizadas+pendientes+rechazadas)/total*100))+"%":"0%"]]}/></Bottom><Bottom title="Integración con ARCA"><div className="arca-card"><div><b>◎ ARCA</b><em>Integración implementada</em></div>{["Emisión y autorización vía WSFEv1","Obtención y almacenamiento de CAE","Control de punto de venta y numeración","Consulta/reconciliación de comprobantes","Auditoría de respuestas ARCA"].map(x=><p key={x}>✓ {x}</p>)}<Link href="/configuracion">Ver configuración</Link></div></Bottom></section>
  <section id="billing-emission" className="billing-emission"><h2>Emisión oficial</h2><p>Los CAE, numeración y autorización se obtienen exclusivamente de ARCA.</p><div className="billing-emission-grid"><select value={opId} onChange={e=>loadReceivers(e.target.value)}><option value="">Operación</option>{ops.filter(o=>o.estado==="CERRADA").map(o=><option key={o.id} value={o.id}>{o.codigo} · {Number(o.cantidad_tn).toLocaleString("es-AR")} TN</option>)}</select><select value={receiver} onChange={e=>setReceiver(e.target.value)}><option value="">Empresa receptora</option>{companies.map(c=><option key={c.id} value={c.id}>{c.razon_social} · CUIT {c.cuit}</option>)}</select><select value={tipo} onChange={e=>setTipo(Number(e.target.value))}><option value={1}>Factura A</option><option value={6}>Factura B</option><option value={11}>Factura C</option><option value={51}>Factura M</option></select><input placeholder="Punto de venta ARCA" value={pv} onChange={e=>setPv(e.target.value)}/><input placeholder="Importe neto" value={net} onChange={e=>setNet(e.target.value)}/><input placeholder="IVA" value={iva} onChange={e=>setIva(e.target.value)}/><button disabled={busy||!opId||!receiver} onClick={request}>{busy?"Procesando…":"Enviar a ARCA"}</button></div></section>
 </main>
}
function Kpi({icon,value,label,trend,tone}:{icon:string;value:string;label:string;trend:string;tone:string}){return <div className={"billing-kpi "+tone}><b>{icon}</b><span><strong>{value}</strong><small>{label}</small><i>{trend}</i></span></div>}
function Filter({label,children}:{label:string;children:any}){return <label className="billing-filter">{label}{children}</label>}
function Bottom({title,children}:{title:string;children:any}){return <section className="billing-bottom-card"><h2>{title}</h2>{children}</section>}
function Bars({items}:{items:string[][]}){return <div className="billing-bars-list">{items.map((x,i)=><div key={i}><span>{x[0]}</span><i style={{width:x[1]}}/><b>{x[1]}</b></div>)}</div>}
