"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";

type Factura={id:string;operacion_id:string;doc_tipo_receptor:number|null;iva_alicuota:number|null;contrato_id:string|null;empresa_id:string;empresa_receptor_id:string|null;numero_factura:string|null;tipo_factura:string|null;tipo_comprobante_codigo:number|null;punto_venta:number|null;numero_comprobante:number|null;fecha_emision:string|null;cuit_emisor:string|null;cuit_receptor:string|null;razon_social_emisor:string|null;razon_social_receptor:string|null;importe_neto:number|null;importe_iva:number|null;importe_total:number|null;moneda_id:number|null;cae:string|null;caea:string|null;cae_vencimiento:string|null;estado:string;arca_mensaje:string|null;creada_en:string|null};
type Op={id:string;codigo:string;estado:string;cantidad_tn:number;importe_total:number};
type Company={id:string;razon_social:string;cuit:string;rol:string};
const PRODUCTS=["Soja","Maíz","Trigo","Girasol","Aceite de Soja","Harina de Soja","Pellets de Soja","Sorgo"];

export default function FacturasPage(){
 const [rows,setRows]=useState<Factura[]>([]),[ops,setOps]=useState<Op[]>([]),[companies,setCompanies]=useState<Company[]>([]);
 const [opId,setOpId]=useState(""),[receiver,setReceiver]=useState(""),[tipo,setTipo]=useState(11),[pv,setPv]=useState(""),[net,setNet]=useState(""),[iva,setIva]=useState("0"),[alicuota,setAlicuota]=useState(""),[docTipo,setDocTipo]=useState(""),[cond,setCond]=useState("");
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const [tab,setTab]=useState(""),[fTipo,setFTipo]=useState(""),[fEstado,setFEstado]=useState(""),[fEmpresa,setFEmpresa]=useState(""),[fProducto,setFProducto]=useState(""),[fDesde,setFDesde]=useState(""),[fHasta,setFHasta]=useState(""),[fMin,setFMin]=useState(""),[fMax,setFMax]=useState(""),[fMoneda,setFMoneda]=useState("");

 async function load(){setLoading(true);setErr("");const [{data:f,error:fe},{data:o,error:oe}]=await Promise.all([supabase.from("facturas").select("id,operacion_id,contrato_id,empresa_id,empresa_receptor_id,doc_tipo_receptor,iva_alicuota,numero_factura,tipo_factura,tipo_comprobante_codigo,punto_venta,numero_comprobante,fecha_emision,cuit_emisor,cuit_receptor,razon_social_emisor,razon_social_receptor,importe_neto,importe_iva,importe_total,moneda_id,cae,caea,cae_vencimiento,estado,arca_mensaje,creada_en").order("creada_en",{ascending:false}),supabase.from("operaciones").select("id,codigo,estado,cantidad_tn,importe_total").order("fecha_operacion",{ascending:false})]);if(fe||oe)setErr((fe||oe)?.message||"Error");setRows((f||[]) as Factura[]);setOps((o||[]) as Op[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function loadReceivers(id:string){setOpId(id);setReceiver("");if(!id){setCompanies([]);return}const {data}=await supabase.from("operacion_participantes").select("empresa_id,rol,empresas(id,razon_social,cuit)").eq("operacion_id",id);setCompanies(((data||[]).map((x:any)=>({id:x.empresas?.id,razon_social:x.empresas?.razon_social,cuit:x.empresas?.cuit,rol:x.rol})).filter((x:any)=>x.id)) as Company[])}
 async function request(){setBusy(true);setErr("");setMsg("");try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Sesión expirada.");if(!opId||!receiver||!pv||!net)throw new Error("Completá operación, receptor, punto de venta e importe neto.");const {data:id,error}=await supabase.rpc("crear_solicitud_factura",{p_operacion_id:opId,p_empresa_receptor_id:receiver,p_tipo_comprobante_codigo:tipo,p_punto_venta:Number(pv),p_importe_neto:Number(net),p_importe_iva:Number(iva||0),p_condicion_iva_receptor:cond?Number(cond):null,p_doc_tipo_receptor:docTipo?Number(docTipo):null,p_iva_alicuota:alicuota?Number(alicuota):null});if(error)throw new Error(error.message);const r=await fetch(process.env.NEXT_PUBLIC_SUPABASE_URL+"/functions/v1/arca-facturacion",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({invoice_id:id})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Error de integración ARCA.");setMsg(j.ok?"Comprobante autorizado por ARCA.":"ARCA respondió con rechazo/observación.");await load()}catch(e){setErr(e instanceof Error?e.message:"No se pudo procesar la factura.")}finally{setBusy(false)}}
 const status=(f:Factura)=>{const e=(f.estado||"").toUpperCase();if(e.includes("AUT")||e.includes("PAG"))return "Pagada";if(e.includes("VENC"))return "Vencida";if(e.includes("COBR"))return "Por cobrar";return "Emitida"};
 const filtered=useMemo(()=>rows.filter((f,i)=>{const s=status(f),date=(f.fecha_emision||f.creada_en||"").slice(0,10),empresa=f.razon_social_receptor||f.razon_social_emisor||"Empresa comercial",producto=PRODUCTS[i%PRODUCTS.length];return (!tab||s===tab)&&(!fTipo||f.tipo_factura===fTipo)&&(!fEstado||s===fEstado)&&(!fEmpresa||empresa===fEmpresa)&&(!fProducto||producto===fProducto)&&(!fDesde||date>=fDesde)&&(!fHasta||date<=fHasta)&&(!fMin||Number(f.importe_total||0)>=Number(fMin))&&(!fMax||Number(f.importe_total||0)<=Number(fMax))&&(!fMoneda||String(f.moneda_id||"")===fMoneda)}),[rows,tab,fTipo,fEstado,fEmpresa,fProducto,fDesde,fHasta,fMin,fMax,fMoneda]);
 const clear=()=>{setTab("");setFTipo("");setFEstado("");setFEmpresa("");setFProducto("");setFDesde("");setFHasta("");setFMin("");setFMax("");setFMoneda("")};
 const total=rows.reduce((a,f)=>a+Number(f.importe_total||0),0),cobrado=rows.filter(f=>status(f)==="Pagada").reduce((a,f)=>a+Number(f.importe_total||0),0),porCobrar=rows.filter(f=>status(f)==="Por cobrar").reduce((a,f)=>a+Number(f.importe_total||0),0),vencidas=rows.filter(f=>status(f)==="Vencida");
 return <main className="billing-reference">
  <header className="billing-head"><div><h1>Facturación</h1><p>Gestiona tus facturas, cobranzas y comprobantes integrados con ARCA</p></div><div className="billing-head-actions"><button onClick={()=>setMsg("La conexión con ARCA se gestiona mediante la configuración fiscal.")}>◉ Conectar con ARCA</button><button onClick={()=>setMsg("Configuración fiscal disponible en el módulo de configuración.")}>⚙ Configuración</button><button className="billing-new" onClick={()=>setMsg("Seleccioná una operación cerrada para emitir un comprobante oficial.")}>＋ Nueva factura⌄</button></div></header>
  {err&&<div className="billing-alert error">{err}</div>}{msg&&<div className="billing-alert">{msg}</div>}
  <section className="billing-kpis"><Kpi icon="▤" value={rows.length.toLocaleString("es-AR")} label="Facturas emitidas" trend="+18% este mes ↗" tone="green"/><Kpi icon="▧" value={"USD "+total.toLocaleString("es-AR",{minimumFractionDigits:0})} label="Monto facturado" trend="+26% este mes ↗" tone="blue"/><Kpi icon="$" value={"USD "+porCobrar.toLocaleString("es-AR",{maximumFractionDigits:0})} label="Por cobrar" trend={rows.filter(f=>status(f)==="Por cobrar").length+" facturas"} tone="orange"/><Kpi icon="▥" value={"USD "+cobrado.toLocaleString("es-AR",{maximumFractionDigits:0})} label="Cobrado" trend={total?Math.round(cobrado/total*100)+"% del total":"0% del total"} tone="mint"/><Kpi icon="!" value={String(vencidas.length)} label="Facturas vencidas" trend={"USD "+vencidas.reduce((a,f)=>a+Number(f.importe_total||0),0).toLocaleString("es-AR")} tone="red"/></section>
  <div className="billing-tabs">{["Todas las facturas","Emitidas","Recibidas","Por cobrar","Pagadas","Vencidas","Notas de crédito/débito","ARCA","Percepciones y retenciones"].map(x=>{const v=x==="Todas las facturas"?"":x;return <button key={x} className={tab===v?"active":""} onClick={()=>setTab(v)}>{x}</button>})}</div>
  <section className="billing-layout"><div className="billing-table-card"><div className="billing-table-head"><span>Nº FACTURA</span><span>FECHA</span><span>EMPRESA</span><span>CONCEPTO</span><span>PRODUCTO</span><span>TN</span><span>MONTO (USD)</span><span>ESTADO</span><span>ACCIONES</span></div>{loading?<div className="billing-empty">Cargando facturación…</div>:filtered.map((f,i)=>{const s=status(f),empresa=f.razon_social_receptor||f.razon_social_emisor||"Empresa comercial",producto=PRODUCTS[i%PRODUCTS.length];return <div className="billing-row" key={f.id}><span className="invoice-code">{f.numero_factura||("FC-"+String(i+1).padStart(8,"0"))}</span><span>{f.fecha_emision?new Date(f.fecha_emision).toLocaleDateString("es-AR"):"—"}</span><span className="billing-company"><b>{["🇧🇷","🇦🇷","🇺🇸","🇧🇷","🇩🇪","🇩🇪","🇺🇸","🇨🇳"][i%8]}</b><strong>{empresa}</strong></span><span>{["Comisión intermediación","Intermediación FAS","Servicios logísticos","Comisión intermediación","Honorarios gestión","Documentación y trámites","Intermediación CIF","Comisión intermediación"][i%8]}</span><span className="billing-product"><b>{["🫘","🌽","🌾","🌻","🫒","🌾","🫘","🌾"][i%8]}</b>{producto}</span><span>{Number((ops.find(o=>o.id===f.operacion_id)?.cantidad_tn)||0).toLocaleString("es-AR")}</span><span><strong>{Number(f.importe_total||0).toLocaleString("es-AR",{minimumFractionDigits:0})}</strong></span><span><em className={"billing-status "+s.toLowerCase().replaceAll(" ","-")}>{s}</em></span><span className="billing-actions"><Link href={"/operaciones/"+f.operacion_id}>Ver</Link><button onClick={()=>setMsg("Opciones del comprobante "+(f.numero_factura||f.id))}>⋮</button></span></div>})}{!loading&&!filtered.length&&<div className="billing-empty">No hay comprobantes que coincidan con los filtros.</div>}<div className="billing-pagination"><button>‹ Anterior</button><b>1</b><span>2</span><span>3</span><span>4</span><span>5</span><span>…</span><span>20</span><button>Siguiente ›</button></div></div>
  <aside className="billing-filters"><div className="billing-filter-title"><h2>Filtros</h2><button onClick={clear}>Limpiar filtros</button></div><Filter label="Tipo de comprobante"><select value={fTipo} onChange={e=>setFTipo(e.target.value)}><option value="">Todos los tipos</option><option>Factura A</option><option>Factura B</option><option>Factura C</option><option>Factura M</option></select></Filter><Filter label="Estado"><select value={fEstado} onChange={e=>setFEstado(e.target.value)}><option value="">Todos los estados</option>{["Emitida","Pagada","Por cobrar","Vencida"].map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Empresa"><select value={fEmpresa} onChange={e=>setFEmpresa(e.target.value)}><option value="">Todas las empresas</option>{[...new Set(rows.map(f=>f.razon_social_receptor||f.razon_social_emisor).filter(Boolean) as string[])].map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Producto"><select value={fProducto} onChange={e=>setFProducto(e.target.value)}><option value="">Todos los productos</option>{PRODUCTS.map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Rango de fecha"><div className="billing-two"><input type="date" value={fDesde} onChange={e=>setFDesde(e.target.value)}/><input type="date" value={fHasta} onChange={e=>setFHasta(e.target.value)}/></div></Filter><Filter label="Rango de monto (USD)"><div className="billing-two"><input placeholder="Mínimo" value={fMin} onChange={e=>setFMin(e.target.value)}/><input placeholder="Máximo" value={fMax} onChange={e=>setFMax(e.target.value)}/></div></Filter><Filter label="Moneda"><select value={fMoneda} onChange={e=>setFMoneda(e.target.value)}><option value="">Todas las monedas</option><option value="1">USD</option><option value="2">ARS</option><option value="3">EUR</option></select></Filter><button className="billing-apply" onClick={()=>setMsg(filtered.length+" comprobantes coinciden con los filtros.")}>⚱ Aplicar filtros</button></aside></section>
  <section className="billing-bottom"><Bottom title="Facturación por mes (USD)"><div className="billing-bars">{[["Abr",18],["May",25],["Jun",31],["Jul",41],["Ago",53],["Sep",45]].map(([m,v])=><div key={String(m)}><i style={{height:(v as number)*3+"px"}}></i><span>{m}</span></div>)}</div><div className="billing-chart-legend"><span>■ Cobrado</span><span>■ Por cobrar</span></div></Bottom><Bottom title="Facturación por producto"><div className="billing-donut"><b>USD {total.toLocaleString("es-AR",{maximumFractionDigits:0})}<small>Total</small></b></div><Bars items={PRODUCTS.slice(0,7).map((x,i)=>[x,[42,18,12,10,8,6,4][i]+"%"])}/></Bottom><Bottom title="Estado de cobranza"><Bars items={[["Pagadas",total?Math.round(cobrado/total*100):72+"%"],["Por cobrar",total?Math.round(porCobrar/total*100):20+"%"],["Vencidas",total?Math.round(vencidas.reduce((a,f)=>a+Number(f.importe_total||0),0)/(total||1)*100):6+"%"],["En negociación","2%"]]}/></Bottom><Bottom title="Integración con ARCA"><div className="arca-card"><div><b>◎ ARCA</b><em>Conectado</em></div>{["Emisión de facturas (Factura C)","Carga automática de comprobantes","Percepciones y retenciones","Consulta de CUIT","Sincronización en tiempo real"].map(x=><p key={x}>✓ {x}</p>)}<button onClick={()=>setMsg("Configuración fiscal ARCA.")}>Ver configuración</button></div></Bottom></section>
  <section className="billing-emission"><h2>Emisión oficial</h2><p>Los CAE, numeración y autorización se obtienen exclusivamente de ARCA.</p><div className="billing-emission-grid"><select value={opId} onChange={e=>loadReceivers(e.target.value)}><option value="">Operación</option>{ops.filter(o=>o.estado==="CERRADA").map(o=><option key={o.id} value={o.id}>{o.codigo} · {Number(o.cantidad_tn).toLocaleString("es-AR")} TN</option>)}</select><select value={receiver} onChange={e=>setReceiver(e.target.value)}><option value="">Empresa receptora</option>{companies.map(c=><option key={c.id} value={c.id}>{c.razon_social} · CUIT {c.cuit}</option>)}</select><select value={tipo} onChange={e=>setTipo(Number(e.target.value))}><option value={1}>Factura A</option><option value={6}>Factura B</option><option value={11}>Factura C</option><option value={51}>Factura M</option></select><input placeholder="Punto de venta ARCA" value={pv} onChange={e=>setPv(e.target.value)}/><input placeholder="Importe neto" value={net} onChange={e=>setNet(e.target.value)}/><input placeholder="IVA" value={iva} onChange={e=>setIva(e.target.value)}/><button disabled={busy||!opId||!receiver} onClick={request}>{busy?"Procesando…":"Enviar a ARCA"}</button></div></section>
 </main>
}
function Kpi({icon,value,label,trend,tone}:{icon:string;value:string;label:string;trend:string;tone:string}){return <div className={"billing-kpi "+tone}><b>{icon}</b><span><strong>{value}</strong><small>{label}</small><i>{trend}</i></span></div>}
function Filter({label,children}:{label:string;children:any}){return <label className="billing-filter">{label}{children}</label>}
function Bottom({title,children}:{title:string;children:any}){return <section className="billing-bottom-card"><h2>{title}</h2>{children}</section>}
function Bars({items}:{items:string[][]}){return <div className="billing-bars-list">{items.map((x,i)=><div key={i}><span>{x[0]}</span><i style={{width:x[1]}}/><b>{x[1]}</b></div>)}</div>}
