"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";

type Profile={name:string;email:string;phone:string;city:string;country:string;avatar:string;role:string;company:string;verified:boolean;language:string;timezone:string};
type EditState={name:string;email:string;phone:string;city:string;country:string;role:string;company:string;language:string;timezone:string};
export default function PerfilPage(){
 const [p,setP]=useState<Profile>({name:"Usuario AgroBrokerIA",email:"",phone:"",city:"",country:"",avatar:"",role:"",company:"",verified:false,language:"Español",timezone:"GMT-3 (Buenos Aires)"});
 const [edit,setEdit]=useState<EditState>({name:"",email:"",phone:"",city:"",country:"",role:"",company:"",language:"Español",timezone:"GMT-3 (Buenos Aires)"});
 const [editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const [passwords,setPasswords]=useState({current:"",next:"",confirm:""}),[changingPassword,setChangingPassword]=useState(false);
 const openDocument=(name:string)=>window.location.href=`/documentos?documento=${encodeURIComponent(name)}`;
 const exportData=()=>{const blob=new Blob([JSON.stringify({perfil:p,exportado_en:new Date().toISOString()},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="agrobrokeria-perfil.json";a.click();URL.revokeObjectURL(url)};
 const requestDeletion=()=>{window.location.href="mailto:soporte@agrobroker.com?subject=Solicitud%20de%20eliminacion%20de%20cuenta&body=Solicito%20iniciar%20el%20proceso%20de%20eliminacion%20de%20mi%20cuenta%20AgroBrokerIA.";};
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data:db}=await supabase.from("profiles").select("nombre,email,empresa,telefono,provincia,tipo_usuario,idioma,pais_iso,zona_horaria").eq("id",user.id).maybeSingle();const m=user.user_metadata||{};const name=String(db?.nombre||m.nombre||m.full_name||m.name||user.email?.split("@")[0]||"Usuario AgroBrokerIA");const role=String(db?.tipo_usuario||m.rol||m.role||"");const company=String(db?.empresa||m.empresa||m.company||"");const language=String(db?.idioma||m.idioma||"Español");const timezone=String(db?.zona_horaria||m.zona_horaria||"GMT-3 (Buenos Aires)");const next={name,email:String(user.email||db?.email||""),phone:String(db?.telefono||m.telefono||m.phone||""),city:String(m.ciudad||m.city||""),country:String(db?.pais_iso||m.pais||m.country||""),avatar:String(m.avatar_url||m.picture||""),role,company,verified:Boolean(m.verificada||m.verified),language,timezone};setP(next);setEdit({name:next.name,email:next.email,phone:next.phone,city:next.city,country:next.country,role:next.role,company:next.company,language:next.language,timezone:next.timezone});setLoading(false)})()},[]);
 const beginEdit=()=>{setEdit({name:p.name,email:p.email,phone:p.phone,city:p.city,country:p.country,role:p.role,company:p.company,language:p.language,timezone:p.timezone});setMessage("");setEditing(true)};
 const save=async()=>{setSaving(true);setMessage("");const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage("La sesión expiró.");setSaving(false);return}const {error:dbError}=await supabase.from("profiles").update({nombre:edit.name,email:edit.email,telefono:edit.phone,provincia:edit.city,pais_iso:edit.country,tipo_usuario:edit.role,empresa:edit.company,idioma:edit.language,zona_horaria:edit.timezone}).eq("id",user.id);if(dbError){setMessage("No se pudieron guardar los datos: "+dbError.message);setSaving(false);return}const {error:authError}=await supabase.auth.updateUser({email:edit.email,data:{nombre:edit.name,telefono:edit.phone,ciudad:edit.city,pais:edit.country,rol:edit.role,empresa:edit.company,idioma:edit.language,zona_horaria:edit.timezone}});if(authError){setMessage("Datos guardados, pero el correo requiere confirmación: "+authError.message)}else setMessage("Perfil actualizado correctamente.");setP({...p,...edit});setEditing(false);setSaving(false)};
 const changePassword=async()=>{if(!passwords.current||!passwords.next||!passwords.confirm){setMessage("Completá los tres campos de contraseña.");return}if(passwords.next.length<8){setMessage("La nueva contraseña debe tener al menos 8 caracteres.");return}if(passwords.next!==passwords.confirm){setMessage("La confirmación no coincide.");return}setChangingPassword(true);setMessage("");const {data:{user}}=await supabase.auth.getUser();if(!user?.email){setMessage("No se pudo validar la cuenta.");setChangingPassword(false);return}const {error:reauth}=await supabase.auth.signInWithPassword({email:user.email,password:passwords.current});if(reauth){setMessage("La contraseña actual no es correcta.");setChangingPassword(false);return}const {error}=await supabase.auth.updateUser({password:passwords.next});setMessage(error?"No se pudo cambiar la contraseña: "+error.message:"Contraseña actualizada correctamente.");if(!error)setPasswords({current:"",next:"",confirm:""});setChangingPassword(false)};
 if(loading)return <main className="profile-reference"><div className="profile-loading">Cargando perfil...</div></main>;
 const initials=p.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase();
 const field=(key:keyof EditState,label:string,placeholder?:string)=><label className="profile-edit-field"><span>{label}</span><input value={edit[key]} onChange={e=>setEdit({...edit,[key]:e.target.value})} placeholder={placeholder}/></label>;
 return <main className="profile-reference">
  <header className="profile-head"><div><h1>Mi Perfil</h1><p>Gestioná toda tu información personal, empresarial y de seguridad desde este lugar.</p></div><button className="profile-edit" onClick={editing?()=>setEditing(false):beginEdit}>{editing?"Cancelar":"✎  Editar perfil"}</button></header>
  {message&&<div className={message.includes("correctamente")?"profile-message success":"profile-message"}>{message}</div>}
  <nav className="profile-tabs">{[["Información general","#general"],["Empresa","#empresa"],["Verificación","#verificacion"],["Preferencias","#preferencias"],["Seguridad","#seguridad"],["Facturación","/facturas"],["Notificaciones","/notificaciones"],["Actividad","/historial"]].map(([x,h],i)=>h.startsWith("#")?<a className={i===0?"active":""} href={h} key={x}>{x}</a>:<Link className="" href={h} key={x}>{x}</Link>)}</nav>
  {editing&&<section className="profile-card profile-editor" id="general"><h2>Editar información del perfil</h2><div className="profile-edit-grid">{field("name","Nombre completo")} {field("email","Correo electrónico")} {field("phone","Teléfono")} {field("city","Ciudad / Provincia")} {field("country","País")} {field("role","Tipo de usuario")} {field("company","Empresa")} {field("language","Idioma")} {field("timezone","Zona horaria")}</div><div className="profile-editor-actions"><button onClick={()=>setEditing(false)}>Cancelar</button><button className="primary" onClick={save} disabled={saving}>{saving?"Guardando...":"Guardar cambios"}</button></div></section>}
  <section className="profile-top" id="general">
   <div className="profile-card identity"><div className="profile-avatar">{p.avatar?<img src={p.avatar} alt="Perfil"/>:initials}</div><div><h2>{p.name}<span className="verified">✓</span></h2><p className="profile-role">{[p.role,p.company].filter(Boolean).join(" | ")||"Datos profesionales no registrados"}</p><div className="profile-tags">{p.role&&<b>{p.role}</b>}<b className={p.verified?"green":""}>{p.verified?"● Verificada":"Verificación no registrada"}</b></div><p className="bio">La información mostrada corresponde a los datos registrados en tu cuenta.</p></div></div>
   <div className="profile-card contact"><h2>Información de contacto <button onClick={beginEdit}>Editar</button></h2><p>✉ <span>{p.email||"Correo no registrado"}</span></p><p>⌕ <span>{p.phone||"Teléfono no registrado"}</span></p><p>⌖ <span>{p.city||"Ubicación no registrada"}</span></p><p>▣ <span>Sitio web no registrado</span></p></div>
   <div className="profile-card reputation"><h2>Nivel y reputación</h2><div className="gold-badge">♛</div><div className="rep-copy"><strong>{p.verified?"Verificada":"Sin nivel registrado"}</strong><span>{p.verified?"Estado de verificación registrado":"No se consultó una puntuación de reputación"}</span></div></div>
  </section>
  <section className="profile-kpis"><K icon="▤" value="—" label="Operaciones: no consultado"/><K icon="▥" value="—" label="Comisiones: no consultado"/><K icon="♧" value="—" label="Empresas relacionadas: no consultado"/><K icon="▦" value="—" label="Antigüedad: no consultada"/><K icon="▥" value={p.verified?"Verificada":"—"} label="Reputación registrada"/></section>
  <section className="profile-columns">
   <Card title="Información personal" edit onEdit={beginEdit}><Rows rows={[[ "♙","Nombre completo",p.name],["▦","Fecha de nacimiento","No registrada"],["⊕","País",p.country],["♧","Ciudad",p.city],["◉","Idioma principal",p.language],["◉","Idiomas adicionales","Inglés, Português"],["◷","Zona horaria",p.timezone]]}/></Card>
   <Card title="Información empresarial" edit onEdit={beginEdit}><Rows rows={[["♜","Nombre comercial",p.company||"No registrado"],["▣","CUIT","No registrada"],["▤","Tipo de empresa",p.role||"No registrada"],["▤","País",p.country||"No registrado"],["⌖","Dirección",p.city||"No registrada"],["▤","Sitio web","No registrado"],["♙","Actividad principal","No registrada"],["▦","Productos de interés","No registrados"],["◎","Mercados","No registrados"]]}/></Card>
   <Card title="Documentación y verificación"><div className="docs">{["Documento de identidad","CUIT / Constancia fiscal","Comprobante de domicilio","Certificación de empresa","Referencias comerciales","Verificación KYC","Cuenta bancaria"].map(x=><div key={x}><span>●</span>{x}<b>Verificado</b><button onClick={()=>openDocument(x)}>Ver</button></div>)}</div></Card>
  </section>
  <section className="profile-bottom" id="preferencias">
   <Card title="Mis intereses" edit onEdit={beginEdit}><h4>Productos</h4><div className="chips"><span>No registrados</span></div><h4>Tipos de operación</h4><div className="chips"><span>No registrados</span></div><h4>Países de interés</h4><div className="chips"><span>No registrados</span><span className="add" role="button" tabIndex={0} onClick={beginEdit}>＋ Agregar</span></div></Card>
   <Card title="Preferencias de la plataforma" edit onEdit={beginEdit}><Rows rows={[["⊕","Idioma de la plataforma",p.language],["◉","Tema visual","Claro"],["♧","Notificaciones por email","Activadas"],["♧","Notificaciones push","Activadas"],["✉","Alertas de oportunidades IA","Activadas"],["▥","Resumen diario del mercado","Activado"]]}/></Card>
   <Card title="Acciones rápidas"><div className="quick-profile"><a href="#seguridad">🔑 <b>Cambiar contraseña</b><small>Desde Perfil, sin salir a Configuración →</small></a><Link href="/notificaciones">⚙ <b>Configurar notificaciones</b><small>Personaliza tus alertas →</small></Link><button onClick={exportData}>⇩ <b>Exportar mis datos</b><small>Descarga tu información →</small></button><button className="danger" onClick={requestDeletion}>♜ <b>Eliminar cuenta</b><small>Solicitar eliminación →</small></button></div></Card>
  </section>
  <section className="profile-card profile-security" id="seguridad"><h2>Seguridad de mi perfil</h2><p>Cambiá tu contraseña sin salir de Perfil. Primero validamos tu contraseña actual.</p><div className="password-grid"><input type="password" placeholder="Contraseña actual" value={passwords.current} onChange={e=>setPasswords({...passwords,current:e.target.value})}/><input type="password" placeholder="Nueva contraseña" value={passwords.next} onChange={e=>setPasswords({...passwords,next:e.target.value})}/><input type="password" placeholder="Repetir nueva contraseña" value={passwords.confirm} onChange={e=>setPasswords({...passwords,confirm:e.target.value})}/><button onClick={changePassword} disabled={changingPassword}>{changingPassword?"Actualizando...":"Cambiar contraseña"}</button></div></section>
 </main>
}
function K({icon,value,label}:{icon:string;value:string;label:string}){return <div><i>{icon}</i><strong>{value}</strong><span>{label}</span></div>}
function Card({title,children,edit,onEdit}:{title:string;children:React.ReactNode;edit?:boolean;onEdit?:()=>void}){return <div className="profile-card info-card"><h2>{title}{edit&&<button onClick={onEdit}>Editar</button>}</h2>{children}</div>}
function Rows({rows}:{rows:string[][]}){return <div className="profile-rows">{rows.map(r=><div key={r[1]}><i>{r[0]}</i><span>{r[1]}</span><b>{r[2]}</b></div>)}</div>}