"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {supabase} from "@/lib/supabase/client";
type Profile={name:string;email:string;phone:string;city:string;country:string;avatar:string;role:string;company:string;verified:boolean};
export default function PerfilPage(){
 const [p,setP]=useState<Profile>({name:"Usuario AgroBrokerIA",email:"",phone:"",city:"",country:"",avatar:"",role:"",company:"",verified:false});
 const [loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState("");
 const router=useRouter();
 const [edit,setEdit]=useState({name:"",phone:"",city:"",country:"",company:"",cuit:"",role:"",language:"es",theme:"Claro",emailAlerts:true,pushAlerts:true,dailySummary:true,products:"",operations:"",interestCountries:""});
 const goEdit=()=>{const m=JSON.parse(JSON.stringify((window as any).__agroProfileMeta||{}));setEdit({name:p.name,phone:p.phone,city:p.city,country:p.country,company:p.company,cuit:String(m.cuit||""),role:p.role,language:String(m.idioma||"es"),theme:String(m.theme||"Claro"),emailAlerts:m.emailAlerts!==false,pushAlerts:m.pushAlerts!==false,dailySummary:m.dailySummary!==false,products:String(m.products||""),operations:String(m.operations||""),interestCountries:String(m.interestCountries||"")});setSaveError("");setEditing(true);};
 const saveProfile=async()=>{setSaving(true);setSaveError("");try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesión no disponible.");const meta={...user.user_metadata,nombre:edit.name,telefono:edit.phone,ciudad:edit.city,pais:edit.country,empresa:edit.company,cuit:edit.cuit,rol:edit.role,idioma:edit.language,theme:edit.theme,emailAlerts:edit.emailAlerts,pushAlerts:edit.pushAlerts,dailySummary:edit.dailySummary,products:edit.products,operations:edit.operations,interestCountries:edit.interestCountries};const {error}=await supabase.auth.updateUser({data:meta});if(error)throw error;const {error:pe}=await supabase.from("profiles").update({nombre:edit.name,email:user.email||null,telefono:edit.phone,provincia:edit.city,pais_iso:edit.country,tipo_usuario:edit.role||null,idioma:edit.language}).eq("id",user.id);if(pe)throw pe;setP(x=>({...x,name:edit.name||x.name,phone:edit.phone,city:edit.city,country:edit.country,company:edit.company,role:edit.role}));(window as any).__agroProfileMeta=meta;setEditing(false);window.dispatchEvent(new Event("agrobrokeria:profile-changed"));}catch(e){setSaveError(e instanceof Error?e.message:"No se pudo guardar el perfil.");}finally{setSaving(false)}};
 const openDocument=(name:string)=>router.push(`/documentos?documento=${encodeURIComponent(name)}`);
 const exportData=()=>{const blob=new Blob([JSON.stringify({perfil:p,exportado_en:new Date().toISOString()},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="agrobrokeria-perfil.json";a.click();URL.revokeObjectURL(url)};
 const requestDeletion=()=>{window.location.href="mailto:soporte@agrobrokeria.com?subject=Solicitud%20de%20eliminacion%20de%20cuenta&body=Solicito%20iniciar%20el%20proceso%20de%20eliminacion%20de%20mi%20cuenta%20AgroBrokerIA.";};
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const m=user.user_metadata||{};(window as any).__agroProfileMeta=m;setP({name:m.nombre||m.full_name||m.name||user.email?.split("@")[0]||"Usuario AgroBrokerIA",email:user.email||"",phone:m.telefono||m.phone||"",city:m.ciudad||m.city||"",country:m.pais||m.country||"",avatar:m.avatar_url||m.picture||"",role:m.rol||m.role||"",company:m.empresa||m.company||"",verified:Boolean(m.verificada||m.verified)});setLoading(false)})()},[]);
 if(loading)return <main className="profile-reference"><div className="profile-loading">Cargando perfil...</div></main>;
 const initials=p.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase();
 return <main className="profile-reference">
  <header className="profile-head"><div><h1>Mi Perfil</h1><p>Gestiona tu información personal, empresarial y preferencias de la plataforma</p></div><button className="profile-edit" onClick={goEdit}>✎ &nbsp; Editar perfil</button></header>
  {editing&&<section className="profile-editor-card"><div className="profile-editor-head"><div><h2>Editar perfil</h2><p>Modificá tus datos directamente desde tu perfil.</p></div><button type="button" onClick={()=>setEditing(false)} className="profile-editor-close">×</button></div>{saveError&&<div className="profile-editor-error">{saveError}</div>}<div className="profile-editor-grid"><label>Nombre completo<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Teléfono<input value={edit.phone} onChange={e=>setEdit({...edit,phone:e.target.value})}/></label><label>País<input value={edit.country} onChange={e=>setEdit({...edit,country:e.target.value})}/></label><label>Ciudad / provincia<input value={edit.city} onChange={e=>setEdit({...edit,city:e.target.value})}/></label><label>Empresa / nombre comercial<input value={edit.company} onChange={e=>setEdit({...edit,company:e.target.value})}/></label><label>CUIT<input value={edit.cuit} onChange={e=>setEdit({...edit,cuit:e.target.value})}/></label><label>Tipo / rol<input value={edit.role} readOnly/></label><label>Idioma principal<select value={edit.language} onChange={e=>setEdit({...edit,language:e.target.value})}><option value="es">Español</option><option value="en">English</option><option value="pt">Português</option><option value="it">Italiano</option><option value="fr">Français</option><option value="de">Deutsch</option></select></label><label>Tema visual<select value={edit.theme} onChange={e=>setEdit({...edit,theme:e.target.value})}><option>Claro</option><option>Oscuro</option></select></label><label>Productos de interés<input value={edit.products} onChange={e=>setEdit({...edit,products:e.target.value})} placeholder="Separados por coma"/></label><label>Tipos de operación<input value={edit.operations} onChange={e=>setEdit({...edit,operations:e.target.value})} placeholder="Separados por coma"/></label><label>Países de interés<input value={edit.interestCountries} onChange={e=>setEdit({...edit,interestCountries:e.target.value})} placeholder="Separados por coma"/></label><label className="profile-check"><input type="checkbox" checked={edit.emailAlerts} onChange={e=>setEdit({...edit,emailAlerts:e.target.checked})}/> Notificaciones por email</label><label className="profile-check"><input type="checkbox" checked={edit.pushAlerts} onChange={e=>setEdit({...edit,pushAlerts:e.target.checked})}/> Notificaciones push</label><label className="profile-check"><input type="checkbox" checked={edit.dailySummary} onChange={e=>setEdit({...edit,dailySummary:e.target.checked})}/> Resumen diario del mercado</label></div><div className="profile-editor-actions"><button type="button" className="profile-editor-cancel" onClick={()=>setEditing(false)}>Cancelar</button><button type="button" className="profile-editor-save" onClick={saveProfile} disabled={saving}>{saving?"Guardando…":"Guardar cambios"}</button></div></section>}
  <nav className="profile-tabs">{[["Información general","/perfil"],["Empresa","/empresas"],["Verificación","/verificaciones"],["Preferencias","/configuracion"],["Seguridad","/seguridad"],["Facturación","/facturas"],["Notificaciones","/notificaciones"],["Actividad","/historial"]].map(([x,h],i)=><Link className={i===0?"active":""} href={h} key={x}>{x}</Link>)}</nav>
  <section className="profile-top">
   <div className="profile-card identity"><div className="profile-avatar">{p.avatar?<img src={p.avatar} alt="Perfil"/>:initials}</div><div><h2>{p.name}<span className="verified">✓</span></h2><p className="profile-role">{[p.role,p.company].filter(Boolean).join(" | ")||"Datos profesionales no registrados"}</p><div className="profile-tags">{p.role&&<b>{p.role}</b>}<b className={p.verified?"green":""}>{p.verified?"● Verificada":"Verificación no registrada"}</b></div><p className="bio">La información mostrada corresponde a los datos registrados en tu cuenta.</p></div></div>
   <div className="profile-card contact"><h2>Información de contacto <button onClick={goEdit}>Editar</button></h2><p>✉ <span>{p.email||"Correo no registrado"}</span></p><p>⌕ <span>{p.phone||"Teléfono no registrado"}</span></p><p>⌖ <span>{p.city||"Ubicación no registrada"}</span></p><p>▣ <span>Sitio web no registrado</span></p></div>
   <div className="profile-card reputation"><h2>Nivel y reputación</h2><div className="gold-badge">♛</div><div className="rep-copy"><strong>{p.verified?"Verificada":"Sin nivel registrado"}</strong><span>{p.verified?"Estado de verificación registrado":"No se consultó una puntuación de reputación"}</span></div></div>
  </section>
  <section className="profile-kpis"><K icon="▤" value="—" label="Operaciones: no consultado"/><K icon="▥" value="—" label="Comisiones: no consultado"/><K icon="♧" value="—" label="Empresas relacionadas: no consultado"/><K icon="▦" value="—" label="Antigüedad: no consultada"/><K icon="▥" value={p.verified?"Verificada":"—"} label="Reputación registrada"/></section>
  <section className="profile-columns">
   <Card title="Información personal" edit onEdit={goEdit}><Rows rows={[[ "♙","Nombre completo",p.name],["▦","Fecha de nacimiento","No registrada"],["⊕","País",p.country],["♧","Ciudad",p.city],["◉","Idioma principal","Español"],["◉","Idiomas adicionales","Inglés, Português"],["◷","Zona horaria","GMT-3 (Buenos Aires)"]]}/></Card>
   <Card title="Información empresarial" edit onEdit={goEdit}><Rows rows={[["♜","Nombre comercial",p.company||"No registrado"],["▣","CUIT","No registrada"],["▤","Tipo de empresa",p.role||"No registrada"],["▤","País",p.country||"No registrado"],["⌖","Dirección",p.city||"No registrada"],["▤","Sitio web","No registrado"],["♙","Actividad principal","No registrada"],["▦","Productos de interés","No registrados"],["◎","Mercados","No registrados"]]}/></Card>
   <Card title="Documentación y verificación"><div className="docs">{["Documento de identidad","CUIT / Constancia fiscal","Comprobante de domicilio","Certificación de empresa","Referencias comerciales","Verificación KYC","Cuenta bancaria"].map(x=><div key={x}><span>●</span>{x}<b>Verificado</b><button onClick={()=>openDocument(x)}>Ver</button></div>)}</div></Card>
  </section>
  <section className="profile-bottom">
   <Card title="Mis intereses" edit onEdit={goEdit}><h4>Productos</h4><div className="chips"><span>No registrados</span></div><h4>Tipos de operación</h4><div className="chips"><span>No registrados</span></div><h4>Países de interés</h4><div className="chips"><span>No registrados</span><span className="add" role="button" tabIndex={0} onClick={goEdit} onKeyDown={e=>e.key==="Enter"&&goEdit()}>＋ Agregar</span></div></Card>
   <Card title="Preferencias de la plataforma" edit onEdit={goEdit}><Rows rows={[["⊕","Idioma de la plataforma","Español"],["◉","Tema visual","Claro"],["♧","Notificaciones por email","Activadas"],["♧","Notificaciones push","Activadas"],["✉","Alertas de oportunidades IA","Activadas"],["▥","Resumen diario del mercado","Activado"]]}/></Card>
   <Card title="Acciones rápidas"><div className="quick-profile"><Link href="/seguridad">🔒 <b>Cambiar contraseña</b><small>Mantén tu cuenta segura →</small></Link><Link href="/notificaciones">⚙ <b>Configurar notificaciones</b><small>Personaliza tus alertas →</small></Link><button onClick={exportData}>⇩ <b>Exportar mis datos</b><small>Descarga tu información →</small></button><button className="danger" onClick={requestDeletion}>♜ <b>Eliminar cuenta</b><small>Solicitar eliminación →</small></button></div></Card>
  </section>
 </main>
}
function K({icon,value,label}:{icon:string;value:string;label:string}){return <div><i>{icon}</i><strong>{value}</strong><span>{label}</span></div>}
function Card({title,children,edit,onEdit}:{title:string;children:React.ReactNode;edit?:boolean;onEdit?:()=>void}){return <div className="profile-card info-card"><h2>{title}{edit&&<button onClick={onEdit}>Editar</button>}</h2>{children}</div>}
function Rows({rows}:{rows:string[][]}){return <div className="profile-rows">{rows.map(r=><div key={r[1]}><i>{r[0]}</i><span>{r[1]}</span><b>{r[2]}</b></div>)}</div>}