"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase/client";
type Quote={id:string;source:string;market_date:string;obtained_at:string;price:number|null;currency:string|null;unit:string|null;price_type:string;position:string|null;market:string|null;port:string|null;freshness:string;commodity_id:string|null};
const names=new Map([["SOJA","Soja"],["MAIZ","Maíz"],["TRIGO","Trigo"],["GIRASOL","Girasol"],["SORGO","Sorgo"]]);
export default function MercadoPage(){const[quotes,setQuotes]=useState<Quote[]>([]),[commodities,setCommodities]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState(""),[syncMsg,setSyncMsg]=useState("");
async function load(){setLoading(true);setError("");const[{data:q,error:qe},{data:c,error:ce}]=await Promise.all([supabase.from("market_quotes").select("id,source,market_date,obtained_at,price,currency,unit,price_type,position,market,port,freshness,commodity_id").order("market_date",{ascending:false}).order("obtained_at",{ascending:false}).limit(100),supabase.from("commodities").select("id,codigo")]);if(qe||ce)setError(qe?.message||ce?.message||"No se pudo cargar mercado.");setQuotes((q||[])as Quote[]);setCommodities(Object.fromEntries((c||[]).map((x:any)=>[x.id,x.codigo])));setLoading(false)}useEffect(()=>{load()},[]);
async function sync(){setSyncing(true);setSyncMsg("");setError("");try{const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Necesitás iniciar sesión.");const r=await fetch(process.env.NEXT_PUBLIC_SUPABASE_URL+"/functions/v1/market-data-sync",{method:"POST",headers:{Authorization:"Bearer "+session.access_token}});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo actualizar BCR/CAC.");setSyncMsg("BCR/CAC actualizado. El histórico fue conservado.");await load()}catch(e){setError(e instanceof Error?e.message:"Error de actualización.")}finally{setSyncing(false)}}
const latest=new Map<string,Quote>();for(const q of quotes){const key=commodities[q.commodity_id||""]||q.commodity_id||"OTRO";if(!latest.has(key))latest.set(key,q)}
return <main className="module-page"><div className="module-hero"><div><span className="eyebrow">MERCADO AGRO · BCR / CAC</span><h1>Mercado</h1><p>Referencias normalizadas con fuente, fecha y trazabilidad. Cada actualización queda en histórico.</p></div><button className="primary-action" onClick={sync} disabled={syncing}>{syncing?"Actualizando…":"Actualizar BCR/CAC"}</button></div>{error&&<div className="module-alert module-alert-error">{error}</div>}{syncMsg&&<div className="module-alert">{syncMsg}</div>}<section className="dashboard-panel"><div className="panel-heading"><div><span className="eyebrow">PIZARRA</span><h2>Precios Cámara Arbitral</h2></div><span className="module-pill">Fuente BCR/CAC</span></div>{loading?<div className="loading-card">Cargando referencias…</div>:quotes.length===0?<div className="module-empty compact"><h3>Sin datos de mercado sincronizados</h3><p>AgroBrokerIA no inventa cotizaciones. Ejecutá una actualización para consultar la fuente.</p></div>:<div className="document-grid">{Array.from(latest.entries()).map(([code,q])=><article className="document-card" key={q.id}><div className="document-icon">$</div><div><strong>{names.get(code)||code}</strong><p>{q.price===null?"S/C":(q.currency||"")+" "+Number(q.price).toLocaleString("es-AR")+" / "+(q.unit||"T")}</p><small>{q.market_date} · {new Date(q.obtained_at).toLocaleString("es-AR")} · {q.source}</small></div><span className="document-status ok">{q.freshness}</span></article>)}</div>}</section><section className="dashboard-panel"><div className="panel-heading"><div><span className="eyebrow">FOB / FAS</span><h2>Referencias de exportación</h2></div></div>{quotes.filter(q=>q.price_type!=="PIZARRA_CAC").length===0?<div className="module-empty compact"><p>Todavía no hay referencias FOB/FAS sincronizadas.</p></div>:<div className="document-grid">{quotes.filter(q=>q.price_type!=="PIZARRA_CAC").slice(0,20).map(q=><article className="document-card" key={q.id}><div><strong>{q.price_type}</strong><p>{q.currency} {q.price} / {q.unit}</p><small>{q.market} · {q.port} · {q.position} · {q.market_date}</small></div></article>)}</div>}</section></main>}