"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase/client";
import Link from "next/link";

type Quote={id:string;source:string;market_date:string;obtained_at:string;price:number|null;currency:string|null;unit:string|null;price_type:string;position:string|null;market:string|null;port:string|null;freshness:string;commodity_id:string|null;product_id:number|null;variation:number|null;previous_value:number|null;};
type Pub={id:string;tipo:string;cantidad_tn:number;precio_tn:number;provincia:string|null;localidad:string|null;puerto:string|null;creada_en:string|null;productos?:{nombre:string}|{nombre:string}[]|null};
const names=new Map([["SOJA","Soja"],["MAIZ","Maíz"],["TRIGO","Trigo"],["GIRASOL","Girasol"],["SORGO","Sorgo"],["ACEITE_SOJA","Aceite de Soja"],["HARINA_SOJA","Harina de Soja"]]);
const icon=(code:string)=>code==="SOJA"?"🫘":code==="MAIZ"?"🌽":code==="TRIGO"?"🌾":code==="GIRASOL"?"🌻":"🌾";
const fmt=(q?:Quote|null)=>q?.price==null?"Sin cotización":`${q.currency||"USD"} ${Number(q.price).toLocaleString("es-AR",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const productName=(p:Pub)=>Array.isArray(p.productos)?p.productos[0]?.nombre||"Commodity":p.productos?.nombre||"Commodity";

export default function MercadoPage(){
 const[quotes,setQuotes]=useState<Quote[]>([]),[commodities,setCommodities]=useState<Record<string,string>>({}),[offers,setOffers]=useState<Pub[]>([]),[demands,setDemands]=useState<Pub[]>([]);
 const[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState(""),[syncMsg,setSyncMsg]=useState(""),[marketTab,setMarketTab]=useState("Granos"),[range,setRange]=useState("1D");
 async function load(){
  setLoading(true);setError("");
  const [qr,cr,pr]=await Promise.all([
   supabase.from("market_quotes").select("id,source,market_date,obtained_at,price,currency,unit,price_type,position,market,port,freshness,commodity_id,product_id,variation,previous_value").order("market_date",{ascending:false}).order("obtained_at",{ascending:false}).limit(200),
   supabase.from("commodities").select("id,codigo"),
   supabase.from("publicaciones").select("id,tipo,cantidad_tn,precio_tn,provincia,localidad,puerto,creada_en,productos(nombre)").eq("estado","PUBLICADA").order("creada_en",{ascending:false}).limit(12)
  ]);
  if(qr.error||cr.error||pr.error)setError(qr.error?.message||cr.error?.message||pr.error?.message||"No se pudo cargar mercado.");
  setQuotes((qr.data||[]) as Quote[]);setCommodities(Object.fromEntries((cr.data||[]).map((x:any)=>[x.id,x.codigo])));
  const pubs=(pr.data||[]) as Pub[];setOffers(pubs.filter(x=>x.tipo!=="DEMANDA").slice(0,5));setDemands(pubs.filter(x=>x.tipo==="DEMANDA").slice(0,5));setLoading(false);
 }
 useEffect(()=>{void load()},[]);
 async function sync(){
  setSyncing(true);setSyncMsg("");setError("");
  try{const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Necesitás iniciar sesión.");
   const r=await fetch(process.env.NEXT_PUBLIC_SUPABASE_URL+"/functions/v1/market-data-sync",{method:"POST",headers:{Authorization:"Bearer "+session.access_token}});
   const j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo actualizar BCR/CAC.");
   setSyncMsg("Precios BCR/CAC actualizados. El histórico fue conservado.");await load();
  }catch(e){setError(e instanceof Error?e.message:"Error de actualización.")}finally{setSyncing(false)}
 }
 const latest=useMemo(()=>{const m=new Map<string,Quote>();for(const q of quotes){const code=commodities[q.commodity_id||""]||q.commodity_id||"OTRO";if(!m.has(code))m.set(code,q)}return m},[quotes,commodities]);
 const cards=["SOJA","MAIZ","TRIGO","GIRASOL"].map(code=>({code,q:latest.get(code)}));
 const tabCodes:Record<string,string[]>={Granos:["SOJA","MAIZ","TRIGO","GIRASOL","SORGO"],Aceites:["ACEITE_SOJA"],Harinas:["HARINA_SOJA"],Subproductos:["PELLETS_SOJA","SORGO"],Futuros:[],FOB:[],FAS:[],CIF:[], "Mercados internacionales":[]};
 const tabRows=(tabCodes[marketTab]||[]).map(code=>({code,q:latest.get(code)}));
 const tabQuotes=quotes.filter(q=>{const p=String(q.price_type||"").toUpperCase();if(marketTab==="Futuros")return p.includes("FUT");if(["FOB","FAS","CIF"].includes(marketTab))return p.includes(marketTab);if(marketTab==="Mercados internacionales")return ["CHICAGO","EURONEXT","BRASIL","PARIS"].includes(String(q.market||"").toUpperCase());return tabCodes[marketTab]?.includes((commodities[q.commodity_id||""]||q.commodity_id||"").toUpperCase())||false;}).slice(0,20);
 const soja=quotes.filter(q=>(commodities[q.commodity_id||""]||"").toUpperCase()==="SOJA").slice(0,30).reverse();
 const international=quotes.filter(q=>["CHICAGO","EURONEXT","BRASIL","PARIS"].includes((q.market||"").toUpperCase())).slice(0,6);
 const futures=quotes.filter(q=>String(q.price_type).toUpperCase().includes("FUT")).slice(0,8);
 return <main className="market-reference">
  <header className="market-reference-head"><div><h1>Mercado</h1><p>Precios en tiempo real y análisis de los principales granos y commodities agrícolas</p></div><div className="market-head-actions"><span className="market-open"><i/> Mercado abierto</span><span>◷ {new Date().toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})} (GMT-3)</span><small>Bolsa de Comercio de Rosario</small><a className="market-source-link" href="https://www.bcr.com.ar/es/mercados/mercado-de-granos/cotizaciones/cotizaciones-locales-1" target="_blank" rel="noreferrer">Fuente oficial ↗</a><button onClick={sync} disabled={syncing}>⟳ &nbsp;{syncing?"Actualizando…":"Actualizar precios"}</button></div></header>
  {error&&<div className="module-alert module-alert-error">{error}</div>}{syncMsg&&<div className="module-alert">{syncMsg}</div>}
  <nav className="market-tabs">{["Granos","Aceites","Harinas","Subproductos","Futuros","FOB","FAS","CIF","Mercados internacionales"].map(x=><button key={x} className={marketTab===x?"active":""} onClick={()=>setMarketTab(x)}>{x}</button>)}</nav>
  <section className="market-top-grid"><div className="market-quote-cards">{(marketTab==="Granos"?cards:tabRows.length?tabRows:cards.filter(x=>tabCodes[marketTab]?.includes(x.code))).map(({code,q})=><article className="market-quote-card" key={code}><b>{icon(code)}</b><div><strong>{names.get(code)}</strong><small>{code==="GIRASOL"?"Rosario":"MATba · Rosario"}</small><em>{fmt(q)}</em><span className={(q?.variation||0)>=0?"positive":"negative"}>{q?.variation==null?"Sin variación":`${q.variation>=0?"+":""}${Number(q.variation).toFixed(2)}%`} ↗</span></div><div className="market-spark"/></article>)}</div><section className="market-side-card"><div className="market-section-title"><strong>Mercados internacionales</strong><Link href="/mercado">Ver todos →</Link></div><div className="market-pills">{["Chicago","Euronext","Brasil","París"].map((x,i)=><span className={i===0?"active":""} key={x}>{x}</span>)}</div><div className="market-mini-head"><span>PRODUCTO</span><span>ÚLTIMO</span><span>VAR.</span></div>{international.length?international.map(q=><div className="market-mini-row" key={q.id}><span>{names.get(commodities[q.commodity_id||""]||"")||commodities[q.commodity_id||""]||"Commodity"}</span><b>{fmt(q)}</b><em>{q.variation==null?"—":`${q.variation>=0?"+":""}${q.variation.toFixed(2)}%`}</em></div>):<div className="market-empty-small">Sin referencias internacionales sincronizadas.</div>}</section></section>

  <section className="market-main-grid"><section className="market-chart-card"><div className="market-section-title"><strong>🫘 &nbsp;Evolución de precios - Soja</strong><div className="chart-ranges">{["1D","1S","1M","3M","1A","Todo"].map(x=><button className={range===x?"active":""} onClick={()=>setRange(x)} key={x}>{x}</button>)}</div></div><div className="market-chart">{soja.length?<svg viewBox="0 0 900 300" preserveAspectRatio="none" aria-label="Evolución de Soja"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#28b879" stopOpacity=".35"/><stop offset="100%" stopColor="#28b879" stopOpacity=".02"/></linearGradient></defs><polyline fill="url(#area)" stroke="none" points={`0,290 ${soja.map((q,i)=>{const max=Math.max(...soja.map(x=>x.price||0)),min=Math.min(...soja.map(x=>x.price||0));const x=20+i*860/Math.max(1,soja.length-1),y=270-((q.price||0)-min)/Math.max(1,max-min)*220;return x+","+y}).join(" ")} 900,290`}/><polyline fill="none" stroke="#16a96d" strokeWidth="3" points={soja.map((q,i)=>{const max=Math.max(...soja.map(x=>x.price||0)),min=Math.min(...soja.map(x=>x.price||0));const x=20+i*860/Math.max(1,soja.length-1),y=270-((q.price||0)-min)/Math.max(1,max-min)*220;return x+","+y}).join(" ")}/></svg>:<div className="market-chart-empty"><strong>Sin datos de evolución de Soja</strong><span>Actualizá BCR/CAC para cargar cotizaciones verificadas.</span></div>}</div><div className="chart-axis"><span>09:00</span><span>10:00</span><span>11:00</span><span>12:00</span><span>13:00</span><span>14:00</span><span>15:00</span><span>16:00</span></div></section>
   <section className="market-side-card main-quotes"><div className="market-section-title"><strong>Cotizaciones principales</strong></div><div className="market-mini-head"><span>PRODUCTO</span><span>ÚLTIMO</span><span>VARIACIÓN</span></div>{cards.concat(["ACEITE_SOJA","HARINA_SOJA","SORGO"].map(code=>({code,q:latest.get(code)}))).map(({code,q})=><div className="market-mini-row" key={code}><span>{names.get(code)||code}</span><b>{fmt(q)}</b><em className={(q?.variation||0)>=0?"positive":"negative"}>{q?.variation==null?"—":`${q.variation>=0?"+":""}${q.variation.toFixed(2)}%`}</em></div>)}</section>
  </section>

  <section className="market-lower-grid"><MarketTable title="Últimas ofertas en el mercado" items={offers} type="offer"/><MarketTable title="Últimas demandas en el mercado" items={demands} type="demand"/><section className="market-side-stack"><section className="market-side-card"><div className="market-section-title"><strong>Futuros - MATba</strong><Link href="/mercado">Ver todos →</Link></div>{futures.length?<div className="market-futures"><div>MES <b>SOJA</b><b>MAÍZ</b><b>TRIGO</b></div>{futures.slice(0,5).map(q=><div key={q.id}><span>{q.position||q.market_date}</span><b>{fmt(q)}</b><b>{fmt(q)}</b><b>{fmt(q)}</b></div>)}</div>:<div className="market-empty-small">Sin futuros sincronizados.</div>}</section><section className="market-side-card"><div className="market-section-title"><strong>FOB / FAS / CIF</strong><Link href="/mercado">Ver todos →</Link></div><div className="market-pills"><span className="active">FOB</span><span>FAS</span><span>CIF</span></div>{quotes.filter(q=>q.price_type!=="PIZARRA_CAC").slice(0,4).length?quotes.filter(q=>q.price_type!=="PIZARRA_CAC").slice(0,4).map(q=><div className="market-mini-row" key={q.id}><span>{names.get(commodities[q.commodity_id||""]||"")||"Commodity"}</span><b>{q.port||"—"}</b><em>{fmt(q)}</em></div>):<div className="market-empty-small">Sin referencias FOB/FAS/CIF sincronizadas.</div>}</section></section></section>

  <section className="market-feature-strip"><div><b>📈</b><span><strong>Precios en tiempo real</strong><small>Bolsa de Comercio de Rosario</small></span></div><div><b>🌐</b><span><strong>Mercados globales</strong><small>Chicago, Euronext, Brasil y más</small></span></div><div><b>▤</b><span><strong>Análisis y tendencias</strong><small>Información para mejores decisiones</small></span></div><div><b>🔔</b><span><strong>Alertas de precios</strong><small>Notificaciones personalizadas</small></span></div></section>
 </main>
}

function MarketTable({title,items,type}:{title:string;items:Pub[];type:"offer"|"demand"}){
 return <section className="market-table-card"><div className="market-section-title"><strong>{title}</strong><Link href={type==="offer"?"/marketplace":"/marketplace?tipo=DEMANDA"}>Ver todas →</Link></div><div className="market-mini-head"><span>PRODUCTO</span><span>VOLUMEN</span><span>{type==="offer"?"ORIGEN":"DESTINO"}</span><span>PRECIO</span><span>PUBLICADO</span><span/></div>{items.map(p=><div className="market-offer-row" key={p.id}><span>🫘 {productName(p)}</span><span>{Number(p.cantidad_tn).toLocaleString("es-AR")} TN</span><span>{p.localidad||p.provincia||"Global"}</span><b>{p.precio_tn? `USD ${Number(p.precio_tn).toLocaleString("es-AR")}/tn`:"—"}</b><span>{p.creada_en?new Date(p.creada_en).toLocaleDateString("es-AR"):"—"}</span><Link href={`/marketplace?publicacion=${p.id}`}>Ver</Link></div>)}{!items.length&&<div className="market-empty-small">No hay publicaciones activas.</div>}</section>
}