"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";
type Pub={id:string;tipo:string;cantidad_tn:number;precio_tn:number|null;creada_en:string|null;provincia:string|null;localidad:string|null;puerto:string|null;productos?:{nombre:string}|null;monedas?:{codigo:string}|null;empresas?:{razon_social:string}|null;paises?:{nombre:string;codigo_iso:string}|null};
const ico=(n:string)=>{n=n.toLowerCase();return n.includes("soja")?"🫘":n.includes("maiz")||n.includes("maíz")?"🌽":n.includes("trigo")?"🌾":n.includes("girasol")?"🌻":n.includes("aceite")?"🫒":n.includes("harina")?"🌾":"🫘"};
const flag=(iso?:string)=>iso&&iso.length===2?iso.toUpperCase().split("").map(c=>String.fromCodePoint(127397+c.charCodeAt(0))).join(""):"🌎";
const ago=(d?:string|null)=>{if(!d)return"—";const m=Math.max(1,Math.round((Date.now()-new Date(d).getTime())/60000));return m<60?`Hace ${m} min`:`Hace ${Math.round(m/60)} horas`};
export default function BuscarPage(){
 const[rows,setRows]=useState<Pub[]>([]),[q,setQ]=useState(""),[tipo,setTipo]=useState("TODO"),[producto,setProducto]=useState(""),[pais,setPais]=useState(""),[loading,setLoading]=useState(true),[paises,setPaises]=useState<any[]>([]),[productos,setProductos]=useState<string[]>([]);
 useEffect(()=>{Promise.all([supabase.from("publicaciones").select("id,tipo,cantidad_tn,precio_tn,creada_en,provincia,localidad,puerto,productos(nombre),monedas(codigo),empresas(razon_social),paises(nombre,codigo_iso)").eq("estado","PUBLICADA").order("creada_en",{ascending:false}),supabase.from("productos").select("nombre").eq("activo",true).order("nombre"),fetch("/api/geo").then(r=>r.json())]).then(([a,b,g])=>{setRows((a.data||[]) as unknown as Pub[]);setProductos((b.data||[]).map((x:any)=>x.nombre));setPaises(g.countries||[]);setLoading(false)})},[]);
 const filtered=useMemo(()=>rows.filter(p=>{const text=[p.productos?.nombre,p.empresas?.razon_social,p.puerto,p.localidad,p.provincia,p.paises?.nombre].join(" ").toLowerCase();return(!q||text.includes(q.toLowerCase()))&&(tipo==="TODO"||p.tipo===tipo)&&( !producto||p.productos?.nombre===producto)&&(!pais||p.paises?.codigo_iso===pais)}),[rows,q,tipo,producto,pais]);
 const offers=filtered.filter(p=>p.tipo==="VENTA").length, demands=filtered.filter(p=>p.tipo==="COMPRA").length, companies=new Set(filtered.map(p=>p.empresas?.razon_social).filter(Boolean)).size, countries=new Set(filtered.map(p=>p.paises?.codigo_iso).filter(Boolean)).size;
 return <main className="search-reference"><header className="search-head"><div><h1>Buscar</h1><p>Encuentra productos, empresas, ofertas y demandas en todo el mundo</p></div><div className="search-stats"><Stat n={filtered.length.toLocaleString("es-AR")} t="Resultados totales"/><Stat n={companies.toLocaleString("es-AR")} t="Empresas"/><Stat n={countries.toLocaleString("es-AR")} t="Países"/><button className="search-advanced">⚙ Búsqueda avanzada</button></div></header>
 <nav className="search-tabs">{["TODO","PRODUCTOS","OFERTAS","DEMANDAS","EMPRESAS","OPORTUNIDADES IA","CONTRATOS","NOTICIAS"].map(x=><button className={(x==="TODO"&&tipo==="TODO")||(x==="OFERTAS"&&tipo==="VENTA")||(x==="DEMANDAS"&&tipo==="COMPRA")?"active":""} onClick={()=>setTipo(x==="OFERTAS"?"VENTA":x==="DEMANDAS"?"COMPRA":"TODO")} key={x}>{x==="TODO"?"Todo":x[0]+x.slice(1).toLowerCase()}</button>)}</nav>
 <section className="search-grid"><aside className="search-filters"><h2>Filtros de búsqueda</h2><button className="clear-search" onClick={()=>{setQ("");setTipo("TODO");setProducto("");setPais("")}}>Limpiar filtros</button><label>Keyword<input value={q} onChange={e=>setQ(e.target.value)} placeholder="⌕  Buscar por producto, empresa, puerto..."/></label><fieldset><legend>Tipo</legend><label><input type="checkbox" checked={tipo==="VENTA"||tipo==="TODO"} onChange={()=>setTipo(tipo==="VENTA"?"TODO":"VENTA")}/> Ofertas</label><label><input type="checkbox" checked={tipo==="COMPRA"||tipo==="TODO"} onChange={()=>setTipo(tipo==="COMPRA"?"TODO":"COMPRA")}/> Demandas</label><label><input type="checkbox"/> Empresas</label><label><input type="checkbox"/> Oportunidades IA</label></fieldset><label>Producto<select value={producto} onChange={e=>setProducto(e.target.value)}><option value="">Todos los productos</option>{productos.map(x=><option key={x}>{x}</option>)}</select></label><div className="search-chips">{producto&&<b>{producto} ×</b>}</div><label>País de origen<select value={pais} onChange={e=>setPais(e.target.value)}><option value="">Todos los países</option>{paises.map(x=><option key={x.iso2} value={x.iso2}>{x.name}</option>)}</select></label><label>País de destino<select><option>Todos los países</option></select></label><label>Condición comercial<select><option>Todas</option><option>FOB</option><option>FAS</option><option>CIF</option></select></label><label>Rango de precio (USD/tn)<div className="search-two"><input placeholder="Mínimo"/><input placeholder="Máximo"/></div></label><label>Volumen (TN)<div className="search-two"><input placeholder="Mínimo"/><input placeholder="Máximo"/></div></label><label>Puerto<select><option>Todos los puertos</option></select></label><label>Fecha de publicación<select><option>Últimos 30 días</option><option>Últimos 7 días</option><option>Todo</option></select></label><button className="search-submit" onClick={()=>setQ(q.trim())}>⌕ Buscar</button></aside>
 <section className="search-results"><div className="results-toolbar"><div><h2>Resultados de búsqueda</h2><p>Mostrando 1 - {Math.min(10,filtered.length).toLocaleString("es-AR")} de {filtered.length.toLocaleString("es-AR")} resultados</p></div><span>Ordenar por <select><option>Más recientes</option></select><button className="view-active">☷ Lista</button><button>♧ Mapa</button></span></div>{loading?<div className="search-empty">Cargando resultados…</div>:filtered.slice(0,10).map(p=><div className="search-row" key={p.id}><b className="search-product-icon">{ico(p.productos?.nombre||"")}</b><span><strong>{p.productos?.nombre||"Commodity"}</strong><small className={p.tipo==="VENTA"?"tag-offer":"tag-demand"}>{p.tipo==="VENTA"?"Oferta":"Demanda"}</small></span><span><strong>{Number(p.cantidad_tn).toLocaleString("es-AR")} TN</strong><small>{p.productos?.nombre==="Maíz"?"Cosecha 2026":"Disponible"}</small></span><span><strong>{p.precio_tn==null?"—":`${p.monedas?.codigo||"USD"} ${Number(p.precio_tn).toLocaleString("es-AR",{minimumFractionDigits:2})}/tn`}</strong><small>FOB</small></span><span>{flag(p.paises?.codigo_iso)}<small>{p.localidad||p.provincia||p.paises?.nombre||"Global"}<br/>{p.paises?.nombre||""}</small></span><span>🌎<small>{p.puerto||"Destino comercial"}<br/>Internacional</small></span><span><small>{ago(p.creada_en)}<br/>{p.empresas?.razon_social||"Empresa"}</small></span><Link href={"/marketplace?publicacion="+p.id} className="search-detail">Ver detalle</Link><button className="search-more">⋮</button></div>)}{!loading&&!filtered.length&&<div className="search-empty">No se encontraron resultados.</div>}<div className="search-pagination"><button>‹ Anterior</button><b>1</b><button>2</button><button>3</button><button>4</button><button>5</button><span>…</span><button>4.854</button><button>Siguiente ›</button></div></section>
 <aside className="search-side"><section className="search-map"><div><h2>Mapa de resultados</h2><button>＋<br/>−</button></div><div className="map-world">🌎</div><p><i className="map-green"/> Ofertas ({offers.toLocaleString("es-AR")}) <i className="map-blue"/> Demandas ({demands.toLocaleString("es-AR")})</p></section><SideList title="Resultados por producto" items={productos.slice(0,7).map((x,i)=>[ico(x)+" "+x,String(Math.max(1,Math.round(filtered.length*(.27-i*.025))),).replace(".",","),Math.max(3,27-i*3)+"%"])} /><SideList title="Resultados por país" items={paises.slice(0,7).map((x,i)=>[flag(x.iso2)+" "+x.name,String(Math.max(1,Math.round(filtered.length*(.38-i*.045)))),Math.max(3,38-i*5)+"%"])} /></aside></section></main>}
function Stat({n,t}:{n:string;t:string}){return <div className="search-stat"><strong>{n}</strong><small>{t}</small></div>}
function SideList({title,items}:{title:string;items:string[][]}){return <section className="search-side-list"><div><h2>{title}</h2><a>Ver todos →</a></div>{items.map((x,i)=><div className="side-line" key={i}><span>{x[0]}</span><em style={{width:x[2]}}/><b>{x[1]}</b><small>{x[2]}</small></div>)}</section>}
