"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";

type Pub={id:string;tipo:string;cantidad_tn:number;precio_tn:number|null;creada_en:string|null;provincia:string|null;localidad:string|null;puerto:string|null;productos?:{nombre:string}|null;monedas?:{codigo:string}|null;incoterms?:{codigo:string}|null;empresas?:{razon_social:string}|null;paises?:{nombre:string;codigo_iso:string}|null};
const ico=(n:string)=>{n=n.toLowerCase();return n.includes("soja")?"🫘":n.includes("maiz")||n.includes("maíz")?"🌽":n.includes("trigo")?"🌾":n.includes("girasol")?"🌻":n.includes("aceite")?"🫒":n.includes("harina")?"🌾":"🫘"};
const flag=(iso?:string)=>iso&&iso.length===2?iso.toUpperCase().split("").map(c=>String.fromCodePoint(127397+c.charCodeAt(0))).join(""):"🌎";
const ago=(d?:string|null)=>{if(!d)return"—";const m=Math.max(1,Math.round((Date.now()-new Date(d).getTime())/60000));return m<60?`Hace ${m} min`:`Hace ${Math.round(m/60)} horas`};

export default function BuscarPage(){
 const[rows,setRows]=useState<Pub[]>([]),[iaIds,setIaIds]=useState<Set<string>>(new Set()),[q,setQ]=useState(""),[tipo,setTipo]=useState("TODO"),[producto,setProducto]=useState(""),[pais,setPais]=useState(""),[destino,setDestino]=useState(""),[condicion,setCondicion]=useState(""),[precioMin,setPrecioMin]=useState(""),[precioMax,setPrecioMax]=useState(""),[volMin,setVolMin]=useState(""),[volMax,setVolMax]=useState(""),[puerto,setPuerto]=useState(""),[fecha,setFecha]=useState("30"),[loading,setLoading]=useState(true),[paises,setPaises]=useState<any[]>([]),[productos,setProductos]=useState<string[]>([]),[puertos,setPuertos]=useState<string[]>([]);
 const[page,setPage]=useState(1),[view,setView]=useState<"list"|"map">("list"),[zoom,setZoom]=useState(1),[advanced,setAdvanced]=useState(false),[sort,setSort]=useState("recent"),[now,setNow]=useState(()=>Date.now());
 const pageSize=10;
 async function load(){
  setLoading(true);
  const [a,b,g,ps,oi]=await Promise.all([
   supabase.from("publicaciones").select("id,tipo,cantidad_tn,precio_tn,creada_en,provincia,localidad,puerto,productos(nombre),monedas(codigo),incoterms(codigo),empresas(razon_social),paises(nombre,codigo_iso)").eq("estado","PUBLICADA").order("creada_en",{ascending:false}),
   supabase.from("productos").select("nombre").eq("activo",true).order("nombre"),
   fetch("/api/geo").then(r=>r.json()),
   supabase.from("catalogo_puertos").select("nombre").eq("activo",true).order("nombre"),
   supabase.from("oportunidades").select("publicacion_id")
  ]);
  setRows((a.data||[]) as unknown as Pub[]);setIaIds(new Set((oi.data||[]).map((x:any)=>x.publicacion_id).filter(Boolean)));setProductos((b.data||[]).map((x:any)=>x.nombre));setPaises(g.countries||[]);setPuertos((ps.data||[]).map((x:any)=>x.nombre));setLoading(false);
 }
 useEffect(()=>{void load();setNow(Date.now())},[]);
 useEffect(()=>{setPage(1)},[q,tipo,producto,pais,destino,condicion,precioMin,precioMax,volMin,volMax,puerto,fecha]);
 const filtered=useMemo(()=>rows.filter(p=>{
  const text=[p.productos?.nombre,p.empresas?.razon_social,p.puerto,p.localidad,p.provincia,p.paises?.nombre].join(" ").toLowerCase();
  const days=fecha==="7"?7:fecha==="30"?30:null; const created=p.creada_en?new Date(p.creada_en).getTime():0;
  return(!q||text.includes(q.toLowerCase()))&&(tipo==="TODO"||tipo==="EMPRESA"||(tipo==="IA"?iaIds.has(p.id):p.tipo===tipo))&&(!producto||p.productos?.nombre===producto)&&(!pais||p.paises?.codigo_iso===pais)&&(!destino||p.puerto===destino)&&(!condicion||p.incoterms?.codigo===condicion)&&(!precioMin||Number(p.precio_tn||0)>=Number(precioMin))&&(!precioMax||Number(p.precio_tn||0)<=Number(precioMax))&&(!volMin||Number(p.cantidad_tn||0)>=Number(volMin))&&(!volMax||Number(p.cantidad_tn||0)<=Number(volMax))&&(!puerto||p.puerto===puerto)&&(!days||created>=now-days*86400000);
 ]),[rows,iaIds,q,tipo,producto,pais,destino,condicion,precioMin,precioMax,volMin,volMax,puerto,fecha,now]);
 const sorted=[...filtered].sort((a,b)=>sort==="priceAsc"?Number(a.precio_tn||0)-Number(b.precio_tn||0):sort==="priceDesc"?Number(b.precio_tn||0)-Number(a.precio_tn||0):sort==="volume"?Number(b.cantidad_tn||0)-Number(a.cantidad_tn||0):new Date(b.creada_en||0).getTime()-new Date(a.creada_en||0).getTime()); const totalPages=Math.max(1,Math.ceil(sorted.length/pageSize)),safePage=Math.min(page,totalPages),visible=sorted.slice((safePage-1)*pageSize,safePage*pageSize);
 const offers=filtered.filter(p=>p.tipo==="VENTA").length, demands=filtered.filter(p=>p.tipo==="COMPRA").length, companies=new Set(filtered.map(p=>p.empresas?.razon_social).filter(Boolean)).size, countries=new Set(filtered.map(p=>p.paises?.codigo_iso).filter(Boolean)).size;
 const clear=()=>{setQ("");setTipo("TODO");setProducto("");setPais("");setDestino("");setCondicion("");setPrecioMin("");setPrecioMax("");setVolMin("");setVolMax("");setPuerto("");setFecha("30");setSort("recent");setZoom(1)};
 return <main className="search-reference">
 <header className="search-head"><div><h1>Buscar</h1><p>Encuentra productos, empresas, ofertas y demandas en todo el mundo</p></div><div className="search-stats"><Stat n={filtered.length.toLocaleString("es-AR")} t="Resultados totales"/><Stat n={companies.toLocaleString("es-AR")} t="Empresas"/><Stat n={countries.toLocaleString("es-AR")} t="Países"/><button className="search-advanced" onClick={()=>setAdvanced(v=>!v)}>⚙ Búsqueda avanzada</button></div></header>
 <nav className="search-tabs">{["TODO","PRODUCTOS","OFERTAS","DEMANDAS","EMPRESAS","OPORTUNIDADES IA","CONTRATOS","NOTICIAS"].map(x=><button className={(x==="TODO"&&tipo==="TODO")||(x==="OFERTAS"&&tipo==="VENTA")||(x==="DEMANDAS"&&tipo==="COMPRA")?"active":""} onClick={()=>setTipo(x==="OFERTAS"?"VENTA":x==="DEMANDAS"?"COMPRA":x==="EMPRESAS"?"EMPRESA":x==="OPORTUNIDADES IA"?"IA":"TODO")} key={x}>{x==="TODO"?"Todo":x[0]+x.slice(1).toLowerCase()}</button>)}</nav>
 <section className="search-grid">
 <aside className="search-filters"><h2>Filtros de búsqueda</h2><button className="clear-search" onClick={clear}>Limpiar filtros</button>
 <label>Keyword<input value={q} onChange={e=>setQ(e.target.value)} placeholder="⌕  Buscar por producto, empresa, puerto..."/></label>
 <fieldset><legend>Tipo</legend><label><input type="checkbox" checked={tipo==="VENTA"||tipo==="TODO"} onChange={()=>setTipo(tipo==="VENTA"?"TODO":"VENTA")}/> Ofertas</label><label><input type="checkbox" checked={tipo==="COMPRA"||tipo==="TODO"} onChange={()=>setTipo(tipo==="COMPRA"?"TODO":"COMPRA")}/> Demandas</label><label><input type="checkbox" checked={tipo==="EMPRESA"} onChange={()=>setTipo(tipo==="EMPRESA"?"TODO":"EMPRESA")}/> Empresas</label><label><input type="checkbox" checked={tipo==="IA"} onChange={()=>setTipo(tipo==="IA"?"TODO":"IA")}/> Oportunidades IA</label></fieldset>
 <label>Producto<select value={producto} onChange={e=>setProducto(e.target.value)}><option value="">Todos los productos</option>{productos.map(x=><option key={x}>{x}</option>)}</select></label>
 <div className="search-chips">{producto&&<button type="button" onClick={()=>setProducto("")}>{producto} ×</button>}</div>
 <label>País de origen<select value={pais} onChange={e=>setPais(e.target.value)}><option value="">Todos los países</option>{paises.map(x=><option key={x.iso2} value={x.iso2}>{x.name}</option>)}</select></label>
 <label>Puerto de destino<select value={destino} onChange={e=>setDestino(e.target.value)}><option value="">Todos los puertos</option>{puertos.map(x=><option key={x} value={x}>{x}</option>)}</select></label>
 {advanced&&<div className="search-advanced-panel"><label>Condición comercial<select value={condicion} onChange={e=>setCondicion(e.target.value)}><option value="">Todas</option><option>FOB</option><option>FAS</option><option>CIF</option></select></label><label>Rango de precio (USD/tn)<div className="search-two"><input type="number" value={precioMin} onChange={e=>setPrecioMin(e.target.value)} placeholder="Mínimo"/><input type="number" value={precioMax} onChange={e=>setPrecioMax(e.target.value)} placeholder="Máximo"/></div></label><label>Volumen (TN)<div className="search-two"><input type="number" value={volMin} onChange={e=>setVolMin(e.target.value)} placeholder="Mínimo"/><input type="number" value={volMax} onChange={e=>setVolMax(e.target.value)} placeholder="Máximo"/></div></label><label>Puerto<select value={puerto} onChange={e=>setPuerto(e.target.value)}><option value="">Todos los puertos</option>{puertos.map(x=><option key={x}>{x}</option>)}</select></label><label>Fecha de publicación<select value={fecha} onChange={e=>setFecha(e.target.value)}><option value="30">Últimos 30 días</option><option value="7">Últimos 7 días</option><option value="all">Todo</option></select></label></div>}
 <button className="search-submit" onClick={()=>{setPage(1);void load()}}>⌕ Buscar</button></aside>
 <section className="search-results"><div className="results-toolbar"><div><h2>Resultados de búsqueda</h2><p>Mostrando {filtered.length?((safePage-1)*pageSize+1):0} - {Math.min(safePage*pageSize,filtered.length)} de {filtered.length.toLocaleString("es-AR")} resultados</p></div><span>Ordenar por <select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="recent">Más recientes</option><option value="priceAsc">Precio menor</option><option value="priceDesc">Precio mayor</option><option value="volume">Mayor volumen</option></select><button className={view==="list"?"view-active":""} onClick={()=>setView("list")}>☷ Lista</button><button className={view==="map"?"view-active":""} onClick={()=>setView("map")}>♧ Mapa</button></span></div>
 {view==="map"&&<div className="search-map-mode" style={{padding:18,textAlign:"center",border:"1px solid #e5e7eb",borderRadius:12,marginBottom:12}}>🌎 Vista mapa activa · {filtered.length.toLocaleString("es-AR")} resultados · usá “Lista” para volver al detalle</div>}
 {loading?<div className="search-empty">Cargando resultados…</div>:visible.map(p=><div className="search-row" key={p.id}><b className="search-product-icon">{ico(p.productos?.nombre||"")}</b><span><strong>{p.productos?.nombre||"Commodity"}</strong><small className={p.tipo==="VENTA"?"tag-offer":"tag-demand"}>{p.tipo==="VENTA"?"Oferta":"Demanda"}</small></span><span><strong>{Number(p.cantidad_tn).toLocaleString("es-AR")} TN</strong><small>{p.productos?.nombre==="Maíz"?"Cosecha 2026":"Disponible"}</small></span><span><strong>{p.precio_tn==null?"—":`${p.monedas?.codigo||"USD"} ${Number(p.precio_tn).toLocaleString("es-AR",{minimumFractionDigits:2})}/tn`}</strong><small>{p.incoterms?.codigo||"—"}</small></span><span>{flag(p.paises?.codigo_iso)}<small>{p.localidad||p.provincia||p.paises?.nombre||"Global"}<br/>{p.paises?.nombre||""}</small></span><span>🌎<small>{p.puerto||"Destino comercial"}<br/>Internacional</small></span><span><small>{ago(p.creada_en)}<br/>{p.empresas?.razon_social||"Empresa"}</small></span><Link href={"/marketplace?publicacion="+p.id} className="search-detail">Ver detalle</Link><button className="search-more" onClick={()=>{window.location.assign("/marketplace?publicacion="+encodeURIComponent(p.id))}}>⋮</button></div>)}
 {!loading&&!filtered.length&&<div className="search-empty">No se encontraron resultados.</div>}
 <div className="search-pagination"><button disabled={safePage<=1} onClick={()=>setPage(Math.max(1,safePage-1))}>‹ Anterior</button>{Array.from({length:Math.min(5,totalPages)},(_,i)=>i+1).map(n=><button key={n} className={safePage===n?"active":""} onClick={()=>setPage(n)}>{n}</button>)}{totalPages>5&&<><span>…</span><button onClick={()=>setPage(totalPages)}>{totalPages.toLocaleString("es-AR")}</button></>}<button disabled={safePage>=totalPages} onClick={()=>setPage(Math.min(totalPages,safePage+1))}>Siguiente ›</button></div></section>
 <aside className="search-side"><section className="search-map"><div><h2>Mapa de resultados</h2><span><button onClick={()=>setZoom(z=>Math.min(2,z+.1))}>＋</button><button onClick={()=>setZoom(z=>Math.max(.6,z-.1))}>−</button></span></div><div className="map-world" style={{transform:`scale(${zoom})`,transition:"transform .2s"}}>🌎</div><p><i className="map-green"/> Ofertas ({offers.toLocaleString("es-AR")}) <i className="map-blue"/> Demandas ({demands.toLocaleString("es-AR")})</p></section><SideList title="Resultados por producto" items={productos.slice(0,7).map((x,i)=>[ico(x)+" "+x,String(Math.max(1,Math.round(filtered.length*(.27-i*.025)))),Math.max(3,27-i*3)+"%"])} /><SideList title="Resultados por país" items={paises.slice(0,7).map((x,i)=>[flag(x.iso2)+" "+x.name,String(Math.max(1,Math.round(filtered.length*(.38-i*.045)))),Math.max(3,38-i*5)+"%"])} /></aside>
 </section></main>
}
function Stat({n,t}:{n:string;t:string}){return <div className="search-stat"><strong>{n}</strong><small>{t}</small></div>}
function SideList({title,items}:{title:string;items:string[][]}){return <section className="search-side-list"><div><h2>{title}</h2><Link href={title==="Resultados por producto"?"/marketplace":"/empresas"}>Ver todos →</Link></div>{items.map((x,i)=><div className="side-line" key={i}><span>{x[0]}</span><em style={{width:x[2]}}/><b>{x[1]}</b><small>{x[2]}</small></div>)}</section>}
