"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";
type Pub={id:string;tipo:string;cantidad_tn:number;precio_tn:number|null;estado:string;provincia:string|null;localidad:string|null;puerto:string|null;puertos?:string[]|null;creada_en:string|null;calidad?:string|null;productos?:{nombre:string}|null;monedas?:{codigo:string}|null;incoterms?:{codigo:string}|null;empresas?:{razon_social:string;verificada?:boolean|null}|null;paises?:{nombre:string;codigo_iso:string}|null;provincias?:{nombre:string;codigo:string}|null;localidades?:{nombre:string}|null};
const icon=(n:string)=>{n=n.toLowerCase();return n.includes("soja")?"🫘":n.includes("maiz")||n.includes("maíz")?"🌽":n.includes("trigo")?"🌾":n.includes("girasol")?"🌻":"🌾"};
const productoCoincide=(nombre:string|undefined,filtro:string)=>{if(!filtro)return true;const n=(nombre||"").toLowerCase();const f=filtro.toLowerCase();if(f==="aceites")return n.includes("aceite");if(f==="harinas")return n.includes("harina");if(f==="subproductos")return ["pellet","expeller","afrechillo","subproducto"].some(x=>n.includes(x));return n===f;};
const flag=(iso?:string)=>iso&&iso.length===2?iso.toUpperCase().split("").map(c=>String.fromCodePoint(127397+c.charCodeAt(0))).join(""):"🌎";
const ago=(d?:string|null)=>{if(!d)return"—";const m=Math.max(1,Math.round((Date.now()-new Date(d).getTime())/60000));return m<60?`Hace ${m} min`:`Hace ${Math.round(m/60)} horas`};
export default function MarketplacePage(){
 const[rows,setRows]=useState<Pub[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[producto,setProducto]=useState(""),[pais,setPais]=useState(""),[provincia,setProvincia]=useState(""),[ciudad,setCiudad]=useState(""),[condicion,setCondicion]=useState(""),[precioMin,setPrecioMin]=useState(""),[precioMax,setPrecioMax]=useState(""),[isDemand,setIsDemand]=useState(false),[paises,setPaises]=useState<any[]>([]),[provincias,setProvincias]=useState<any[]>([]),[ciudades,setCiudades]=useState<any[]>([]),[productos,setProductos]=useState<string[]>([]),[puertos,setPuertos]=useState<any[]>([]);
 async function load(){const[a,b,catalogo]=await Promise.all([supabase.from("publicaciones").select("id,tipo,cantidad_tn,precio_tn,estado,provincia,localidad,puerto,puertos,creada_en,productos(nombre),monedas(codigo),incoterms(codigo),paises(nombre,codigo_iso),provincias(nombre,codigo),localidades(nombre),empresas(razon_social,verificada)").eq("estado","PUBLICADA").order("creada_en",{ascending:false}),supabase.from("productos").select("nombre").eq("activo",true).order("nombre"),supabase.from("catalogo_puertos").select("codigo,nombre").eq("activo",true).order("nombre")]);if(a.error||b.error)setError(a.error?.message||b.error?.message||"No se pudieron cargar las ofertas.");setRows((a.data||[]) as unknown as Pub[]);setProductos((b.data||[]).map((x:any)=>x.nombre));setPuertos((catalogo.data||[]) as any[]);setLoading(false)}
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setIsDemand(q.get("tipo")==="DEMANDA");void load();fetch("/api/geo").then(r=>r.json()).then(d=>setPaises(d.countries||[]))},[]);
 useEffect(()=>{setProvincia("");setCiudad("");if(!pais){setProvincias([]);return}fetch("/api/geo?country="+pais).then(r=>r.json()).then(d=>setProvincias(d.states||[]))},[pais]);
 useEffect(()=>{setCiudad("");if(!pais||!provincia){setCiudades([]);return}fetch("/api/geo?country="+pais+"&state="+provincia).then(r=>r.json()).then(d=>setCiudades(d.cities||[]))},[pais,provincia]);
 const filtered=useMemo(()=>rows.filter(p=>{
  const price=Number(p.precio_tn);
  const min=precioMin.trim()===""?null:Number(precioMin);
  const max=precioMax.trim()===""?null:Number(precioMax);
  return p.tipo===(isDemand?"COMPRA":"VENTA")
    &&productoCoincide(p.productos?.nombre,producto)
    &&(!pais||p.paises?.codigo_iso===pais)
    &&(!provincia||p.provincias?.codigo===provincia||p.provincia===provincia)
    &&(!ciudad||p.localidades?.nombre===ciudad||p.localidad===ciudad)
    &&(!condicion||p.incoterms?.codigo===condicion)
    &&(min===null||(!Number.isNaN(min)&&price>=min))
    &&(max===null||(!Number.isNaN(max)&&price<=max));
}),[rows,producto,pais,provincia,ciudad,condicion,precioMin,precioMax,isDemand]);
 const companies=new Set(filtered.map(p=>p.empresas?.razon_social).filter(Boolean)).size,countries=new Set(filtered.map(p=>p.paises?.codigo_iso).filter(Boolean)).size,tons=filtered.reduce((a,p)=>a+Number(p.cantidad_tn||0),0);
 const puertoNombre=(value?:string|null)=>{if(!value)return"—";const p=puertos.find((x:any)=>x.codigo===value||x.nombre===value);return p?.nombre||value}; const puertosPublicacion=(p:Pub)=>{const values=Array.isArray(p.puertos)&&p.puertos.length?p.puertos:[p.puerto].filter(Boolean) as string[];return values.map(puertoNombre)}; const title=isDemand?"Demandas":"Ofertas", description=isDemand?"Encuentra compradores de granos y commodities agrícolas":"Encuentra las mejores ofertas de granos y commodities agrícolas";
 return <main className={"offers-reference "+(isDemand?"demand-reference":"")}><header className="offers-head"><div><h1>{title}</h1><p>{description}</p></div><Link href={"/nueva-publicacion?tipo="+(isDemand?"DEMANDA":"OFERTA")} className="offers-publish">{isDemand?"⌑ Publicar demanda":"⌑ Publicar oferta"} ＋</Link></header>
 <section className="offers-stats"><Stat i={isDemand?"🛒":"🏷️"} v={String(filtered.length)} t={isDemand?"Demandas activas":"Ofertas activas"} c="green"/><Stat i="▤" v={String(companies)} t={isDemand?"Empresas compradoras":"Empresas oferentes"} c="blue"/><Stat i="🌐" v={String(countries)} t="Países" c="purple"/><Stat i="🤝" v={tons.toLocaleString("es-AR")} t={isDemand?"Volumen total demandado":"Volumen total"} c="orange" s=" tn"/></section>
 <section className="offers-layout"><div className="offers-main"><nav className="offers-tabs">{["Todas las "+(isDemand?"demandas":"ofertas"),"Soja","Maíz","Trigo","Girasol","Aceites","Harinas","Subproductos"].map((x,i)=><button key={x} className={(i===0&&!producto)||producto===x?"active":""} onClick={()=>setProducto(i?x:"")}>{x}</button>)}</nav>
 <div className="offers-table-card"><div className="offers-table-head"><span>PRODUCTO</span><span>VOLUMEN</span><span>{isDemand?"PRECIO OBJETIVO":"PRECIO"}</span><span>CONDICIÓN</span><span>{isDemand?"DESTINO":"ORIGEN"}</span><span>{isDemand?"ORIGEN PREFERIDO":"DESTINO"}</span><span>PUBLICADO</span><span>EMPRESA</span><span>ESTADO</span><span>ACCIONES</span></div>{loading?<div className="offers-empty">Cargando ofertas…</div>:error?<div className="offers-empty">{error}</div>:filtered.length?filtered.map(p=><div className="offer-row" key={p.id}><span className="offer-product"><b>{icon(p.productos?.nombre||"")}</b><strong>{p.productos?.nombre||"Commodity"}</strong><small>{p.calidad||"Disponible"}</small></span><span><strong>{Number(p.cantidad_tn).toLocaleString("es-AR")} TN</strong></span><span><strong>{p.precio_tn==null?"—":`${p.monedas?.codigo||"—"} ${Number(p.precio_tn).toLocaleString("es-AR")}/tn`}</strong><small>{isDemand?"Precio objetivo":p.incoterms?.codigo||"Condición no informada"}</small></span><span><em className="cond-fob">{p.incoterms?.codigo||"—"}</em></span><span className="offer-place">{flag(p.paises?.codigo_iso)} <b>{isDemand?(puertoNombre(p.puerto)||p.localidad||p.provincia||p.paises?.nombre||"Global"):(p.localidad||p.provincia||p.paises?.nombre||"Global")}</b><small>{isDemand?"Destino comercial":p.paises?.nombre||""}</small></span><span className="offer-place">{isDemand?"🌎":"🌎"} <b>{isDemand?(p.provincia||p.localidad||"Origen no informado"):(puertosPublicacion(p).slice(0,2).join(" · ")||"A coordinar")}</b><small>{isDemand?"Origen preferido":(puertosPublicacion(p).length>2?`+${puertosPublicacion(p).length-2} puertos`:"Destino comercial")}</small></span><span>{ago(p.creada_en)}</span><span className="offer-company"><b>{p.empresas?.razon_social||"Empresa"}</b>{p.empresas?.verificada&&<i>✓</i>}<small>{p.empresas?.verificada?"Verificada":"Pendiente"}</small></span><span><em className={"offer-active "+(isDemand?"demand-active":"")}>Activa</em></span><Link className="offer-detail" href={"/marketplace?publicacion="+p.id}>Ver detalle</Link></div>):<div className="offers-empty"><strong>No hay ofertas que coincidan.</strong></div>}</div></div>
 <aside className="offers-sidebar"><section className="offers-filter-card"><div className="offers-side-title"><h2>Filtrar {isDemand?"demandas":"ofertas"}</h2><button onClick={()=>{setProducto("");setPais("");setProvincia("");setCiudad("");setCondicion("");setPrecioMin("");setPrecioMax("");}}>Limpiar filtros</button></div><label>Producto<select value={producto} onChange={e=>setProducto(e.target.value)}><option value="">Todos los productos</option>{productos.map(x=><option key={x}>{x}</option>)}</select></label><label>País de {isDemand?"destino":"origen"}<select value={pais} onChange={e=>setPais(e.target.value)}><option value="">Todos los países</option>{paises.map(x=><option key={x.iso2} value={x.iso2}>{x.name}</option>)}</select></label><label>Provincia / estado<select value={provincia} onChange={e=>setProvincia(e.target.value)}><option value="">Todos</option>{provincias.map(x=><option key={x.iso2} value={x.iso2}>{x.name}</option>)}</select></label><label>Ciudad / localidad<select value={ciudad} onChange={e=>setCiudad(e.target.value)}><option value="">Todas</option>{ciudades.map(x=><option key={x.name}>{x.name}</option>)}</select></label><label>Condición comercial<select value={condicion} onChange={e=>setCondicion(e.target.value)}><option value="">Todas</option><option value="FOB">FOB</option><option value="FAS">FAS</option><option value="CIF">CIF</option></select></label><label>Rango de precio / TN<div className="offers-range"><input type="number" min="0" step="0.01" value={precioMin} onChange={e=>setPrecioMin(e.target.value)} placeholder="Mínimo"/><input type="number" min="0" step="0.01" value={precioMax} onChange={e=>setPrecioMax(e.target.value)} placeholder="Máximo"/></div></label><button type="button" className="offers-apply" onClick={()=>void load()}>⌕ Actualizar resultados</button></section><section className="offers-region-card"><h2>{isDemand?"Demanda por región de destino":"Ofertas por región de origen"}</h2>{[...new Set(filtered.map(p=>p.provincia||p.localidad||p.paises?.nombre||"Global"))].slice(0,6).map((x,i)=><div key={x}><span className="region-dot"/><b>{x}</b><strong>{filtered.length?Math.round(filtered.filter(p=>(p.provincia||p.localidad||p.paises?.nombre||"Global")===x).reduce((a,p)=>a+Number(p.cantidad_tn),0)/Math.max(1,tons)*100):0}%</strong></div>)}</section></aside></section>
 <section className="offers-feature-strip"><Feature i="🛡️" t={isDemand?"Compradores verificados":"Empresas verificadas"} d={isDemand?"Empresas internacionales con proceso de verificación y KYC.":"Todas las empresas pasan por un proceso de verificación y KYC."}/><Feature i="🤝" t="Negociación segura" d="Comunicación directa con empresas verificadas."/><Feature i="▤" t="Contratos multilingües" d="LOI, SCO y contratos en varios idiomas."/><Feature i="📊" t="Oportunidades con IA" d="La IA te recomienda las mejores oportunidades."/></section></main>}
function Stat({i,v,t,c,s=""}:{i:string;v:string;t:string;c:string;s?:string}){return <div className={"offers-stat "+c}><b>{i}</b><span><strong>{v}<small>{s}</small></strong><em>{t}</em><i>Mercado activo</i></span></div>}
function Feature({i,t,d}:{i:string;t:string;d:string}){return <div className="offers-feature"><b>{i}</b><span><strong>{t}</strong><small>{d}</small></span></div>}
