"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";
export default function FiscalConfigPage(){
 const[id,setId]=useState(""),[name,setName]=useState(""),[commercial,setCommercial]=useState(""),[cuit,setCuit]=useState(""),[iva,setIva]=useState(""),[country,setCountry]=useState("Argentina"),[province,setProvince]=useState(""),[city,setCity]=useState(""),[address,setAddress]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesión no disponible.");const{data:p}=await supabase.from("profiles").select("active_company_id").eq("id",user.id).single();if(!p?.active_company_id)throw new Error("No hay empresa activa.");setId(p.active_company_id);const{data:c,error:e}=await supabase.from("companies").select("razon_social,nombre_comercial,cuit,condicion_iva,pais,provincia,localidad,direccion").eq("id",p.active_company_id).single();if(e)throw e;setName(c?.razon_social||"");setCommercial(c?.nombre_comercial||"");setCuit(c?.cuit||"");setIva(c?.condicion_iva||"");setCountry(c?.pais||"Argentina");setProvince(c?.provincia||"");setCity(c?.localidad||"");setAddress(c?.direccion||"");}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar la configuración fiscal.");}finally{setLoading(false)}})()},[]);
 async function save(){setSaving(true);setError("");setMsg("");try{const{error:e}=await supabase.from("companies").update({razon_social:name.trim(),nombre_comercial:commercial.trim()||null,cuit:cuit.trim(),condicion_iva:iva||null,pais:country.trim()||"Argentina",provincia:province.trim()||null,localidad:city.trim()||null,direccion:address.trim()||null}).eq("id",id);if(e)throw e;setMsg("Datos fiscales guardados correctamente.");}catch(e){setError(e instanceof Error?e.message:"No se pudieron guardar los datos fiscales.");}finally{setSaving(false)}}
 return <main className="module-page"><div className="module-hero"><div><span className="eyebrow">EMPRESA</span><h1>Configuración fiscal</h1><p>Datos que utiliza la plataforma para facturación y comprobantes oficiales.</p></div><Link className="module-pill" href="/facturas">← Volver a Facturación</Link></div>{error&&<div className="module-alert module-alert-error">{error}</div>}{msg&&<div className="module-alert">{msg}</div>}<section className="company-card"><div className="settings-form-grid"><label>Razón social<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Nombre comercial<input value={commercial} onChange={e=>setCommercial(e.target.value)}/></label><label>CUIT<input value={cuit} onChange={e=>setCuit(e.target.value)}/></label><label>Condición frente al IVA<select value={iva} onChange={e=>setIva(e.target.value)}><option value="">Seleccionar</option><option>Responsable Inscripto</option><option>Monotributista</option><option>Exento</option><option>Consumidor Final</option></select></label><label>País<input value={country} onChange={e=>setCountry(e.target.value)}/></label><label>Provincia / estado<input value={province} onChange={e=>setProvince(e.target.value)}/></label><label>Ciudad / localidad<input value={city} onChange={e=>setCity(e.target.value)}/></label><label>Dirección<input value={address} onChange={e=>setAddress(e.target.value)}/></label></div><button className="module-pill" onClick={save} disabled={saving}>{saving?"Guardando…":"Guardar datos fiscales"}</button><div className="settings-actions"><Link className="module-pill" href="/configuracion/arca">Configurar ARCA →</Link></div></section></main>;
}