"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase/client";

type Viaje={id:string;operacion_id:string;vehiculo_id:string|null;origen:string|null;destino:string|null;fecha_salida:string|null;fecha_llegada:string|null;estado:string|null};
type Operacion={id:string;codigo:string|null;cantidad_tn:number|null;estado:string|null};
type Entrega={viaje_id:string;toneladas_entregadas:number|null;fecha_entrega:string|null;recibido_por:string|null};
type Logistica={operacion_id:string;estado:string|null;carta_porte_numero:string|null;carta_porte_estado:string|null;transportista:string|null;transportista_cuit:string|null;chofer_nombre:string|null;patente_camion:string|null;patente_acoplado:string|null;fecha_carga:string|null;fecha_estimada_entrega:string|null;destino:string|null;kilos_entregados:number|null};

const date=(v:string|null|undefined)=>v?new Date(v).toLocaleDateString("es-AR"):"—";
const tn=(v:number|null)=>v==null?"—":Number(v).toLocaleString("es-AR",{maximumFractionDigits:0})+" TN";
const norm=(v:string|null|undefined)=>String(v||"").toUpperCase().replaceAll(" ","_");
const flag=(v:string|null|undefined)=>{const s=String(v||"").toLowerCase();if(s.includes("china")||s.includes("shanghai"))return "🇨🇳";if(s.includes("italia")||s.includes("génova")||s.includes("genova"))return "🇮🇹";if(s.includes("paises bajos")||s.includes("países bajos")||s.includes("rotterdam"))return "🇳🇱";if(s.includes("alemania")||s.includes("hamburgo"))return "🇩🇪";if(s.includes("brasil")||s.includes("santos"))return "🇧🇷";if(s.includes("uruguay")||s.includes("montevideo"))return "🇺🇾";if(s.includes("chile")||s.includes("valparaiso"))return "🇨🇱";if(s.includes("filipinas")||s.includes("manila"))return "🇵🇭";return ""};

export default function LogisticaPage(){
 const [viajes,setViajes]=useState<Viaje[]>([]),[ops,setOps]=useState<Operacion[]>([]),[entregas,setEntregas]=useState<Entrega[]>([]),[logs,setLogs]=useState<Logistica[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("TODOS"),[q,setQ]=useState(""),[transportista,setTransportista]=useState(""),[tipo,setTipo]=useState(""),[estado,setEstado]=useState("");
 const [producto,setProducto]=useState(""),[paisOrigen,setPaisOrigen]=useState(""),[paisDestino,setPaisDestino]=useState(""),[fromDate,setFromDate]=useState(""),[toDate,setToDate]=useState(""),[minVol,setMinVol]=useState(""),[maxVol,setMaxVol]=useState(""),[selectedViaje,setSelectedViaje]=useState<string|null>(null);
 useEffect(()=>{(async()=>{try{const [v,o,e,l]=await Promise.all([supabase.from("viajes").select("id,operacion_id,vehiculo_id,origen,destino,fecha_salida,fecha_llegada,estado").order("fecha_salida",{ascending:false}).limit(100),supabase.from("operaciones").select("id,codigo,cantidad_tn,estado").order("fecha_operacion",{ascending:false}).limit(100),supabase.from("entregas").select("viaje_id,toneladas_entregadas,fecha_entrega,recibido_por").order("fecha_entrega",{ascending:false}).limit(200),supabase.from("operacion_logistica").select("operacion_id,estado,carta_porte_numero,carta_porte_estado,transportista,transportista_cuit,chofer_nombre,patente_camion,patente_acoplado,fecha_carga,fecha_estimada_entrega,destino,kilos_entregados").order("updated_at",{ascending:false}).limit(100)]);const err=[v.error,o.error,e.error,l.error].find(Boolean);if(err)throw new Error(err.message);setViajes((v.data||[]) as Viaje[]);setOps((o.data||[]) as Operacion[]);setEntregas((e.data||[]) as Entrega[]);setLogs((l.data||[]) as Logistica[])}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar logística.")}finally{setLoading(false)}})()},[]);
 const opMap=useMemo(()=>new Map(ops.map(o=>[o.id,o])),[ops]),logMap=useMemo(()=>new Map(logs.map(l=>[l.operacion_id,l])),[logs]);
 const stats=useMemo(()=>({transport:viajes.filter(v=>["EN_TRANSITO","EN CURSO","EN_CURSO"].includes(norm(v.estado))).length,scheduled:viajes.filter(v=>["PROGRAMADO","PROGRAMADA"].includes(norm(v.estado))).length,delivered:viajes.filter(v=>["ENTREGADO","ENTREGADA","FINALIZADO"].includes(norm(v.estado))).length,loading:viajes.filter(v=>["EN_CARGA","EN CARGA"].includes(norm(v.estado))).length,delayed:viajes.filter(v=>["DEMORADO","CON_DEMORA","DEMORADA"].includes(norm(v.estado))).length}),[viajes]);
 const rows=viajes.filter((v)=>{const n=norm(v.estado),l=logMap.get(v.operacion_id),op=opMap.get(v.operacion_id),productName=(op as any)?.producto_nombre||"Sin producto registrado",transportName=l?.transportista||"";return (tab==="TODOS"||(tab==="ORIGEN"&&!["ENTREGADO","ENTREGADA","FINALIZADO"].includes(n))||(tab==="TRANSITO"&&["EN_TRANSITO","EN CURSO","EN_CURSO"].includes(n))||(tab==="DESTINO"&&["EN_CARGA","PROGRAMADO","PROGRAMADA"].includes(n))||(tab==="ENTREGADAS"&&["ENTREGADO","ENTREGADA","FINALIZADO"].includes(n))||(tab==="DEMORADAS"&&["DEMORADO","CON_DEMORA","DEMORADA"].includes(n))||(tab==="CANCELADAS"&&n==="CANCELADA"))&&(!q||`${v.origen} ${v.destino} ${op?.codigo||""}`.toLowerCase().includes(q.toLowerCase()))&&(!estado||n===estado)&&(!transportista||transportName===transportista)&&(!producto||productName===producto)&&(!paisOrigen||String(v.origen||"")===paisOrigen)&&(!paisDestino||String(v.destino||l?.destino||"")===paisDestino)&&(!fromDate||String(l?.fecha_carga||v.fecha_salida||"").slice(0,10)>=fromDate)&&(!toDate||String(l?.fecha_carga||v.fecha_salida||"").slice(0,10)<=toDate)&&(!minVol||Number(op?.cantidad_tn||0)>=Number(minVol))&&(!maxVol||Number(op?.cantidad_tn||0)<=Number(maxVol))});
 const totalTn=ops.reduce((a,o)=>a+Number(o.cantidad_tn||0),0);
 const transportistas=[...new Set(logs.map(l=>l.transportista).filter(Boolean) as string[])];
 const destinations=useMemo(()=>{const m=new Map<string,number>();viajes.forEach(v=>{const d=v.destino||logMap.get(v.operacion_id)?.destino||"Sin destino";m.set(d,(m.get(d)||0)+Number(opMap.get(v.operacion_id)?.cantidad_tn||0))});return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[viajes,logMap,opMap]);
 
 return <main className="logistics-reference">
  <header className="logistics-head"><div><h1>Logística</h1><p>Organiza y controla el transporte de tus granos, desde el origen hasta el destino</p></div><div className="logistics-head-actions"><Link href="/logistica#calculadora-flete">▣ Calculadora de flete</Link><Link href="/empresas">▣ Proveedores</Link><Link href="/operaciones" className="logistics-new">＋ Nueva logística⌄</Link></div></header>
  {error&&<div className="logistics-alert">{error}</div>}
  <section className="logistics-kpis"><Kpi icon="▣" value={String(stats.transport+stats.loading)} label="En transporte" trend="Cargas en estados activos" tone="blue"/><Kpi icon="●" value={String(stats.scheduled)} label="Programadas" trend="Cargas programadas registradas" tone="purple"/><Kpi icon="✓" value={String(stats.delivered)} label="Entregadas" trend="Entregas registradas" tone="green"/><Kpi icon="◷" value={String(stats.loading)} label="En carga" trend="Cargas en estado de carga" tone="orange"/><Kpi icon="!" value={String(stats.delayed)} label="Con demoras" trend="Demoras registradas" tone="red"/></section>
  <nav className="logistics-tabs">{[["TODOS","Todas las cargas"],["ORIGEN","En origen"],["TRANSITO","En tránsito"],["DESTINO","En destino"],["ENTREGADAS","Entregadas"],["DEMORADAS","Demoradas"],["CANCELADAS","Canceladas"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</nav>
  <section id="calculadora-flete" className="logistics-layout"><div className="logistics-main"><div className="logistics-table-head"><span># CARGA</span><span>PRODUCTO</span><span>VOLUMEN</span><span>ORIGEN</span><span>DESTINO</span><span>TRANSPORTISTA</span><span>TIPO</span><span>FECHA CARGA</span><span>FECHA ESTIMADA</span><span>ESTADO</span><span>SEGUIMIENTO</span><span>ACCIONES</span></div>{loading?<div className="logistics-empty">Cargando logística…</div>:rows.map((v,i)=>{const op=opMap.get(v.operacion_id),l=logMap.get(v.operacion_id),st=norm(v.estado||l?.estado);return <div className="logistics-row" key={v.id}><strong>LG-${op?.codigo?.replace(/^OP-/,"")||v.id.slice(0,8)}</strong><span className="log-product"><b>•</b><span>{op?.codigo?"Producto según operación":"Sin producto registrado"}</span></span><span>{tn(op?.cantidad_tn??null)}</span><span>{flag(v.origen)} {v.origen||"—"}</span><span>{flag(v.destino||l?.destino)} {v.destino||l?.destino||"—"}</span><span>{l?.transportista||"—"}</span><span><em className="transport-badge">{l?.patente_camion||l?.patente_acoplado?"Camión":"Sin tipo registrado"}</em></span><span>{date(l?.fecha_carga||v.fecha_salida)}</span><span>{date(l?.fecha_estimada_entrega||v.fecha_llegada)}</span><span><em className={"log-status "+statusClass(st)}>{statusLabel(st)}</em></span><span className="tracking"><i></i><i></i><i></i><b>▰</b></span><span className="row-actions"><Link href={"/operaciones/"+v.operacion_id}>Ver</Link><button onClick={()=>setSelectedViaje(v.id)}>⋮</button></span></div>})}{!loading&&!rows.length&&<div className="logistics-empty">No hay cargas que coincidan con los filtros.</div>}</div>
   <aside className="logistics-filters"><div className="filter-title"><h2>Filtrar logística</h2><button onClick={()=>{setQ("");setEstado("");setTransportista("");setTipo("");setProducto("");setPaisOrigen("");setPaisDestino("");setFromDate("");setToDate("");setMinVol("");setMaxVol("")}}>Limpiar filtros</button></div><Filter label="Producto"><select value={producto} onChange={e=>setProducto(e.target.value)}><option value="">Todos los productos</option><option value="Sin producto registrado">Sin producto registrado</option></select></Filter><Filter label="Estado"><select value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos los estados</option><option value="EN_TRANSITO">En tránsito</option><option value="PROGRAMADO">Programadas</option><option value="ENTREGADO">Entregadas</option><option value="DEMORADO">Con demora</option></select></Filter><Filter label="Tipo de transporte"><select value={tipo} onChange={e=>setTipo(e.target.value)}><option value="">Todos los tipos</option><option>Camión</option><option value="Sin tipo registrado">Sin tipo registrado</option></select></Filter><Filter label="País de origen"><select value={paisOrigen} onChange={e=>setPaisOrigen(e.target.value)}><option value="">Todos los países</option>{[...new Set(viajes.map(v=>v.origen).filter(Boolean) as string[])].map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="País de destino"><select value={paisDestino} onChange={e=>setPaisDestino(e.target.value)}><option value="">Todos los países</option>{[...new Set(viajes.map(v=>v.destino||logMap.get(v.operacion_id)?.destino).filter(Boolean) as string[])].map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Rango de fecha de carga"><div className="log-two"><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></div></Filter><Filter label="Rango de volumen (TN)"><div className="log-two"><input value={minVol} onChange={e=>setMinVol(e.target.value)} inputMode="decimal" placeholder="Mínimo"/><input value={maxVol} onChange={e=>setMaxVol(e.target.value)} inputMode="decimal" placeholder="Máximo"/></div></Filter><Filter label="Transportista"><select value={transportista} onChange={e=>setTransportista(e.target.value)}><option value="">Todos los transportistas</option>{transportistas.map(x=><option key={x}>{x}</option>)}</select></Filter><button className="log-apply" onClick={()=>document.querySelector(".logistics-main")?.scrollIntoView({behavior:"smooth"})}>⚱ Aplicar filtros</button></aside></section>
  <section className="logistics-bottom"><Panel title="Rutas principales"><div className="route-map"><div className="route-line a"></div><div className="route-line b"></div><span>Rutas registradas</span></div><Legend items={destinations.map(([x,v])=>[String(x),`${totalTn?Math.round(Number(v)/totalTn*100):0}%`])}/></Panel><Panel title="Volumen por destino (TN)"><Bars items={destinations.map(([x,v])=>[String(x),Number(v).toLocaleString("es-AR")])}/></Panel><Panel title="Tipos de transporte"><div className="transport-chart"><div className="transport-donut"><b>{viajes.length}<small>Cargas<br/>totales</small></b></div><p>El tipo de transporte se mostrará cuando esté registrado en la logística de cada carga.</p></div></Panel><Panel title="Actividad reciente"><div className="activity-list">{rows.slice(0,5).map(v=><div key={v.id}><b>▣</b><span>{statusLabel(norm(v.estado))} {opMap.get(v.operacion_id)?.codigo||"carga"}</span><small>{date(v.fecha_salida)}</small></div>)}{!rows.length&&<p>Sin actividad reciente.</p>}</div></Panel></section>
 {selectedViaje&&<div className="logistics-modal"><div><button onClick={()=>setSelectedViaje(null)}>×</button><h2>Detalle de carga</h2><p><b>Carga:</b> LG-{selectedViaje.slice(0,8)}</p><p>Operación vinculada: {viajes.find(v=>v.id===selectedViaje)?.operacion_id||"—"}</p><p>Origen: {viajes.find(v=>v.id===selectedViaje)?.origen||"—"}</p><p>Destino: {viajes.find(v=>v.id===selectedViaje)?.destino||"—"}</p><button onClick={()=>setSelectedViaje(null)}>Cerrar</button></div></div>}
 
 </main>;
}
function statusLabel(s:string){if(s.includes("TRANSITO"))return "En tránsito";if(s.includes("CARGA"))return "En carga";if(s.includes("ENTREG"))return "Entregada";if(s.includes("DEMOR"))return "Con demora";if(s.includes("PROGRAM"))return "Programada";if(s.includes("CANCEL"))return "Cancelada";return s?String(s).toLowerCase().replaceAll("_"," "):"Sin estado"}
function statusClass(s:string){if(s.includes("TRANSITO"))return "transito";if(s.includes("CARGA"))return "carga";if(s.includes("ENTREG"))return "entregada";if(s.includes("DEMOR"))return "demora";if(s.includes("PROGRAM"))return "programada";if(s.includes("CANCEL"))return "cancelada";return "neutral"}
function Kpi({icon,value,label,trend,tone}:{icon:string;value:string;label:string;trend:string;tone:string}){return <div className={"log-kpi "+tone}><b>{icon}</b><span><strong>{value}</strong><small>{label}</small><i>{trend}</i></span></div>}
function Filter({label,children}:{label:string;children:any}){return <label className="log-filter">{label}{children}</label>}
function Panel({title,children}:{title:string;children:any}){return <section className="log-panel"><h2>{title}</h2>{children}</section>}
function Legend({items}:{items:string[][]}){return <div className="log-legend">{items.map((x,i)=><p key={i}><span><i></i>{x[0]}</span><b>{x[1]}</b></p>)}</div>}
function Bars({items}:{items:string[][]}){return <div className="log-bars">{items.map((x,i)=><div key={i}><span>{x[0]}</span><i style={{width:Math.max(8,100/(i+1))+"%"}}></i><b>{x[1]}</b></div>)}</div>}
