"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";
export default function PagosConfigPage(){
 const[companyId,setCompanyId]=useState(""),[mpId,setMpId]=useState(""),[mpAlias,setMpAlias]=useState(""),[mpEmail,setMpEmail]=useState(""),[mpRef,setMpRef]=useState(""),[mpEnabled,setMpEnabled]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesión no disponible.");const{data:p}=await supabase.from("profiles").select("active_company_id").eq("id",user.id).single();if(!p?.active_company_id)throw new Error("No hay empresa activa.");setCompanyId(p.active_company_id);const{data:x}=await supabase.from("integraciones_pago").select("id,habilitado,credencial_secret_ref,metadata").eq("empresa_id",p.active_company_id).eq("proveedor","MERCADOPAGO").maybeSingle();if(x){setMpId(x.id);setMpEnabled(Boolean(x.habilitado));setMpRef(x.credencial_secret_ref||"");setMpAlias(String(x.metadata?.alias||""));setMpEmail(String(x.metadata?.email||""));}}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar pagos.");}finally{setLoading(false)}})()},[]);
 async function save(){setSaving(true);setError("");setMsg("");try{const payload={empresa_id:companyId,proveedor:"MERCADOPAGO",ambiente:"production",habilitado:mpEnabled,credencial_secret_ref:mpRef.trim()||null,metadata:{alias:mpAlias.trim()||null,email:mpEmail.trim()||null}};const q=mpId?supabase.from("integraciones_pago").update(payload).eq("id",mpId):supabase.from("integraciones_pago").insert(payload).select("id").single();const{data,error:e}=await q;if(e)throw e;if(!mpId&&data?.id)setMpId(data.id);setMsg("Configuración de Mercado Pago guardada.");}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar Mercado Pago.");}finally{setSaving(false)}}
 if(loading)return <main className="module-page"><div className="module-hero"><h1>Configuración de pagos</h1></div></main>;
 return <main className="module-page"><div className="module-hero"><div><span className="eyebrow">PAGOS</span><h1>Configuración de pagos</h1><p>Configurá cuentas bancarias y Mercado Pago desde sus módulos reales.</p></div><Link className="module-pill" href="/medios-cobro">← Volver a Métodos de pago</Link></div>{error&&<div className="module-alert module-alert-error">{error}</div>}{msg&&<div className="module-alert">{msg}</div>}<section className="settings-grid"><Link href="/cuentas-bancarias" className="settings-card"><div className="settings-icon">🏦</div><div><h2>Cuentas bancarias</h2><p>Agregar y gestionar bancos, CBU/IBAN, alias y moneda.</p></div><span className="settings-arrow">→</span></Link><section className="company-card"><h2>Mercado Pago</h2><p>Configurá los datos comerciales y la referencia segura de la credencial. La credencial nunca se guarda en texto plano.</p><div className="settings-form-grid"><label>Alias / cuenta<input value={mpAlias} onChange={e=>setMpAlias(e.target.value)} placeholder="Nombre identificatorio"/></label><label>Email de Mercado Pago<input type="email" value={mpEmail} onChange={e=>setMpEmail(e.target.value)} placeholder="correo@mercadopago"/></label><label>Referencia del secreto<input value={mpRef} onChange={e=>setMpRef(e.target.value)} placeholder="Nombre del secreto en Supabase"/></label></div><label className="settings-toggle"><input type="checkbox" checked={mpEnabled} onChange={e=>setMpEnabled(e.target.checked)}/> Habilitar Mercado Pago</label><button className="module-pill" onClick={save} disabled={saving}>{saving?"Guardando…":"Guardar Mercado Pago"}</button></section></section></main>;
}