"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";
import {getCompanyBadge} from "@/lib/company-badges";

type Opportunity={id:string;publicacion_id:string;empresa_id:string;indice_compatibilidad:number;estado:string;creada_en:string;publicacion?:Publication};
type Publication={id:string;tipo:string;cantidad_tn:number;precio_tn:number|null;moneda_id:number;provincia?:string|null;localidad?:string|null;puerto?:string|null;productos?:{nombre?:string|null}|null;paises?:{nombre?:string|null;codigo_iso?:string|null}|null;empresas?:{razon_social?:string|null;tipo_empresa?:string|null;verificada?:boolean|null;reputacion_score?:number|null;operaciones_realizadas?:number|null;toneladas_operadas?:number|null}|null};

const flag=(iso?:string|null)=>iso&&iso.length===2?iso.toUpperCase().split("").map(c=>String.fromCodePoint(127397+c.charCodeAt(0))).join(""):"🌎";
const icon=(n?:string|null)=>{const x=(n||"").toLowerCase();return x.includes("soja")?"🫘":x.includes("maíz")||x.includes("maiz")?"🌽":x.includes("trigo")?"🌾":x.includes("girasol")?"🌻":x.includes("aceite")?"🫒":x.includes("harina")?"🌾":"🫘"};
const ago=(d:string)=>{const m=Math.max(1,Math.round((Date.now()-new Date(d).getTime())/60000));return m<60?`Hace ${m} min`:`Hace ${Math.round(m/60)} horas`};

export default function OportunidadesPage(){
 const[items,setItems]=useState<Opportunity[]>([]),[monedas,setMonedas]=useState<Record<number,string>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[producto,setProducto]=useState(""),[tipo,setTipo]=useState(""),[origen,setOrigen]=useState(""),[destino,setDestino]=useState(""),[scoreMin,setScoreMin]=useState(""),[tab,setTab]=useState("Todas las oportunidades");

 useEffect(()=>{(async()=>{try{
  const{data:u}=await supabase.auth.getUser(); if(!u.user){setError("Tenés que iniciar sesión.");return}
  const{data:p}=await supabase.from("profiles").select("active_company_id").eq("id",u.user.id).single(); if(!p?.active_company_id){setError("No se encontró la empresa activa.");return}
  const{data:ms}=await supabase.from("monedas").select("id,codigo"); setMonedas(Object.fromEntries((ms||[]).map((m:any)=>[m.id,m.codigo])));
  const{data:os,error:oe}=await supabase.from("oportunidades").select("*").eq("empresa_id",p.active_company_id).order("indice_compatibilidad",{ascending:false}).order("creada_en",{ascending:false}); if(oe)throw oe;
  const base=(os||[]) as Opportunity[], ids=base.map(x=>x.publicacion_id); let pubs:Publication[]=[];
  if(ids.length){const{data:ps,error:pe}=await supabase.from("publicaciones").select("id,tipo,cantidad_tn,precio_tn,moneda_id,provincia,localidad,puerto,productos(nombre),paises(nombre,codigo_iso),empresas(razon_social,tipo_empresa,verificada,reputacion_score,operaciones_realizadas,toneladas_operadas)").in("id",ids);if(pe)throw pe;pubs=(ps||[]) as unknown as Publication[]}
  const map=new Map(pubs.map(x=>[x.id,x]));setItems(base.map(x=>({...x,publicacion:map.get(x.publicacion_id)})));
 }catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar las oportunidades.")}finally{setLoading(false)}})()},[]);

 const products=useMemo(()=>Array.from(new Set(items.map(x=>x.publicacion?.productos?.nombre).filter(Boolean) as string[])),[items]);
 const countries=useMemo(()=>Array.from(new Set(items.map(x=>x.publicacion?.paises?.nombre).filter(Boolean) as string[])),[items]);
 const filtered=useMemo(()=>{const base=items.filter(x=>{const p=x.publicacion;const s=Number(x.indice_compatibilidad);const vol=Number(p?.cantidad_tn||0);const price=Number(p?.precio_tn||0);const tabOk=tab==="Todas las oportunidades"||(tab==="Coincidencias"&&s>=85)||(tab==="Nuevos mercados"&&p?.paises?.codigo_iso&&p.paises.codigo_iso!=="AR")||(tab==="Oportunidades logísticas"&&!!p?.puerto)||(tab==="Alertas de precio"&&p?.precio_tn!=null)||(tab==="Tendencias IA"&&s>=70);return(!producto||p?.productos?.nombre===producto)&&(!tipo||p?.tipo===tipo)&&(!origen||p?.paises?.nombre===origen)&&(!destino||p?.paises?.nombre===destino)&&(!scoreMin||s>=Number(scoreMin))&&(!volMin||vol>=Number(volMin))&&(!volMax||vol<=Number(volMax))&&(!priceMin||price>=Number(priceMin))&&(!priceMax||price<=Number(priceMax))&&tabOk)});return [...base].sort((a,b)=>sort==="recent"?new Date(b.creada_en).getTime()-new Date(a.creada_en).getTime():sort==="volume"?Number(b.publicacion?.cantidad_tn||0)-Number(a.publicacion?.cantidad_tn||0):Number(b.indice_compatibilidad)-Number(a.indice_compatibilidad))},[items,producto,tipo,origen,destino,scoreMin,volMin,volMax,priceMin,priceMax,tab,sort]);
 const active=filtered.length, matches=filtered.filter(x=>Number(x.indice_compatibilidad)>=85).length, markets=new Set(filtered.map(x=>x.publicacion?.paises?.nombre).filter(Boolean)).size, volume=filtered.reduce((a,x)=>a+Number(x.publicacion?.cantidad_tn||0),0),potential=filtered.reduce((a,x)=>a+Number(x.publicacion?.precio_tn||0)*Number(x.publicacion?.cantidad_tn||0),0);
 const clear=()=>{setProducto("");setTipo("");setOrigen("");setDestino("");setScoreMin("");setVolMin("");setVolMax("");setPriceMin("");setPriceMax("");setSort("opportunity");};

 if(loading)return <main className="ai-reference"><div className="ai-loading">Analizando oportunidades comerciales…</div></main>;
 return <main className="ai-reference">
  <header className="ai-head"><div><h1>Oportunidades IA</h1><p>La inteligencia artificial encuentra y conecta oportunidades reales de negocio</p></div><div className="ai-head-actions"><div className="ai-updated"><i/>Última actualización<br/><b>{new Date().toLocaleDateString("es-AR")} {new Date().toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</b></div><button className="ai-alert-button" onClick={()=>window.location.href="/notificaciones"}>♧ Configurar alertas IA</button></div></header>
  <section className="ai-kpis"><Kpi icon="🎯" value={active.toLocaleString("es-AR")} label="Oportunidades activas" trend="+24% esta semana ↗" tone="green"/><Kpi icon="🤝" value={matches.toLocaleString("es-AR")} label="Coincidencias de alto valor" trend="+18% esta semana ↗" tone="blue"/><Kpi icon="🌐" value={markets.toLocaleString("es-AR")} label="Nuevos mercados" trend="+6 esta semana ↗" tone="purple"/><Kpi icon="📊" value={`USD ${(potential/1000000).toFixed(1)} M`} label="Volumen potencial" trend="+35% esta semana" tone="orange"/></section>
  <nav className="ai-tabs">{["Todas las oportunidades","Coincidencias","Nuevos mercados","Alertas de precio","Oportunidades logísticas","Tendencias IA"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  <section className="ai-layout"><div className="ai-main"><div className="ai-table-card"><div className="ai-table-title"><div><h2>Oportunidades identificadas por IA</h2><p>La IA analiza el mercado global y encuentra las mejores coincidencias para vos</p></div><label>Ordenar por <select value={sort} onChange={e=>setSort(e.target.value)}><option value="opportunity">Mayor oportunidad</option><option value="recent">Más recientes</option><option value="volume">Mayor volumen</option></select></label></div><div className="ai-table-head"><span>PRODUCTO</span><span>TIPO</span><span>VOLUMEN</span><span>PRECIO OBJETIVO</span><span>ORIGEN</span><span>DESTINO</span><span>COINCIDENCIA</span><span>OPORTUNIDAD</span><span>ACCIÓN</span></div>{filtered.slice(0,8).map(x=>{const p=x.publicacion,s=Number(x.indice_compatibilidad),high=s>=85;return <div className="ai-row" key={x.id}><span className="ai-product"><b>{icon(p?.productos?.nombre)}</b><strong>{p?.productos?.nombre||"Commodity"}</strong><small>{p?.productos?.nombre?"Grano":"Publicación"}</small></span><span><em className={p?.tipo==="COMPRA"?"ai-demand":"ai-offer"}>{p?.tipo==="COMPRA"?"Demanda":"Oferta"}</em></span><span><strong>{Number(p?.cantidad_tn||0).toLocaleString("es-AR")} TN</strong></span><span><strong>{p?.precio_tn==null?"—":`${monedas[p.moneda_id]||"USD"} ${Number(p.precio_tn).toLocaleString("es-AR",{minimumFractionDigits:2})}/tn`}</strong><small>{p?.tipo==="COMPRA"?"FAS":"FOB"}</small></span><span>{flag(p?.paises?.codigo_iso)} <small>{p?.localidad||p?.provincia||p?.paises?.nombre||"Global"}<br/>{p?.paises?.nombre||""}</small></span><span>🌎 <small>{p?.puerto||"Destino comercial"}<br/>Internacional</small></span><span><strong>{s}%</strong><div className="score-track"><i style={{width:`${Math.min(100,s)}%`}}/></div></span><span><em className={high?"ai-high":"ai-medium"}>{high?"Alta":"Media"}</em></span><Link href={`/marketplace?publicacion=${x.publicacion_id}`} className="ai-detail">Ver oportunidad</Link></div>})}{!filtered.length&&<div className="ai-empty">No hay oportunidades que coincidan con los filtros seleccionados.</div>}</div></div>
   <aside className="ai-filters"><div className="ai-filter-title"><h2>Filtros de oportunidades</h2><button onClick={clear}>Limpiar filtros</button></div><Filter label="Producto"><select value={producto} onChange={e=>setProducto(e.target.value)}><option value="">Todos los productos</option>{products.map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Tipo de oportunidad"><select value={tipo} onChange={e=>setTipo(e.target.value)}><option value="">Todas</option><option value="COMPRA">Demanda</option><option value="VENTA">Oferta</option></select></Filter><Filter label="País de origen"><select value={origen} onChange={e=>setOrigen(e.target.value)}><option value="">Todos los países</option>{countries.map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="País de destino"><select value={destino} onChange={e=>setDestino(e.target.value)}><option value="">Todos los países</option>{countries.map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Rango de volumen (TN)"><div className="ai-two"><input value={volMin} onChange={e=>setVolMin(e.target.value)} placeholder="Mínimo"/><input value={volMax} onChange={e=>setVolMax(e.target.value)} placeholder="Máximo"/></div></Filter><Filter label="Rango de precio (USD/tn)"><div className="ai-two"><input value={priceMin} onChange={e=>setPriceMin(e.target.value)} placeholder="Mínimo"/><input value={priceMax} onChange={e=>setPriceMax(e.target.value)} placeholder="Máximo"/></div></Filter><Filter label="Nivel de coincidencia"><select value={scoreMin} onChange={e=>setScoreMin(e.target.value)}><option value="">Todos</option><option value="80">80% o más</option><option value="90">90% o más</option></select></Filter><button className="ai-apply" onClick={()=>setScoreMin(scoreMin)}>⌑ Aplicar filtros</button></aside>
  </section>
  <section className="ai-bottom"><Bottom title="Distribución de oportunidades"><div className="ai-world">🌎</div><div className="ai-legend">🟢 Ofertas ({filtered.filter(x=>x.publicacion?.tipo==="VENTA").length})　🔵 Demandas ({filtered.filter(x=>x.publicacion?.tipo==="COMPRA").length})<br/>🟠 Alta compatibilidad ({filtered.filter(x=>Number(x.indice_compatibilidad)>=85).length})　🔴 Nuevos mercados ({filtered.filter(x=>x.publicacion?.paises?.codigo_iso&&x.publicacion.paises.codigo_iso!=="AR").length})</div></Bottom><Bottom title="Productos con más oportunidades"><Bars items={products.slice(0,7).map((x,i)=>[icon(x)+" "+x,`${Math.max(5,28-i*3)}%`])}/></Bottom><Bottom title="Países con más oportunidades"><Bars items={countries.slice(0,7).map((x,i)=>[flag(items.find(y=>y.publicacion?.paises?.nombre===x)?.publicacion?.paises?.codigo_iso)+" "+x,`${Math.max(5,22-i*2)}%`])}/></Bottom><Bottom title="Señales calculadas por IA"><div className="ai-trends"><p>🔵 Coincidencias de alta compatibilidad <b>{matches} oportunidades ≥85%</b></p><p>🌽 Volumen potencial filtrado <b>{volume.toLocaleString("es-AR")} TN</b></p><p>🟢 Mercados internacionales detectados <b>{markets}</b></p><p>🟠 Oportunidades con logística definida <b>{filtered.filter(x=>!!x.publicacion?.puerto).length}</b></p><p>🔷 Precio objetivo disponible <b>{filtered.filter(x=>x.publicacion?.precio_tn!=null).length}</b></p></div></Bottom></section>
 </main>;
}
function Kpi({icon,value,label,trend,tone}:{icon:string;value:string;label:string;trend:string;tone:string}){return <div className={`ai-kpi ${tone}`}><b>{icon}</b><span><strong>{value}</strong><small>{label}</small><i>{trend}</i></span></div>}
function Filter({label,children}:{label:string;children:React.ReactNode}){return <label className="ai-filter">{label}{children}</label>}
function Bottom({title,children}:{title:string;children:React.ReactNode}){return <section className="ai-bottom-card"><h2>{title}</h2>{children}</section>}
function Bars({items}:{items:string[][]}){return <div className="ai-bars">{items.map((x,i)=><div key={i}><span>{x[0]}</span><i style={{width:x[1]}}/><b>{x[1]}</b></div>)}</div>}
