"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase/client";

type Quote={id:string;price:number|null;currency:string|null;unit:string|null;price_type:string;market_date:string;obtained_at:string;variation:number|null;previous_value:number|null;position:string|null;freshness:string;commodity_id:string|null;product_id:number|null;market:string|null;port:string|null;payload?:Record<string,unknown>|null;};
type Row={code:string;name:string;q?:Quote};

const icon=(code:string)=>code==="SOJA"?"🫘":code==="MAIZ"?"🌽":code==="TRIGO"?"🌾":code==="GIRASOL"?"🌻":code.toLowerCase().includes("aceite")?"🫒":"🌾";
const money=(q?:Quote)=>q?.price==null?"Sin cotización":`${q.currency||"Moneda"} ${Number(q.price).toLocaleString("es-AR",{minimumFractionDigits:2,maximumFractionDigits:2})}`;


export default function PizarraPage(){
 const[quotes,setQuotes]=useState<Quote[]>([]),[codes,setCodes]=useState<Record<string,string>>({}),[productNames,setProductNames]=useState<Record<string,string>>({}),[productCategories,setProductCategories]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState(""),[syncMsg,setSyncMsg]=useState(""),[boardTab,setBoardTab]=useState("Granos"),[range,setRange]=useState("1D"),[compare,setCompare]=useState("SOJA"),[detail,setDetail]=useState<Quote|null>(null),[market,setMarket]=useState("BCR"),[productFilter,setProductFilter]=useState("ALL"),[priceType,setPriceType]=useState("PIZARRA_CAC");
 async function load(){
  setLoading(true);setError("");
  const[q,c,catalog]=await Promise.all([
   supabase.from("market_quotes").select("id,price,currency,unit,price_type,market_date,obtained_at,variation,previous_value,position,freshness,commodity_id,product_id,market,port,payload").order("market_date",{ascending:false}).order("obtained_at",{ascending:false}).limit(300),
   supabase.from("commodities").select("id,codigo"),
   supabase.from("productos").select("id,codigo,nombre,categoria").eq("activo",true)
  ]);
  if(q.error||c.error)setError(q.error?.message||c.error?.message||"No se pudo cargar la pizarra.");
  setQuotes((q.data||[]) as Quote[]);setCodes(Object.fromEntries((c.data||[]).map((x:any)=>[x.id,String(x.codigo).toUpperCase()])));setProductNames(Object.fromEntries((catalog.data||[]).map((x:any)=>[String(x.id),x.nombre] )));setProductCategories(Object.fromEntries((catalog.data||[]).map((x:any)=>[String(x.id),x.categoria||""])));setLoading(false);
 }
 useEffect(()=>{void load()},[]);
 async function sync(){
  setSyncing(true);setSyncMsg("");setError("");
  try{const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Necesitás iniciar sesión.");
   const{data:j,error:invokeError}=await supabase.functions.invoke("market-data-sync");
   if(invokeError)throw new Error(invokeError.message||"No se pudo actualizar BCR/CAC.");
   if(!j?.ok)throw new Error(j?.error||"No se pudo actualizar BCR/CAC.");
   setSyncMsg("Pizarra actualizada desde BCR/CAC. El histórico fue conservado.");await load();
  }catch(e){setError(e instanceof Error?e.message:"Error de actualización.")}finally{setSyncing(false)}
 }
 const codeFor=(q:Quote)=>codes[q.commodity_id||""]||productNames[String(q.product_id||"")]||q.product_id?.toString()||q.commodity_id||"OTRO";
 const categoryFor=(q:Quote)=>productCategories[String(q.product_id||"")]||"";
 const inTab=(q:Quote)=>{if(boardTab==="Granos"){const cat=categoryFor(q);const code=codeFor(q);return !cat&&!q.product_id&&!q.commodity_id||["Cereal","Oleaginosa"].includes(cat)||["SOJA","MAIZ","TRIGO","GIRASOL","SORGO"].includes(code);}const n=productNames[String(q.product_id||"")]?.toLowerCase()||"";if(boardTab==="Aceites")return n.includes("aceite");if(boardTab==="Harinas")return n.includes("harina")||categoryFor(q)==="Harina";if(boardTab==="Subproductos")return categoryFor(q)==="Subproducto"||["pellet","expeller","afrechillo","subproducto"].some(x=>n.includes(x));return true;};
 const filteredQuotes=useMemo(()=>quotes.filter(q=>(priceType==="ALL"||q.price_type===priceType)&&(productFilter==="ALL"||codeFor(q)===productFilter)&&inTab(q)),[quotes,codes,productNames,productCategories,priceType,productFilter,boardTab]);
 const latest=useMemo(()=>{const m=new Map<string,Quote>();for(const q of filteredQuotes){const code=codeFor(q);if(!m.has(code))m.set(code,q)}return m},[filteredQuotes,codes,productNames]);
 const wanted=useMemo(()=>Array.from(new Set(filteredQuotes.map(codeFor))),[filteredQuotes,codes,productNames]);
 const rows:Row[]=wanted.map(code=>({code,name:productNames[String(filteredQuotes.find(q=>codeFor(q)===code)?.product_id||"")]||((latest.get(code)?.product_id==null&&latest.get(code)?.commodity_id==null)?"Cotización BCR/CAC (producto no informado)":code),q:latest.get(code)}));
 const up=rows.filter(r=>(r.q?.variation||0)>0).length,down=rows.filter(r=>(r.q?.variation||0)<0).length,flat=rows.filter(r=>r.q?.variation===0).length,volume=filteredQuotes.length; const statsFor=(code:string)=>{const hs=filteredQuotes.filter(q=>codeFor(q)===code&&q.price!=null);const prices=hs.map(q=>Number(q.price));const latestDate=hs[0]?.market_date;const day=latestDate?hs.filter(q=>q.market_date===latestDate):hs;const dayPrices=day.map(q=>Number(q.price)).filter(Number.isFinite);return {open:day.at(-1)?.price??null,min:dayPrices.length?Math.min(...dayPrices):null,max:dayPrices.length?Math.max(...dayPrices):null};};
 const rangeSize:Record<string,number>={"1D":30,"1S":50,"1M":100,"3M":150,"1A":200,"Todo":300};
 const compareCodes=wanted.slice(0,4); const compareSelectedCode=compareCodes.includes(productFilter)?productFilter:(compareCodes[0]||""); const soja=filteredQuotes.filter(q=>codeFor(q)===compareSelectedCode&&q.price!=null).slice(0,rangeSize[range]||30).reverse(); const compareSeries=compareCodes.map(code=>({code,points:filteredQuotes.filter(q=>codeFor(q)===code&&q.price!=null).slice(0,20).reverse()}));
 return <main className="board-reference">
  <header className="board-head"><div><h1>Pizarra de granos</h1><p>Cotizaciones en tiempo real - Bolsa de Comercio de Rosario</p></div><div className="board-head-right"><span><i/> Mercado abierto</span><span>◷ {new Date().toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})} (GMT-3)</span><small>Bolsa de Comercio de Rosario</small><a className="board-source" href="https://www.bcr.com.ar/es/mercados/mercado-de-granos/cotizaciones/cotizaciones-locales-1" target="_blank" rel="noreferrer">↗ &nbsp; Ver fuente oficial</a></div></header>
  {error&&<div className="module-alert module-alert-error">{error}</div>}{syncMsg&&<div className="module-alert">{syncMsg}</div>}
  <div className="board-toolbar"><nav>{["Granos","Aceites","Harinas","Subproductos"].map(x=><button className={boardTab===x?"active":""} onClick={()=>setBoardTab(x)} key={x}>{x}</button>)}</nav><span>Última actualización: {filteredQuotes[0]?.obtained_at?new Date(filteredQuotes[0].obtained_at).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"}):"Sin sincronización"}</span><button className="board-refresh" onClick={sync} disabled={syncing}>⟳ &nbsp;{syncing?"Actualizando…":"Actualizar"}</button></div>
  <section className="board-layout">
   <section className="board-table-card"><div className="board-table-head"><span>PRODUCTO</span><span>DISPONIBLE</span><span>ÚLTIMO</span><span>VARIACIÓN</span><span>APERTURA</span><span>MÍNIMO</span><span>MÁXIMO</span><span>VOLUMEN</span><span>TENDENCIA</span><span>GRÁFICO</span></div>
    {loading?<div className="board-empty">Cargando pizarra…</div>:rows.map(r=><div className="board-row" key={r.code}><span className="board-product"><b>{icon(r.code)}</b><strong>{r.name}</strong><small>{r.q?.market||r.q?.port||"Fuente BCR/CAC"}</small></span><span>{r.q?.position||"—"}</span><strong>{money(r.q)}</strong><span className={(r.q?.variation||0)>=0?"positive":"negative"}>{r.q?.variation==null?"—":`${r.q.variation>=0?"+":""}${r.q.variation.toFixed(2)}`}<small className="board-var-pct">{r.q?.variation!=null&&r.q.previous_value?` (${r.q.variation>=0?"+":""}${((r.q.variation/Math.max(0.0001,r.q.previous_value))*100).toFixed(2)}%)`:""}</small> {r.q?.variation!=null?(r.q.variation>=0?"↗":"↘"):""}</span><span>{(()=>{const s=statsFor(r.code);return s.open==null?"—":Number(s.open).toLocaleString("es-AR",{minimumFractionDigits:2})})()}</span><span>{(()=>{const s=statsFor(r.code);return s.min==null?"—":Number(s.min).toLocaleString("es-AR",{minimumFractionDigits:2})})()}</span><span>{(()=>{const s=statsFor(r.code);return s.max==null?"—":Number(s.max).toLocaleString("es-AR",{minimumFractionDigits:2})})()}</span><span>{(()=>{const v=Number((r.q?.payload as any)?.volume);return Number.isFinite(v)&&v>0?`${v.toLocaleString("es-AR")} tn`:"—"})()}</span><span className="board-trend"><i/></span><button onClick={()=>setDetail(r.q||null)} disabled={!r.q}>Ver detalle</button></div>)}
   </section>
   <aside className="board-sidebar"><section><h2>Seleccionar mercado</h2><select value={market} onChange={e=>setMarket(e.target.value)}><option value="BCR">Bolsa de Comercio de Rosario</option></select><select value={productFilter} onChange={e=>setProductFilter(e.target.value)}><option value="ALL">Todos los productos</option>{wanted.map(code=><option key={code} value={code}>{productNames[code]||code}</option>)}</select><select value={priceType} onChange={e=>setPriceType(e.target.value)}><option value="PIZARRA_CAC">Pizarra CAC</option><option value="PIZARRA_DISPONIBLE">Mercado disponible</option><option value="ALL">Todos los tipos de precio</option></select></section><section><h2>📊 &nbsp;Resumen del mercado</h2><dl><div><dt>Productos</dt><dd>{rows.length}</dd></div><div><dt>En alza</dt><dd className="positive">{up} ↗</dd></div><div><dt>En baja</dt><dd className="negative">{down} ↘</dd></div><div><dt>Sin cambios</dt><dd>{flat} →</dd></div><div><dt>Observaciones</dt><dd>{volume}</dd></div><div><dt>Última actualización</dt><dd>{quotes[0]?.obtained_at?new Date(quotes[0].obtained_at).toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"}):"—"}</dd></div></dl></section><section><h2>Variación diaria</h2><div className="board-donut"><div><strong>{rows.length?Math.round(up/Math.max(1,rows.length)*100):0}%</strong></div><ul><li><i className="up"/> En alza <b>{rows.length?Math.round(up/Math.max(1,rows.length)*100):0}%</b></li><li><i className="down"/> En baja <b>{rows.length?Math.round(down/Math.max(1,rows.length)*100):0}%</b></li><li><i className="flat"/> Sin cambios <b>{rows.length?Math.round(flat/Math.max(1,rows.length)*100):0}%</b></li></ul></div></section><section><div className="board-side-title"><h2>🔔 &nbsp;Alertas de precios</h2><a href="/notificaciones">Ver todas →</a></div><div className="board-alert-list">{rows.filter(r=>r.q?.variation!=null).slice(0,4).map(r=><div className="board-alert-item" key={r.code}><span className={r.q!.variation!>=0?"alert-up":"alert-down"}>{r.q!.variation!>=0?"↗":"↘"}</span><span><strong>{r.name}</strong> {r.q!.variation!>=0?"registró una suba":"registró una baja"}<small>Última cotización disponible</small></span></div>)}</div></section></aside>
  </section>
  <section className="board-bottom-grid"><section className="board-chart-card"><div className="board-section-title"><strong>Evolución de precios - {productNames[String(soja[0]?.product_id||"")]||compare||"Producto"}</strong><div>{["1D","1S","1M","3M","1A","Todo"].map(x=><button className={range===x?"active":""} onClick={()=>setRange(x)} key={x}>{x}</button>)}</div></div><div className="board-chart">{soja.length?<svg viewBox="0 0 900 260" preserveAspectRatio="none"><defs><linearGradient id="boardArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#28b879" stopOpacity=".3"/><stop offset="100%" stopColor="#28b879" stopOpacity=".02"/></linearGradient></defs><polyline fill="url(#boardArea)" stroke="none" points={`0,250 ${soja.map((q,i)=>{const vals=soja.map(x=>x.price||0),max=Math.max(...vals),min=Math.min(...vals);const x=20+i*860/Math.max(1,soja.length-1),y=225-(q.price==null?0:((q.price-min)/Math.max(1,max-min))*190);return x+","+y}).join(" ")} 900,250`}/><polyline fill="none" stroke="#16a96d" strokeWidth="3" points={soja.map((q,i)=>{const vals=soja.map(x=>x.price||0),max=Math.max(...vals),min=Math.min(...vals);const x=20+i*860/Math.max(1,soja.length-1),y=225-(q.price==null?0:((q.price-min)/Math.max(1,max-min))*190);return x+","+y}).join(" ")}/></svg>:<div className="board-empty">Sin datos de evolución para este producto. Actualizá BCR/CAC para cargar cotizaciones verificadas.</div>}</div><div className="board-axis"><span>{soja[0]?.market_date?new Date(soja[0].market_date).toLocaleDateString("es-AR"):"—"}</span><span>{soja.at(-1)?.market_date?new Date(soja.at(-1)!.market_date).toLocaleDateString("es-AR"):"—"}</span></div></section><section className="board-compare"><div className="board-section-title"><strong>Comparativa de productos</strong></div><div className="board-product-tabs">{compareCodes.map(x=><button className={compare===x?"active":""} onClick={()=>setCompare(x)} key={x}>{productNames[x]||x}</button>)}</div><div className="board-compare-chart"><span>{compareCodes.map(code=><span key={code}>▪ {productNames[code]||code}　</span>)}</span>{compareSeries.some(s=>s.points.length>1)?<svg viewBox="0 0 500 190" preserveAspectRatio="none">{compareSeries.map((s,si)=>{const vals=s.points.map(q=>q.price||0),max=Math.max(...vals,...compareSeries.flatMap(x=>x.points.map(q=>q.price||0))),min=Math.min(...vals,...compareSeries.flatMap(x=>x.points.map(q=>q.price||0)));const pts=s.points.map((q,i)=>{const x=12+i*476/Math.max(1,s.points.length-1),y=165-((q.price||min)-min)/Math.max(0.0001,max-min)*135;return `${x},${y}`}).join(" ");return <polyline key={s.code} fill="none" stroke={["#18a96d","#f0bf18","#c97820","#f0d019"][si]} strokeWidth="2.5" points={pts}/>})}</svg>:<div className="board-empty">El histórico comparativo aparecerá cuando existan varias cotizaciones verificadas.</div>}</div></section></section>
 {detail&&<div className="board-detail-modal"><div><button onClick={()=>setDetail(null)}>×</button><h2>Detalle de cotización</h2><p><b>Producto:</b> {productNames[String(detail.product_id||"")]||codes[detail.commodity_id||""]||detail.product_id||"Commodity"}</p><p><b>Precio:</b> {money(detail)}</p><p><b>Variación:</b> {detail.variation==null?"—":`${detail.variation>=0?"+":""}${detail.variation.toFixed(2)} ${detail.currency||""}${detail.previous_value?` (${((detail.variation/detail.previous_value)*100).toFixed(2)}%)`:""}`}</p><p><b>Mercado:</b> {detail.price_type==="PIZARRA_DISPONIBLE"?"BCR · Mercado disponible":"CAC · Pizarra"}</p><p><b>Fecha de mercado:</b> {new Date(detail.market_date).toLocaleDateString("es-AR")}</p><p><b>Actualizado:</b> {new Date(detail.obtained_at).toLocaleString("es-AR")}</p><button onClick={()=>{setCompare(codeFor(detail));setDetail(null);window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}}>Ver evolución</button></div></div>}</main>
}