"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";
type Payment={id:string;operacion_id:string;importe:number;moneda_id:number|null;metodo_pago:string|null;estado:string|null;fecha_pago:string|null;comprobante:string|null};
export default function PagosPage(){
 const [rows,setRows]=useState<Payment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [currencies,setCurrencies]=useState<Record<number,string>>({});
 useEffect(()=>{(async()=>{const[{data,error:e},{data:m}]=await Promise.all([supabase.from("pagos").select("id,operacion_id,importe,moneda_id,metodo_pago,estado,fecha_pago,comprobante").order("creado_en",{ascending:false}).limit(100),supabase.from("monedas").select("id,codigo")]);if(e)setError(e.message);setRows(data||[]);setCurrencies(Object.fromEntries((m||[]).map((x:{id:number;codigo:string})=>[x.id,x.codigo])));setLoading(false)})()},[]);
 return <main className="module-page"><div className="module-hero"><div><span className="eyebrow">TESORERÍA OPERATIVA</span><h1>Pagos</h1><p>Movimientos económicos registrados y vinculados a operaciones.</p></div><span className="module-pill">{rows.length} registros</span></div>{error&&<div className="module-alert module-alert-error">{error}</div>}{loading?<div className="loading-card">Cargando pagos…</div>:rows.length===0?<div className="empty-module"><div className="empty-module-icon">$</div><h2>No hay pagos registrados</h2><p>Los pagos aparecerán cuando una operación registre un movimiento económico autorizado.</p><Link href="/operaciones" className="secondary-action">Ir a operaciones →</Link></div>:<div className="document-grid">{rows.map(p=><article className="document-card" key={p.id}><div><strong>{currencies[p.moneda_id??0]||"Moneda no informada"} {Number(p.importe||0).toLocaleString("es-AR")}</strong><p>Operación {p.operacion_id}</p><small>{p.metodo_pago||"Medio no informado"} · {p.estado||"Sin estado"} · {p.fecha_pago?new Date(p.fecha_pago).toLocaleString("es-AR"):"Fecha pendiente"}</small></div><span className={"document-status "+(p.estado==="CONFIRMADO"?"ok":"pending")}>{p.estado||"PENDIENTE"}</span></article>)}</div>}</main>;
}