"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase/client";

type Payment={id:string;operacion_id:string;importe:number;moneda_id:number|null;metodo_pago:string|null;estado:string|null;fecha_pago:string|null};
const money=(n:number,c:string)=>`${c} ${Number(n||0).toLocaleString("en-US",{maximumFractionDigits:0})}`;
const label=(s:string|null)=>/RECIB|PAGAD|CONFIRM/i.test(s||"")?"Recibido":/PROCES|PEND/i.test(s||"")?"En proceso":s||"Pendiente";

export default function PagosPage(){
 const[rows,setRows]=useState<Payment[]>([]),[curr,setCurr]=useState<Record<number,string>>({}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const [p,m]=await Promise.all([supabase.from("pagos").select("id,operacion_id,importe,moneda_id,metodo_pago,estado,fecha_pago").order("creado_en",{ascending:false}).limit(100),supabase.from("monedas").select("id,codigo")]);if(p.error)throw p.error;if(m.error)throw m.error;setRows((p.data||[]) as Payment[]);setCurr(Object.fromEntries((m.data||[]).map((x:any)=>[x.id,x.codigo])))}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar los pagos.")}finally{setLoading(false)}})()},[]);
 const totals=useMemo(()=>({received:rows.filter(r=>/RECIB|PAGAD|CONFIRM/i.test(r.estado||"")).reduce((s,r)=>s+Number(r.importe||0),0),process:rows.filter(r=>/PROCES|PEND/i.test(r.estado||"")).reduce((s,r)=>s+Number(r.importe||0),0)}),[rows]);
 return <main className="payments-page"><header className="payments-hero"><div><h1>Pagos</h1><p>Gestiona los pagos de tus operaciones, comisiones y retiros de forma segura.</p></div></header><nav className="payments-tabs"><a className="active" href="/pagos">Resumen</a><a href="/transacciones">Transacciones</a><a href="/cuentas-bancarias">Cuentas bancarias</a><a href="/medios-cobro">Métodos de pago</a><a href="/comisiones">Retiros / comisiones</a><a href="/facturas">Facturas</a><a href="/configuracion">Configuración</a></nav>{error&&<div className="module-alert module-alert-error">{error}</div>}{loading?<div className="payments-loading">Cargando pagos…</div>:<><section className="payment-kpis"><div className="payment-kpi green"><div><small>Pagos recibidos</small><strong>{money(totals.received,"USD")}</strong><em>Total de pagos registrados</em></div></div><div className="payment-kpi amber"><div><small>En proceso</small><strong>{money(totals.process,"USD")}</strong><em>En operaciones activas</em></div></div></section><section className="payments-panel"><h2>Últimos pagos</h2><div className="payments-table-wrap"><table><thead><tr><th>Fecha</th><th>Operación</th><th>Método</th><th>Importe</th><th>Estado</th></tr></thead><tbody>{rows.slice(0,10).map(r=><tr key={r.id}><td>{r.fecha_pago?new Date(r.fecha_pago).toLocaleDateString("es-AR"):"—"}</td><td>{r.operacion_id||"—"}</td><td>{r.metodo_pago||"Pago de operación"}</td><td>{money(Number(r.importe||0),curr[r.moneda_id||0]||"USD")}</td><td>{label(r.estado)}</td></tr>)}</tbody></table></div></section></>}</main>;
}