"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase/client";
const SUPPORT_EMAIL="soporte@agrobrokeria.online";
export default function SoportePage(){
 const[tickets,setTickets]=useState<any[]>([]),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState(""),[msg,setMsg]=useState("");
 const[category,setCategory]=useState("PROBLEMA"),[priority,setPriority]=useState("MEDIA"),[subject,setSubject]=useState(""),[description,setDescription]=useState("");
 async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const{data,error:e}=await supabase.from("soporte_tickets").select("id,categoria,asunto,descripcion,prioridad,estado,notas_admin,creado_at,actualizado_at").eq("profile_id",user.id).order("creado_at",{ascending:false});if(e)setError(e.message);setTickets(data||[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function send(){setSending(true);setError("");setMsg("");try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesión no disponible.");if(!subject.trim()||!description.trim())throw new Error("Completá asunto y descripción.");const{error:e}=await supabase.from("soporte_tickets").insert({profile_id:user.id,email:user.email||null,categoria:category,asunto:subject.trim(),descripcion:description.trim(),prioridad:priority});if(e)throw e;setSubject("");setDescription("");setMsg("Solicitud enviada al soporte.");await load()}catch(e){setError(e instanceof Error?e.message:"No se pudo enviar la solicitud.");}finally{setSending(false)}}
 return <main className="module-page"><div className="module-hero"><div><span className="eyebrow">SOPORTE</span><h1>Centro de soporte</h1><p>Resolvé problemas de la plataforma y comunicáte con el soporte de AgroBrokerIA.</p></div></div>{error&&<div className="module-alert module-alert-error">{error}</div>}{msg&&<div className="module-alert">{msg}</div>}<section className="company-card"><h2>Contactá al soporte</h2><p>Correo: <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a></p><div className="settings-form-grid"><label>Tipo<select value={category} onChange={e=>setCategory(e.target.value)}><option value="PROBLEMA">Problema</option><option value="MANTENIMIENTO">Mantenimiento</option><option value="ACTUALIZACION">Actualización</option><option value="CONSULTA">Consulta</option></select></label><label>Prioridad<select value={priority} onChange={e=>setPriority(e.target.value)}><option>BAJA</option><option>MEDIA</option><option>ALTA</option><option>CRITICA</option></select></label><label>Asunto<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="¿Qué está ocurriendo?"/></label><label>Descripción<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={6} placeholder="Indicá el módulo, acción realizada y mensaje de error."/></label></div><button className="module-pill" onClick={send} disabled={sending}>{sending?"Enviando…":"Enviar solicitud"}</button></section><section className="company-card"><h2>Mis solicitudes</h2>{loading?<p>Cargando…</p>:tickets.length?tickets.map(t=><article key={t.id} className="support-ticket"><div><strong>{t.asunto}</strong><small>{t.categoria} · {t.prioridad} · {new Date(t.creado_at).toLocaleString("es-AR")}</small></div><span>{t.estado}</span><p>{t.descripcion}</p>{t.notas_admin&&<div><b>Respuesta del soporte:</b> {t.notas_admin}</div>}</article>):<p>No tenés solicitudes abiertas todavía.</p>}</section></main>;
}