"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase/client";

type Bank={id:string;empresa_id:string;nombre:string;titular:string|null;banco:string|null;cbu:string|null;alias:string|null;moneda_id:number|null;es_predeterminado:boolean;estado:string};
type Payment={id:string;operacion_id:string;importe:number;metodo_pago:string|null;estado:string|null;fecha_pago:string|null;creado_en:string};

const money=(n:number,c:string)=>`${c} ${Number(n||0).toLocaleString("en-US",{maximumFractionDigits:0})}`;
function Icon({name,size=22}:{name:string;size?:number}){const p:Record<string,React.ReactNode>={
 bank:<><path d="M3 10h18M4 10v8M8 10v8M12 10v8M16 10v8M20 10v8M2 20h20L12 3 2 20Z"/></>,
 dollar:<><circle cx="12" cy="12" r="9"/><path d="M12 5v14M15 8.5c-.7-.7-1.6-1-3-1-1.8 0-3 .9-3 2.1 0 3.2 6 1.2 6 4.2 0 1.2-1.2 2.1-3 2.1-1.4 0-2.5-.4-3.2-1.2"/></>,
 transfer:<><path d="M4 8h15M15 4l4 4-4 4M20 16H5M9 12l-4 4 4 4"/></>,
 clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
 search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
 dots:<><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></>,
 check:<><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></>,
 plus:<><path d="M12 5v14M5 12h14"/></>,
 trash:<><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14M10 11v6M14 11v6"/></>,
 edit:<><path d="m4 20 4-.9L19 8l-3-3L5 16l-1 4Z"/></>
};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]||p.bank}</svg>}

export default function CuentasBancariasPage(){
 const[banks,setBanks]=useState<Bank[]>([]),[payments,setPayments]=useState<Payment[]>([]),[currencies,setCurrencies]=useState<Record<number,string>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<Bank|null>(null),[query,setQuery]=useState(""),[open,setOpen]=useState(false);
 const[country,setCountry]=useState("Argentina"),[bankName,setBankName]=useState(""),[accountType,setAccountType]=useState("Cuenta corriente"),[holder,setHolder]=useState(""),[alias,setAlias]=useState(""),[currency,setCurrency]=useState(""),[cbu,setCbu]=useState("");
 async function load(){setLoading(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Necesitás iniciar sesión.");const{data:profile}=await supabase.from("profiles").select("active_company_id").eq("id",user.id).single();const companyId=profile?.active_company_id;if(!companyId)throw new Error("No se encontró una empresa activa.");const[{data:b,error:be},{data:m,error:me},{data:p,error:pe}]=await Promise.all([supabase.from("medios_cobro").select("id,empresa_id,nombre,titular,banco,cbu,alias,moneda_id,es_predeterminado,estado").eq("empresa_id",companyId).eq("tipo","BANCO").order("es_predeterminado",{ascending:false}),supabase.from("monedas").select("id,codigo,nombre").order("codigo"),supabase.from("pagos").select("id,operacion_id,importe,metodo_pago,estado,fecha_pago,creado_en").order("creado_en",{ascending:false}).limit(20)]);if(be)throw new Error(be.message);if(me)throw new Error(me.message);if(pe)throw new Error(pe.message);const mm=Object.fromEntries((m||[]).map((x:any)=>[x.id,x.codigo]));setBanks((b||[]) as Bank[]);setPayments((p||[]) as Payment[]);setCurrencies(mm);if(b?.length&&!selected)setSelected((b[0]) as Bank);if(!currency&&m?.length)setCurrency(String((m.find((x:any)=>x.codigo==="USD")||m[0]).id));}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar las cuentas.");}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>banks.filter(b=>[b.nombre,b.banco,b.titular,b.alias].join(" ").toLowerCase().includes(query.toLowerCase())),[banks,query]);
 const active=banks.filter(b=>/ACTIV|VERIFIC/i.test(b.estado)).length, pending=banks.filter(b=>/VERIFIC|PEND/i.test(b.estado)).length;
 const add=async()=>{if(!bankName||!holder||!currency){setError("Completá banco, titular y moneda.");return}try{const{data:{user}}=await supabase.auth.getUser();const{data:profile}=await supabase.from("profiles").select("active_company_id").eq("id",user!.id).single();const{data:id,error:e}=await supabase.rpc("crear_medio_cobro",{p_datos:{tipo:"BANCO",nombre:bankName,titular:holder,cuit_cuil:"",banco:bankName,cbu:cbu||null,alias:alias||null,moneda_id:Number(currency)}});if(e||!id)throw new Error(e?.message||"No se pudo crear la cuenta.");setOpen(false);setBankName("");setHolder("");setAlias("");setCbu("");await load()}catch(e){setError(e instanceof Error?e.message:"No se pudo crear la cuenta.")}};
 return <main className="bank-accounts-page">
  <header className="bank-accounts-hero"><div><h1>Cuentas bancarias</h1><p>Gestiona tus cuentas bancarias para recibir y realizar pagos de tus operaciones, comisiones y retiros.</p></div><button onClick={()=>setOpen(true)}><Icon name="plus" size={19}/> Agregar cuenta bancaria</button></header>
  <nav className="bank-tabs">{["Mis cuentas","Beneficiarios","Transferencias","Verificaciones","Límites","Historial","Configuración"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</nav>
  <section className="bank-kpis"><article className="bkp green"><span><Icon name="bank" size={26}/></span><div><small>Cuentas registradas</small><strong>{banks.length}</strong><em>{active} activas | {pending} en verificación</em></div></article><article className="bkp blue"><span><Icon name="dollar" size={26}/></span><div><small>Saldo total (referencial)</small><strong>—</strong><em>Saldo no sincronizado con el banco</em></div></article><article className="bkp amber"><span><Icon name="transfer" size={26}/></span><div><small>Pagos registrados</small><strong>{payments.length}</strong><em>Últimos registros disponibles</em></div></article><article className="bkp purple"><span><Icon name="clock" size={26}/></span><div><small>Verificaciones pendientes</small><strong>{pending}</strong><em>En proceso</em></div></article></section>
  {error&&<div className="bank-error">{error}</div>}
  <div className="bank-main-grid">
   <section className="bank-list-panel"><div className="bank-list-head"><h2>Mis cuentas bancarias</h2><label><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cuentas..."/></label><select><option>Todos los países</option></select></div><table><thead><tr><th>Banco</th><th>Titular / Alias</th><th>Tipo de cuenta</th><th>Moneda</th><th>Número / IBAN</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="bank-loading">Cargando cuentas…</td></tr>:filtered.map(b=><tr key={b.id} onClick={()=>setSelected(b)} className={selected?.id===b.id?"selected":""}><td><span className="bank-brand">{b.banco?.slice(0,2)||"▣"}</span><b>{b.banco||b.nombre}</b><small>Argentina</small></td><td><b>{b.titular||"—"}</b><small>{b.alias||"Cuenta principal"}</small></td><td>Cuenta corriente</td><td>{currencies[b.moneda_id||0]||"USD"}</td><td>**** {b.cbu?.slice(-4)||"—"}</td><td><span className={"bank-status "+(/ACTIV/i.test(b.estado)?"ok":/VERIFIC/i.test(b.estado)?"warn":"bad")}>{/ACTIV/i.test(b.estado)?"Activa":/VERIFIC/i.test(b.estado)?"En verificación":"Inactiva"}</span></td><td><button className="bank-dots" onClick={e=>{e.stopPropagation();setSelected(b)}}><Icon name="dots" size={16}/></button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={7} className="bank-loading">No hay cuentas bancarias registradas.</td></tr>}</tbody></table></section>
   <aside className="bank-detail"><h2>Detalle de cuenta</h2>{selected?<><div className="bank-detail-brand"><span className="bank-brand large">{selected.banco?.slice(0,2)||"▣"}</span><div><b>{selected.banco||selected.nombre}</b><small>🇦🇷 Argentina</small></div><span className={"bank-status "+(/ACTIV/i.test(selected.estado)?"ok":/VERIFIC/i.test(selected.estado)?"warn":"bad")}>{/ACTIV/i.test(selected.estado)?"Activa":/VERIFIC/i.test(selected.estado)?"En verificación":"Inactiva"}</span></div><dl><div><dt>Titular</dt><dd>{selected.titular||"—"}</dd></div><div><dt>Alias</dt><dd>{selected.alias||"Cuenta principal"}</dd></div><div><dt>Tipo de cuenta</dt><dd>Cuenta corriente</dd></div><div><dt>Moneda</dt><dd>{currencies[selected.moneda_id||0]||"USD"} - Moneda</dd></div><div><dt>CBU</dt><dd>{selected.cbu||"—"}</dd></div><div><dt>Número de cuenta</dt><dd>{selected.cbu?.slice(-8)||"—"}</dd></div></dl><div className="bank-detail-actions"><button><Icon name="edit" size={16}/> Editar</button><button><Icon name="trash" size={16}/> Eliminar</button></div></>:<p className="bank-empty">Seleccioná una cuenta.</p>}</aside>
  </div>
  <div className="bank-bottom-grid"><section className="bank-form-panel"><h2>Agregar nueva cuenta bancaria</h2><div className="bank-steps"><b>1</b> Datos del banco <i/> <b>2</b> Información de la cuenta <i/> <b>3</b> Verificación</div><div className="bank-form-grid"><label>País del banco<select value={country} onChange={e=>setCountry(e.target.value)}><option>Argentina</option><option>Estados Unidos</option><option>Brasil</option><option>Alemania</option></select></label><label>Banco<input value={bankName} onChange={e=>setBankName(e.target.value)} placeholder="Banco Santander"/></label><label>Tipo de cuenta<select value={accountType} onChange={e=>setAccountType(e.target.value)}><option>Cuenta corriente</option><option>Caja de ahorro</option></select></label><label>Titular de la cuenta<input value={holder} onChange={e=>setHolder(e.target.value)} placeholder="Titular"/></label><label>Alias (opcional)<input value={alias} onChange={e=>setAlias(e.target.value)} placeholder="Ej. Cuenta principal"/></label><label>Moneda<select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="">Seleccionar</option>{Object.entries(currencies).map(([id,c])=><option value={id} key={id}>{c}</option>)}</select></label><label className="wide">CBU / IBAN<input value={cbu} onChange={e=>setCbu(e.target.value)} placeholder="Ingresá CBU o IBAN"/></label></div><button className="bank-continue" onClick={add}>Continuar →</button></section><section className="bank-transfer-panel"><h2>Últimos pagos <button>Ver todos</button></h2>{payments.length?payments.slice(0,5).map(p=><div className="transfer-row" key={p.id}><span className="in"><Icon name="transfer" size={18}/></span><div><b>{p.metodo_pago||"Pago registrado"}</b><small>{new Date(p.fecha_pago||p.creado_en).toLocaleString("es-AR")}</small></div><strong className="positive">{money(Number(p.importe||0),currencies[0]||"USD")}</strong><em>{p.estado||"Registrado"}</em></div>):<div className="bank-empty">No hay pagos registrados todavía.</div>}</section><section className="bank-verify-panel"><h2>Estado de la cuenta</h2>{[["Cuenta registrada",!!selected],["Banco informado",!!selected?.banco],["Titular informado",!!selected?.titular],["KYC",false]].map(([x,ok])=><div key={String(x)}><span>{ok?"✓":"○"}</span><b>{String(x)}</b><em className={ok?"":"pending"}>{ok?"Disponible":"No disponible"}</em></div>)}<p>ⓘ La plataforma no marca una verificación bancaria como completada sin evidencia de un proceso real.</p></section></div>
  {open&&<div className="bank-modal"><div><button className="bank-modal-close" onClick={()=>setOpen(false)}>×</button><h2>Agregar cuenta bancaria</h2><p>Completá los datos para registrar una nueva cuenta.</p><div className="bank-form-grid"><label>Banco<input value={bankName} onChange={e=>setBankName(e.target.value)}/></label><label>Titular<input value={holder} onChange={e=>setHolder(e.target.value)}/></label><label>Moneda<select value={currency} onChange={e=>setCurrency(e.target.value)}>{Object.entries(currencies).map(([id,c])=><option value={id} key={id}>{c}</option>)}</select></label><label>CBU / IBAN<input value={cbu} onChange={e=>setCbu(e.target.value)}/></label></div><button className="bank-continue" onClick={add}>Guardar cuenta</button></div></div>}
 </main>
}
