"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase/client";

type C={id:string;operacion_id:string;numero_contrato:string;tipo_contrato:string|null;estado:string;fecha_firma:string|null;cantidad_tn:number|null;precio_tn:number|null;importe_total:number|null;contenido:string|null};
type V={id:string;contrato_id:string;version:number;estado:string;motivo:string|null;documento_hash:string|null;creado_en:string};
export default function ContratosPage(){
 const [rows,setRows]=useState<C[]>([]),[versions,setVersions]=useState<V[]>([]),[selected,setSelected]=useState(""),[motivo,setMotivo]=useState("Nueva versión contractual"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 async function load(){setLoading(true);const [{data:c,error:ce},{data:v,error:ve}]=await Promise.all([supabase.from("contratos").select("id,operacion_id,numero_contrato,tipo_contrato,estado,fecha_firma,cantidad_tn,precio_tn,importe_total,contenido").order("creado_en",{ascending:false}),supabase.from("contrato_versiones").select("id,contrato_id,version,estado,motivo,documento_hash,creado_en").order("creado_en",{ascending:false})]);if(ce||ve)setErr((ce||ve)?.message||"Error");setRows((c||[]) as C[]);setVersions((v||[]) as V[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function docx(id:string){setBusy(true);setErr("");try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Sesión expirada.");const r=await fetch("/api/contratos/docx",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({contractId:id})});if(!r.ok)throw new Error((await r.json()).error||"No se pudo generar DOCX");const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Contrato.docx";a.click();URL.revokeObjectURL(url);setMsg("DOCX profesional generado desde el contrato autorizado.")}catch(e){setErr(e instanceof Error?e.message:"Error") }finally{setBusy(false)}}
 async function version(id:string){setBusy(true);setErr("");try{const c=rows.find(x=>x.id===id);if(!c?.contenido)throw new Error("El contrato no tiene contenido.");const {data,error}=await supabase.rpc("crear_version_contrato",{p_contrato_id:id,p_motivo:motivo,p_contenido:c.contenido,p_estado:"BORRADOR"});if(error)throw new Error(error.message);setMsg("Versión "+String(data).slice(0,8)+" creada y hasheada.");await load()}catch(e){setErr(e instanceof Error?e.message:"Error") }finally{setBusy(false)}}
 return <main className="module-page"><div className="module-hero"><div><span className="eyebrow">LEGAL / CONTRACTUAL</span><h1>Contratos</h1><p>Contratos, versiones, hashes y documentos generados a partir de contenido contractual existente.</p></div><div className="module-pill">{rows.length} contratos</div></div>
 {err&&<div className="module-alert module-alert-error">{err}</div>}{msg&&<div className="module-alert">{msg}</div>}
 <section className="document-section"><div className="document-section-head"><div><span className="eyebrow">VERSIONADO</span><h2>Historial de versiones</h2></div><input placeholder="Motivo de nueva versión" value={motivo} onChange={e=>setMotivo(e.target.value)} style={{maxWidth:360}}/></div>
 {loading?<div className="loading-card">Cargando…</div>:<div className="document-grid">{rows.map(c=><article className="document-card" key={c.id}><div className="document-icon">C</div><div><strong>{c.numero_contrato}</strong><p>{c.tipo_contrato||"Contrato comercial"} · {c.estado}</p><small>Operación {c.operacion_id.slice(0,8)} · {c.cantidad_tn||0} TN · {c.importe_total||0}</small><small>{versions.filter(v=>v.contrato_id===c.id).length} versiones registradas</small></div><button disabled={busy} onClick={()=>docx(c.id)}>Word</button><button disabled={busy||c.estado==="CONFIRMADO"} onClick={()=>version(c.id)}>Nueva versión</button></article>)}</div>}
 </section>
 <section className="document-section"><div className="document-section-head"><div><span className="eyebrow">EVIDENCIA</span><h2>Versiones</h2></div></div><div className="document-grid">{versions.map(v=><article className="document-card" key={v.id}><div className="document-icon">V</div><div><strong>v{v.version}</strong><p>{v.estado} · {v.motivo||"Sin motivo"}</p><small>{v.documento_hash||"Sin hash"} · {new Date(v.creado_en).toLocaleString("es-AR")}</small></div></article>)}</div></section>
 </main>
}