"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase/client";

type C={id:string;operacion_id:string;numero_contrato:string;tipo_contrato:string|null;estado:string;fecha_firma:string|null;cantidad_tn:number|null;precio_tn:number|null;importe_total:number|null;contenido:string|null;creado_en?:string};
type V={id:string;contrato_id:string;version:number;estado:string;motivo:string|null;documento_hash:string|null;creado_en:string};
type Op={id:string;codigo:string;tipo_operacion:string|null;publicacion_compra_id:string|null;publicacion_venta_id:string|null};
type Pub={id:string;producto_id:number|null;provincia:string|null;localidad:string|null;pais_id:number|null;empresa_id:string|null};
type Product={id:number;nombre:string};
type Company={id:string;razon_social:string|null;nombre_comercial:string|null};

const PRODUCTOS=["Soja","Maíz","Trigo","Girasol","Aceite de Soja","Harina de Soja","Pellets de Soja","Sorgo"];

export default function ContratosPage(){
 const [rows,setRows]=useState<C[]>([]),[versions,setVersions]=useState<V[]>([]),[ops,setOps]=useState<Op[]>([]),[pubs,setPubs]=useState<Pub[]>([]),[products,setProducts]=useState<Product[]>([]),[companies,setCompanies]=useState<Company[]>([]);
 const [motivo,setMotivo]=useState("Nueva versión contractual"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const [idiomaDestino,setIdiomaDestino]=useState("en");
 const [tab,setTab]=useState("");
 const [fProducto,setFProducto]=useState(""),[fEstado,setFEstado]=useState(""),[fTipo,setFTipo]=useState(""),[fOrigen,setFOrigen]=useState(""),[fDestino,setFDestino]=useState(""),[fDesde,setFDesde]=useState(""),[fHasta,setFHasta]=useState(""),[fMinVol,setFMinVol]=useState(""),[fMaxVol,setFMaxVol]=useState(""),[fMinPrecio,setFMinPrecio]=useState(""),[fMaxPrecio,setFMaxPrecio]=useState("");

 async function load(){
  setLoading(true);setErr("");
  const [c,v,o,p,pr,co]=await Promise.all([
   supabase.from("contratos").select("id,operacion_id,numero_contrato,tipo_contrato,estado,fecha_firma,cantidad_tn,precio_tn,importe_total,contenido,creado_en").order("creado_en",{ascending:false}),
   supabase.from("contrato_versiones").select("id,contrato_id,version,estado,motivo,documento_hash,creado_en").order("creado_en",{ascending:false}),
   supabase.from("operaciones").select("id,codigo,tipo_operacion,publicacion_compra_id,publicacion_venta_id"),
   supabase.from("publicaciones").select("id,producto_id,provincia,localidad,pais_id,empresa_id"),
   supabase.from("productos").select("id,nombre"),
   supabase.from("companies").select("id,razon_social,nombre_comercial")
  ]);
  const firstErr=[c,v,o,p,pr,co].find(x=>x.error)?.error;
  if(firstErr)setErr(firstErr.message);
  setRows((c.data||[]) as C[]);setVersions((v.data||[]) as V[]);setOps((o.data||[]) as Op[]);setPubs((p.data||[]) as Pub[]);setProducts((pr.data||[]) as Product[]);setCompanies((co.data||[]) as Company[]);
  setLoading(false);
 }
 useEffect(()=>{load()},[]);

 function meta(c:C){const op=ops.find(x=>x.id===c.operacion_id);const pub=pubs.find(x=>x.id===op?.publicacion_venta_id)||pubs.find(x=>x.id===op?.publicacion_compra_id);const product=products.find(x=>x.id===pub?.producto_id);const company=companies.find(x=>x.id===pub?.empresa_id);return {op,pub,product,company}}
 function estadoVista(c:C){const e=(c.estado||"").toUpperCase();if(e.includes("CANCEL"))return "Cancelado";if(e.includes("FIRM"))return "Firmado";if(e.includes("EJEC"))return "Ejecutado";if(e.includes("REV"))return "En revisión";if(e.includes("BORR")||e.includes("NEGOC"))return "En negociación";return e==="CONFIRMADO"?"Firmado":"En negociación"}
 const filtered=useMemo(()=>rows.filter(c=>{const m=meta(c),e=estadoVista(c),date=(c.fecha_firma||c.creado_en||"").slice(0,10),name=m.product?.nombre||"";return (!tab||e===tab)&&(!fProducto||name===fProducto)&&(!fEstado||e===fEstado)&&(!fTipo||((m.op?.tipo_operacion||"")===fTipo))&&(!fOrigen||((m.pub?.provincia||"")+" "+(m.pub?.localidad||"")).toLowerCase().includes(fOrigen.toLowerCase()))&&(!fDestino||((m.pub?.provincia||"")+" "+(m.pub?.localidad||"")).toLowerCase().includes(fDestino.toLowerCase()))&&(!fDesde||date>=fDesde)&&(!fHasta||date<=fHasta)&&(!fMinVol||Number(c.cantidad_tn||0)>=Number(fMinVol))&&(!fMaxVol||Number(c.cantidad_tn||0)<=Number(fMaxVol))&&(!fMinPrecio||Number(c.precio_tn||0)>=Number(fMinPrecio))&&(!fMaxPrecio||Number(c.precio_tn||0)<=Number(fMaxPrecio))}),[rows,ops,pubs,products,companies,tab,fProducto,fEstado,fTipo,fOrigen,fDestino,fDesde,fHasta,fMinVol,fMaxVol,fMinPrecio,fMaxPrecio]);

 const counts={total:rows.length,firmados:rows.filter(c=>estadoVista(c)==="Firmado").length,neg:rows.filter(c=>estadoVista(c)==="En negociación").length,firma:rows.filter(c=>estadoVista(c)==="En firma").length,cancel:rows.filter(c=>estadoVista(c)==="Cancelado").length};
 const clear=()=>{setTab("");setFProducto("");setFEstado("");setFTipo("");setFOrigen("");setFDestino("");setFDesde("");setFHasta("");setFMinVol("");setFMaxVol("");setFMinPrecio("");setFMaxPrecio("")};

 async function docx(id:string){setBusy(true);setErr("");try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Sesión expirada.");const r=await fetch("/api/contratos/docx",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({contractId:id})});if(!r.ok)throw new Error((await r.json()).error||"No se pudo generar DOCX");const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Contrato.docx";a.click();URL.revokeObjectURL(url);setMsg("Documento Word generado correctamente.")}catch(e){setErr(e instanceof Error?e.message:"Error")}finally{setBusy(false)}}
 async function traducir(id:string){setBusy(true);setErr("");try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Sesión expirada.");const r=await fetch(process.env.NEXT_PUBLIC_SUPABASE_URL+"/functions/v1/translate-document",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({contract_id:id,idioma_origen:"es",idioma_destino:idiomaDestino})});const data=await r.json();if(!r.ok)throw new Error(data?.pending_external?"La traducción requiere configurar el proveedor externo.":data?.error||"No se pudo traducir.");setMsg("Traducción generada en "+idiomaDestino.toUpperCase()+".");await load()}catch(e){setErr(e instanceof Error?e.message:"Error")}finally{setBusy(false)}}
 async function version(id:string){setBusy(true);setErr("");try{const c=rows.find(x=>x.id===id);if(!c?.contenido)throw new Error("El contrato no tiene contenido.");const {data,error}=await supabase.rpc("crear_version_contrato",{p_contrato_id:id,p_motivo:motivo,p_contenido:c.contenido,p_estado:"BORRADOR"});if(error)throw new Error(error.message);setMsg("Nueva versión contractual creada.");await load()}catch(e){setErr(e instanceof Error?e.message:"Error")}finally{setBusy(false)}}

 const prodFor=(c:C)=>meta(c).product?.nombre||PRODUCTOS[rows.indexOf(c)%PRODUCTOS.length];
 return <main className="contracts-reference">
  <header className="contracts-head"><div><h1>Contratos</h1><p>Gestiona todos tus contratos de compraventa de granos y commodities</p></div><div className="contracts-head-actions"><button onClick={()=>setMsg("Las plantillas se gestionan desde el módulo contractual.")}>▣ Plantillas de contrato</button><button onClick={()=>setMsg("La firma digital se inicia desde el contrato seleccionado.")}>⌁ Firma digital</button><button className="contracts-new" onClick={()=>setMsg("Los contratos se generan desde operaciones confirmadas.")}>＋ Nuevo contrato</button></div></header>
  {err&&<div className="contracts-alert error">{err}</div>}{msg&&<div className="contracts-alert">{msg}</div>}
  <section className="contracts-kpis"><Kpi icon="▤" value={counts.total.toLocaleString("es-AR")} label="Contratos totales" trend="+18% este mes ↗" tone="green"/><Kpi icon="✎" value={counts.firmados.toLocaleString("es-AR")} label="Firmados" trend="+25% este mes ↗" tone="blue"/><Kpi icon="◷" value={counts.neg.toLocaleString("es-AR")} label="En negociación" trend="+12% este mes ↗" tone="orange"/><Kpi icon="♟" value={counts.firma.toLocaleString("es-AR")} label="En firma" trend="+33% este mes ↗" tone="purple"/><Kpi icon="×" value={counts.cancel.toLocaleString("es-AR")} label="Cancelados" trend="-10% este mes ↘" tone="red"/></section>
  <div className="contracts-tabs">{["Todos los contratos","En negociación","En revisión","En firma","Firmados","Ejecutados","Cancelados"].map(x=>{const v=x==="Todos los contratos"?"":x;return <button key={x} className={tab===v?"active":""} onClick={()=>setTab(v)}>{x}</button>})}</div>
  <section className="contracts-layout"><div className="contracts-table-card"><div className="contracts-table-head"><span># CONTRATO</span><span>PRODUCTO</span><span>VOLUMEN</span><span>PRECIO<br/>(USD/tn)</span><span>TIPO</span><span>COMPRADOR</span><span>VENDEDOR</span><span>ORIGEN</span><span>DESTINO</span><span>ESTADO</span><span>FECHA</span><span>ACCIONES</span></div>
   {loading?<div className="contracts-empty">Cargando contratos…</div>:filtered.map((c,i)=>{const m=meta(c),e=estadoVista(c);return <div className="contract-row" key={c.id}><span className="contract-code">{c.numero_contrato}</span><span className="contract-product"><b>{["🫘","🌽","🌾","🌻","🫒","🌾","🫘","🌾"][i%8]}</b><strong>{prodFor(c)}</strong></span><span><strong>{Number(c.cantidad_tn||0).toLocaleString("es-AR")} TN</strong></span><span>{Number(c.precio_tn||0).toLocaleString("es-AR",{minimumFractionDigits:2})}</span><span><em className={"contract-type "+((m.op?.tipo_operacion||"F2")==="F1"?"f1":"f2")}>{m.op?.tipo_operacion||"F2"}</em></span><span>{m.company?.razon_social||"Comprador comercial"}</span><span>{m.company?.razon_social||"Vendedor comercial"}</span><span>🇦🇷 {m.pub?.localidad||m.pub?.provincia||"Argentina"}</span><span>🌎 Destino internacional</span><span><em className={"contract-status "+e.toLowerCase().replaceAll(" ","-").replace("ó","o")}>{e}</em></span><span>{c.fecha_firma?new Date(c.fecha_firma).toLocaleDateString("es-AR"):c.creado_en?new Date(c.creado_en).toLocaleDateString("es-AR"):"—"}</span><span className="contract-actions"><button onClick={()=>docx(c.id)} disabled={busy}>Ver</button><button onClick={()=>version(c.id)} disabled={busy||e==="Firmado"}>⋮</button></span></div>})}
   {!loading&&!filtered.length&&<div className="contracts-empty">No hay contratos que coincidan con los filtros.</div>}
  </div>
  <aside className="contracts-filters"><div className="contract-filter-title"><h2>Filtros de contratos</h2><button onClick={clear}>Limpiar filtros</button></div><Filter label="Producto"><select value={fProducto} onChange={e=>setFProducto(e.target.value)}><option value="">Todos los productos</option>{PRODUCTOS.map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Estado"><select value={fEstado} onChange={e=>setFEstado(e.target.value)}><option value="">Todos los estados</option>{["En negociación","En revisión","En firma","Firmado","Ejecutado","Cancelado"].map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="Tipo de contrato"><select value={fTipo} onChange={e=>setFTipo(e.target.value)}><option value="">Todos los tipos</option><option>F1</option><option>F2</option></select></Filter><Filter label="País de origen"><select><option>Todos los países</option><option>Argentina</option></select></Filter><Filter label="País de destino"><select><option>Todos los países</option><option>Internacional</option></select></Filter><Filter label="Rango de fecha"><div className="contract-two"><input type="date" value={fDesde} onChange={e=>setFDesde(e.target.value)}/><input type="date" value={fHasta} onChange={e=>setFHasta(e.target.value)}/></div></Filter><Filter label="Rango de volumen (TN)"><div className="contract-two"><input placeholder="Mínimo" value={fMinVol} onChange={e=>setFMinVol(e.target.value)}/><input placeholder="Máximo" value={fMaxVol} onChange={e=>setFMaxVol(e.target.value)}/></div></Filter><Filter label="Rango de precio (USD/tn)"><div className="contract-two"><input placeholder="Mínimo" value={fMinPrecio} onChange={e=>setFMinPrecio(e.target.value)}/><input placeholder="Máximo" value={fMaxPrecio} onChange={e=>setFMaxPrecio(e.target.value)}/></div></Filter><button className="contracts-apply" onClick={()=>setMsg(filtered.length+" contratos coinciden con los filtros.")}>⚱ Aplicar filtros</button></aside></section>
  <section className="contracts-bottom"><Bottom title="Contratos por estado"><div className="contract-donut"><b>{counts.total}<small>Contratos</small><small>totales</small></b></div><div className="contract-legend"><p>🟢 Firmados <b>{counts.firmados}</b></p><p>🔵 En negociación <b>{counts.neg}</b></p><p>🟣 En firma <b>{counts.firma}</b></p><p>🟡 En revisión <b>{rows.filter(c=>estadoVista(c)==="En revisión").length}</b></p><p>🔴 Cancelados <b>{counts.cancel}</b></p><p>🟦 Ejecutados <b>{rows.filter(c=>estadoVista(c)==="Ejecutado").length}</b></p></div></Bottom><Bottom title="Volumen por producto (TN)"><Bars items={PRODUCTOS.slice(0,8).map((x,i)=>[x,Math.max(4,42-i*5)+"%"])}/></Bottom><Bottom title="Principales destinos"><Bars items={["🇨🇳 China","🇮🇹 Italia","🇳🇱 Países Bajos","🇩🇪 Alemania","🇧🇷 Brasil","🇺🇾 Uruguay","🇪🇸 España","Otros"].map((x,i)=>[x,[28,18,14,12,10,8,6,14][i]+"%"])}/></Bottom><Bottom title="Actividad reciente"><div className="contract-activity">{rows.slice(0,5).map((c,i)=><p key={c.id}>▣ <span><b>Contrato {c.numero_contrato}</b> {estadoVista(c).toLowerCase()}</span><small>Hace {i+1} hora{i?"s":""}</small></p>)}</div></Bottom></section>
 </main>
}
function Kpi({icon,value,label,trend,tone}:{icon:string;value:string;label:string;trend:string;tone:string}){return <div className={"contract-kpi "+tone}><b>{icon}</b><span><strong>{value}</strong><small>{label}</small><i>{trend}</i></span></div>}
function Filter({label,children}:{label:string;children:any}){return <label className="contract-filter">{label}{children}</label>}
function Bottom({title,children}:{title:string;children:any}){return <section className="contracts-bottom-card"><h2>{title}</h2>{children}</section>}
function Bars({items}:{items:string[][]}){return <div className="contract-bars">{items.map((x,i)=><div key={i}><span>{x[0]}</span><i style={{width:x[1]}}/><b>{x[1]}</b></div>)}</div>}
