import { createClient } from "https://esm.sh/@supabase/supabase-js@2.112.1";
const URL = Deno.env.get("SUPABASE_URL")!;
const ANON = Deno.env.get("SUPABASE_ANON_KEY")!;
const SERVICE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(URL, SERVICE);
const BCR_LOCAL = "https://www.bcr.com.ar/es/mercados/mercado-de-granos/cotizaciones/cotizaciones-locales-0";
const BCR_FOB = "https://www.bcr.com.ar/es/mercados/mercado-de-granos/cotizaciones/cotizaciones-locales-1";
const SOURCE = "BCR/CAC";
const norm=(s:string)=>s.replace(/\s+/g," ").trim();
function num(s:string){const r=norm(s).replace(/[$u\\$s\\/tn]/gi,"").trim();if(!r||/^(S\/C|—|-)$/.test(r))return null;const m=r.match(/-?\d[\d.]*,?\d*/);if(!m)return null;const t=m[0],n=t.includes(",")?Number(t.replace(/\./g,"").replace(",",".")):Number(t.replace(/,/g,""));return Number.isFinite(n)?n:null}
function dateFromText(s:string){const m=norm(s).match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?m[3]+"-"+m[2]+"-"+m[1]:null}
function code(s:string){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase()}
async function commodityId(name:string){const {data}=await db.from("commodities").select("id").eq("codigo",code(name)).maybeSingle();return data?.id??null}
async function save(q:any){const fp=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(q)));q.fingerprint=Array.from(new Uint8Array(fp)).map(b=>b.toString(16).padStart(2,"0")).join("");const {error}=await db.from("market_quotes").upsert(q,{onConflict:"fingerprint",ignoreDuplicates:true});if(error)throw error;return 1}
async function html(url:string){const r=await fetch(url,{headers:{"user-agent":"AgroBrokerIA MarketDataService/2.0"}});if(!r.ok)throw new Error("BCR_HTTP_"+r.status);return await r.text()}
async function authorized(req:Request){const cron=Deno.env.get("CRON_SECRET"),a=req.headers.get("authorization");if(cron&&a==="Bearer "+cron)return true;if(!a?.startsWith("Bearer "))return false;const c=createClient(URL,ANON,{global:{headers:{Authorization:a}}});const {data:{user}}=await c.auth.getUser();return !!user}
async function parseLocal(body:string,runId:string){const d=new DOMParser().parseFromString(body,"text/html");if(!d)throw new Error("BCR_HTML_PARSE_ERROR");const rows=Array.from(d.querySelectorAll("tr"));let dates:string[]=[],saved=0;for(const tr of rows){const cells=Array.from(tr.querySelectorAll("th,td")).map(x=>norm(x.textContent||""));if(cells.some(x=>/Fecha Negociación/i.test(x))){dates=cells.map(dateFromText).filter((x):x is string=>!!x);continue}const idx=cells.findIndex(x=>/^(Soja|Ma[ií]z|Trigo|Girasol|Sorgo)$/i.test(x));if(idx<0||!dates.length)continue;const commodity=cells[idx],id=await commodityId(commodity),values=cells.slice(idx+1),value=num(values[0]),prev=num(values[1]);if(value==null)continue;saved+=await save({source:SOURCE,source_reference:BCR_LOCAL,market_date:dates[0],published_at:null,commodity_id:id,product_id:null,variety:null,position:"SPOT",market:"ROSARIO",port:"ROSARIO",price_type:"PIZARRA_CAC",price:value,currency:"ARS",unit:"T",status:"VALID",freshness:"UPDATED",previous_value:prev,variation:value!==null&&prev!==null?value-prev:null,payload:{commodity,dates,raw_cells:cells,run_id:runId}})}return saved}
async function parseFob(body:string,runId:string){const d=new DOMParser().parseFromString(body,"text/html");if(!d)throw new Error("BCR_HTML_PARSE_ERROR");const rows=Array.from(d.querySelectorAll("tr"));let commodity="",delivery:string[]=[],marketDate:string|null=null,saved=0;for(const tr of rows){const cells=Array.from(tr.querySelectorAll("th,td")).map(x=>norm(x.textContent||""));if(!cells.length)continue;const text=cells.join(" | "),ds=text.match(/\d{2}\/\d{2}\/\d{4}/);if(ds)marketDate=dateFromText(ds[0])||marketDate;const cm=cells.find(x=>/^(Trigo|Ma[ií]z|Soja|Girasol|Sorgo)$/i.test(x));if(cm){commodity=cm;delivery=[];continue}if(/^Fecha Embarque\/Delivery date/i.test(cells[0]||"")){delivery=cells.slice(1);continue}if(!commodity||!marketDate)continue;const metric=cells[0]||"";let type:string|null=null;if(/^FOB comprador/i.test(metric))type="FOB_BID";else if(/^FOB vendedor/i.test(metric))type="FOB_OFFER";else if(/^a\) Impuestos/i.test(metric))type="EXPORT_DUTIES";else if(/^b\) Gastos en puertos/i.test(metric))type="PORT_COST";else if(/^c\) Gtos/i.test(metric))type="MARKETING_COST";else if(/^Total USD/i.test(metric))type="TOTAL_COST";else if(/^FAS Te[oó]rico/i.test(metric))type="FAS_THEORETICAL";if(!type)continue;const id=await commodityId(commodity);for(let i=1;i<cells.length;i++){const value=num(cells[i]);if(value==null)continue;saved+=await save({source:SOURCE,source_reference:BCR_FOB,market_date:marketDate,published_at:null,commodity_id:id,product_id:null,variety:null,position:delivery[i-1]||"SPOT",market:"ARGENTINA",port:"SAGyP/UP RIVER",price_type:type,price:value,currency:"USD",unit:"T",status:"VALID",freshness:"UPDATED",previous_value:null,variation:null,payload:{commodity,metric:type,delivery:delivery[i-1]||null,raw_cells:cells,run_id:runId}})}}return saved}
Deno.serve(async req=>{let runId:string|null=null;try{if(!(await authorized(req)))return new Response(JSON.stringify({error:"AUTH_REQUIRED"}),{status:401,headers:{"content-type":"application/json"}});const {data:run,error:re}=await db.from("market_sync_runs").insert({source:SOURCE,status:"RUNNING"}).select("id").single();if(re)throw re;runId=run.id;const [local,fob]=await Promise.all([html(BCR_LOCAL),html(BCR_FOB)]),[a,b]=await Promise.all([parseLocal(local,runId),parseFob(fob,runId)]),total=a+b;if(total===0)throw new Error("BCR_NO_QUOTES_PARSED");await db.from("market_sync_runs").update({finished_at:new Date().toISOString(),status:"SUCCESS",records_seen:total,records_saved:total}).eq("id",runId);return new Response(JSON.stringify({ok:true,source:SOURCE,run_id:runId,records_saved:total}),{headers:{"content-type":"application/json"}})}catch(e){const msg=e instanceof Error?e.message:"MARKET_SYNC_ERROR";if(runId)await db.from("market_sync_runs").update({finished_at:new Date().toISOString(),status:"ERROR",error_code:msg.slice(0,80),error_message:msg}).eq("id",runId);return new Response(JSON.stringify({ok:false,error:msg,run_id:runId}),{status:502,headers:{"content-type":"application/json"}})}});
