import { createClient } from "https://esm.sh/@supabase/supabase-js@2.112.1";
const URL=Deno.env.get("SUPABASE_URL")!, ANON=Deno.env.get("SUPABASE_ANON_KEY")!, SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(URL,SERVICE);
const BCR_LOCAL="https://www.bcr.com.ar/es/mercados/mercado-de-granos/cotizaciones/cotizaciones-locales-0";
const BCR_FOB="https://www.bcr.com.ar/es/mercados/mercado-de-granos/cotizaciones/cotizaciones-locales-1";
const SOURCE="BCR/CAC";
function norm(s:string){return s.replace(/\s+/g," ").trim()}
function num(s:string){const m=norm(s).replace(/[$u\$s\/tn]/gi,"").match(/-?\d[\d.]*,?\d*/);if(!m)return null;const x=m[0].includes(",")?m[0].replace(/\./g,"").replace(",","."):m[0].replace(/,/g,"");const n=Number(x);return Number.isFinite(n)?n:null}
function dateFromText(s:string){const m=norm(s).match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?m[3]+"-"+m[2]+"-"+m[1]:null}
async function html(url:string){const r=await fetch(url,{headers:{"user-agent":"AgroBrokerIA MarketDataService/1.0"}});if(!r.ok)throw new Error("BCR_HTTP_"+r.status);return await r.text()}
async function auth(req:Request){const cron=Deno.env.get("CRON_SECRET");const a=req.headers.get("authorization");if(cron&&a==="Bearer "+cron)return true;if(!a?.startsWith("Bearer "))return false;const c=createClient(URL,ANON,{global:{headers:{Authorization:a}}});const {data:{user}}=await c.auth.getUser();return !!user}
async function save(q:any){const fp=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(q)));q.fingerprint=Array.from(new Uint8Array(fp)).map(x=>x.toString(16).padStart(2,"0")).join("");const {error}=await db.from("market_quotes").upsert(q,{onConflict:"fingerprint",ignoreDuplicates:true});if(error)throw error;return 1}
async function parseLocal(body:string,runId:string){const d=new DOMParser().parseFromString(body,"text/html");if(!d)throw new Error("BCR_HTML_PARSE_ERROR");const rows=Array.from(d.querySelectorAll("tr"));let marketDate:string|null=null,saved=0;for(const tr of rows){const cells=Array.from(tr.querySelectorAll("th,td")).map(x=>norm(x.textContent||""));const text=cells.join(" | ");if(/Fecha Negociación/i.test(text)){const ds=text.match(/\d{2}\/\d{2}\/\d{4}/);if(ds)marketDate=dateFromText(ds[0]);}const commodity=cells.find(x=>/^(Soja|Ma[ií]z|Trigo|Girasol|Sorgo)$/i.test(x));if(!commodity||!marketDate)continue;const idx=cells.findIndex(x=>x===commodity);const value=cells.slice(idx+1).map(num).find(x=>x!==null);if(value===null||value===undefined)continue;const code=commodity.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();const {data:com}=await db.from("commodities").select("id").eq("codigo",code).maybeSingle();saved+=await save({source:SOURCE,source_reference:BCR_LOCAL,market_date:marketDate,published_at:null,commodity_id:com?.id||null,product_id:null,variety:null,position:"SPOT",market:"ROSARIO",port:"ROSARIO",price_type:"PIZARRA_CAC",price:value,currency:"ARS",unit:"T",status:"VALID",freshness:"UPDATED",previous_value:null,variation:null,payload:{commodity,raw_cells:cells,run_id:runId}})}return saved}
async function parseFob(body:string,runId:string){const d=new DOMParser().parseFromString(body,"text/html");if(!d)throw new Error("BCR_HTML_PARSE_ERROR");const rows=Array.from(d.querySelectorAll("tr"));let commodity="";let marketDate:string|null=null,saved=0;for(const tr of rows){const cells=Array.from(tr.querySelectorAll("th,td")).map(x=>norm(x.textContent||""));const text=cells.join(" | ");const ds=text.match(/\d{2}\/\d{2}\/\d{4}/);if(ds)marketDate=dateFromText(ds[0])||marketDate;const cm=cells.find(x=>/^(Trigo|Ma[ií]z|Soja)$/i.test(x));if(cm){commodity=cm;continue}if(!commodity||!marketDate)continue;const first=cells.slice(1).map(num).find(x=>x!==null);if(first===null||first===undefined)continue;let type:string|null=null;if(/^FOB comprador/i.test(cells[0]||""))type="FOB_BID";else if(/^FOB vendedor/i.test(cells[0]||""))type="FOB_OFFER";else if(/^a\) Impuestos/i.test(cells[0]||""))type="EXPORT_DUTIES";else if(/^b\) Gastos en puertos/i.test(cells[0]||""))type="PORT_COST";else if(/^c\) Gtos/i.test(cells[0]||""))type="MARKETING_COST";else if(/^FAS Te[oó]rico en u\$s/i.test(cells[0]||""))type="FAS_THEORETICAL";if(!type)continue;const code=commodity.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();const {data:com}=await db.from("commodities").select("id").eq("codigo",code).maybeSingle();saved+=await save({source:SOURCE,source_reference:BCR_FOB,market_date:marketDate,published_at:null,commodity_id:com?.id||null,product_id:null,variety:null,position:"SPOT",market:"ARGENTINA",port:"SAGyP/UP RIVER",price_type:type,price:first,currency:"USD",unit:"T",status:"VALID",freshness:"UPDATED",previous_value:null,variation:null,payload:{commodity,metric:type,raw_cells:cells,run_id:runId}})}return saved}
Deno.serve(async req=>{let runId:string|null=null;try{if(!(await auth(req)))return new Response(JSON.stringify({error:"AUTH_REQUIRED"}),{status:401});const {data:run,error:re}=await db.from("market_sync_runs").insert({source:SOURCE,status:"RUNNING"}).select("id").single();if(re)throw re;runId=run.id;const [local,fob]=await Promise.all([html(BCR_LOCAL),html(BCR_FOB)]);const a=await parseLocal(local,runId),b=await parseFob(fob,runId);await db.from("market_sync_runs").update({finished_at:new Date().toISOString(),status:"SUCCESS",records_seen:a+b,records_saved:a+b}).eq("id",runId);return new Response(JSON.stringify({ok:true,source:SOURCE,run_id:runId,records_saved:a+b}),{headers:{"content-type":"application/json"}})}catch(e){const msg=e instanceof Error?e.message:"MARKET_SYNC_ERROR";if(runId)await db.from("market_sync_runs").update({finished_at:new Date().toISOString(),status:"ERROR",error_code:msg.slice(0,80),error_message:msg}).eq("id",runId);return new Response(JSON.stringify({ok:false,error:msg,run_id:runId}),{status:502,headers:{"content-type":"application/json"}})}});