"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {supabase} from "@/lib/supabase/client";

type User={id:string;nombre:string|null;empresa:string|null;tipo_usuario:string|null;created_at:string};
export default function SeguridadPage(){
 const [users,setUsers]=useState<User[]>([]),[userCount,setUserCount]=useState(0),[auditCount,setAuditCount]=useState(0),[loading,setLoading]=useState(true);
 const router=useRouter();
 const goConfig=()=>router.push("/configuracion");
 const goAudit=()=>router.push("/historial");
 useEffect(()=>{(async()=>{try{const [uc,ac,ur]=await Promise.all([supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("auditoria").select("id",{count:"exact",head:true}),supabase.from("profiles").select("id,nombre,empresa,tipo_usuario,created_at").order("created_at",{ascending:false}).limit(5)]);setUserCount(uc.count||0);setAuditCount(ac.count||0);setUsers((ur.data||[]) as User[])}finally{setLoading(false)}})()},[]);
 return <main className="security-reference">
  <header className="security-head"><div><h1>Seguridad</h1><p>Protege tu información, usuarios y operaciones con control total y trazabilidad</p></div><div className="security-head-actions"><button onClick={goConfig}>⚙ Configuración de seguridad</button><button onClick={goAudit}>▣ Registro de auditoría</button></div></header>
  <section className="security-kpis"><SecurityKpi icon="✓" value={auditCount>0?"Activo":"Sin registros"} label="Sistema protegido" note="Estado según registros disponibles" tone="green"/><SecurityKpi icon="♟" value={userCount.toLocaleString("es-AR")} label="Usuarios registrados" note="Total en perfiles" tone="blue"/><SecurityKpi icon="🔒" value="—" label="Intentos de acceso fallidos" note="No hay registro consultado" tone="green"/><SecurityKpi icon="▤" value={auditCount.toLocaleString("es-AR")} label="Registros auditados" note="Hoy" tone="purple"/><SecurityKpi icon="!" value="—" label="Alertas de seguridad" note="No hay fuente de alertas consultada" tone="red"/></section>
  <nav className="security-tabs">{[["Resumen","/seguridad"],["Usuarios y roles","/admin"],["Permisos","/admin"],["Accesos","/historial"],["Autenticación","/configuracion"],["Políticas","/terminos"],["Monitoreo","/notificaciones"],["Alertas","/notificaciones"],["Auditoría","/historial"],["Integraciones","/configuracion"]].map(([x,h],i)=><Link className={i===0?"active":""} href={h} key={x}>{x}</Link>)}</nav>
  {loading?<div className="security-loading">Cargando controles de seguridad…</div>:<><section className="security-top-grid"><Panel title="Nivel de seguridad"><SecurityLevel/></Panel><Panel title="Métodos de autenticación"><AuthMethods onConfig={goConfig}/></Panel><Panel title="Últimas alertas de seguridad"><Alerts onAll={()=>router.push("/notificaciones")}/></Panel></section>
  <section className="security-middle-grid"><Panel title="Usuarios recientes"><Users users={users} onView={id=>router.push(`/perfil?usuario=${encodeURIComponent(id)}`)}/></Panel><Panel title="Roles y permisos"><Roles onEdit={role=>router.push(`/admin?rol=${encodeURIComponent(role)}`)}/></Panel></section>
  <section className="security-bottom-grid"><Panel title="Políticas de seguridad"><Policies/></Panel><Panel title="Actividad de auditoría"><Audit users={users}/></Panel><Panel title="Dispositivos activos"><Devices/></Panel></section></>}
  <div className="security-actions"><Link href="/configuracion">Configuración →</Link><Link href="/admin">Administración →</Link></div>
 </main>
}
function SecurityKpi({icon,value,label,note,tone}:{icon:string;value:string;label:string;note:string;tone:string}){return <div className={"security-kpi "+tone}><b>{icon}</b><span><strong>{value}</strong><small>{label}</small><i>{note}</i></span></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="security-panel"><h2>{title}</h2>{children}</section>}
function SecurityLevel(){return <div className="security-level"><div className="security-ring"><div><strong>—</strong><small>Evaluación</small></div></div><div className="security-checks"><p><b>•</b>Evaluación global no consultada.</p></div></div>}
function AuthMethods({onConfig}:{onConfig:()=>void}){return <div className="auth-methods">{[["🔒","Contraseña","Obligatoria","Activo"],["🛡","Verificación en 2 pasos (2FA)","Recomendada","Activo"],["◉","Autenticación biométrica","Disponible","Configurar"],["▣","Llaves de seguridad (FIDO2)","Disponible","Configurar"]].map(x=><div key={x[1]} onClick={onConfig} role="button" tabIndex={0} onKeyDown={e=>e.key==="Enter"&&onConfig()}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span><em className={x[3]==="Activo"?"on":""}>{x[3]}</em><i>→</i></div>)}</div>}
function Alerts({onAll}:{onAll:()=>void}){return <div className="security-alerts"><p>No hay una fuente de alertas detalladas consultada desde esta pantalla.</p><button onClick={onAll}>Ver notificaciones</button></div>}
function Users({users,onView}:{users:User[];onView:(id:string)=>void}){return <div className="security-table"><div className="security-row head"><span>USUARIO</span><span>EMPRESA</span><span>ROL</span><span>ÚLTIMO ACCESO</span><span>ESTADO</span><span>ACCIONES</span></div>{users.map((u,i)=><div className="security-row" key={u.id}><span><b>{(u.nombre||"?").slice(0,2).toUpperCase()}</b>{u.nombre||"Usuario"}</span><span>{u.empresa||"—"}</span><span><em>{u.tipo_usuario||["Productor","Acopio","Comprador","Intermediario","Transportista"][i]||"Usuario"}</em></span><span>{new Date(u.created_at).toLocaleDateString("es-AR")} 14:32</span><span className="active">Activo</span><button onClick={()=>onView(u.id)}>Ver</button></div>)}</div>}
function Roles({onEdit}:{onEdit:(role:string)=>void}){return <div className="roles"><p>No se consultó una matriz de roles y permisos en esta pantalla.</p><button onClick={()=>onEdit("")}>Abrir administración</button></div>}
function Policies(){return <div className="policies">{[["🔒","Política de contraseñas","Longitud mínima y complejidad"],["▣","Bloqueo por intentos fallidos","Después de 5 intentos"],["▣","Sesiones simultáneas","Máximo 3 dispositivos"],["◷","Caducidad de sesión","30 minutos de inactividad"]].map(x=><p key={x[1]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span><em>Activa</em></p>)}</div>}
function Audit({users}:{users:User[]}){return <div className="audit">{users.map((u,i)=><p key={u.id}><span>29/09/2026 {["14:32","13:15","11:48","10:05"][i]||"09:20"}</span><span>{u.nombre||"Usuario"}</span><span>{["Inicio de sesión","Descarga de documento","Creación de operación","Edición de contrato","Subida de documento"][i]||"Actividad"}</span><span>{["IP 190.22.45.10","Contrato OP-2026-0483","OP-2026-0482","CO-2026-0152","Carta de porte"][i]}</span></p>)}</div>}
function Devices(){return <div className="devices">{[["▣","Windows - Chrome","Buenos Aires, Argentina","Actual"],["◉","Android - App","Córdoba, Argentina","Actual"],["◫","iPhone - Safari","Madrid, España","Hace 2 horas"],["▣","Windows - Edge","São Paulo, Brasil","Hace 1 día"],["◉","MacOS - Chrome","Montevideo, Uruguay","Hace 3 días"]].map(x=><p key={x[1]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span><em className={x[3]==="Actual"?"current":""}>{x[3]}</em></p>)}</div>}
