create table if not exists public.catalogo_puertos (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  pais text not null default 'Argentina',
  provincia text,
  localidad text,
  tipo text not null default 'PORT',
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.catalogo_lugares_recepcion (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  descripcion text,
  activo boolean not null default true,
  orden integer not null default 0
);

alter table public.publicaciones
  add column if not exists puertos text[] not null default '{}'::text[],
  add column if not exists lugares_recepcion text[] not null default '{}'::text[];

insert into public.catalogo_puertos (codigo,nombre,pais,provincia,localidad,tipo) values
('AR-ROS','Puerto Rosario','Argentina','Santa Fe','Rosario','FLUVIAL_CEREALERO'),
('AR-SLO','Puerto San Lorenzo','Argentina','Santa Fe','San Lorenzo','FLUVIAL_CEREALERO'),
('AR-GSM','Puerto General San Martín','Argentina','Santa Fe','General San Martín','FLUVIAL_CEREALERO'),
('AR-TIM','Puerto Timbúes','Argentina','Santa Fe','Timbúes','FLUVIAL_CEREALERO'),
('AR-ASC','Puerto Arroyo Seco','Argentina','Santa Fe','Arroyo Seco','FLUVIAL_CEREALERO'),
('AR-VCO','Puerto Villa Constitución','Argentina','Santa Fe','Villa Constitución','FLUVIAL_CEREALERO'),
('AR-SFE','Puerto Santa Fe','Argentina','Santa Fe','Santa Fe','FLUVIAL'),
('AR-SNI','Puerto San Nicolás','Argentina','Buenos Aires','San Nicolás de los Arroyos','FLUVIAL_CEREALERO'),
('AR-RAM','Puerto Ramallo','Argentina','Buenos Aires','Ramallo','FLUVIAL_CEREALERO'),
('AR-SPD','Puerto San Pedro','Argentina','Buenos Aires','San Pedro','FLUVIAL_CEREALERO'),
('AR-ZAR','Puerto Zárate','Argentina','Buenos Aires','Zárate','FLUVIAL'),
('AR-LIM','Puerto Lima','Argentina','Buenos Aires','Lima','FLUVIAL'),
('AR-CAM','Puerto Campana','Argentina','Buenos Aires','Campana','FLUVIAL'),
('AR-BAI','Puerto Buenos Aires','Argentina','Buenos Aires','Buenos Aires','MARITIMO'),
('AR-DOCK','Puerto Dock Sud','Argentina','Buenos Aires','Dock Sud','FLUVIAL_MARITIMO'),
('AR-LPL','Puerto La Plata','Argentina','Buenos Aires','La Plata','MARITIMO'),
('AR-QUE','Puerto Quequén','Argentina','Buenos Aires','Quequén','MARITIMO_CEREALERO'),
('AR-BBB','Puerto Bahía Blanca','Argentina','Buenos Aires','Bahía Blanca','MARITIMO_CEREALERO'),
('AR-MDP','Puerto Mar del Plata','Argentina','Buenos Aires','Mar del Plata','MARITIMO'),
('AR-SAE','Puerto San Antonio Este','Argentina','Río Negro','San Antonio Este','MARITIMO'),
('AR-PMA','Puerto Madryn','Argentina','Chubut','Puerto Madryn','MARITIMO'),
('AR-COM','Puerto Comodoro Rivadavia','Argentina','Chubut','Comodoro Rivadavia','MARITIMO'),
('AR-PDE','Puerto Deseado','Argentina','Santa Cruz','Puerto Deseado','MARITIMO'),
('AR-RGL','Puerto Río Gallegos','Argentina','Santa Cruz','Río Gallegos','MARITIMO'),
('AR-USU','Puerto Ushuaia','Argentina','Tierra del Fuego','Ushuaia','MARITIMO'),
('AR-COU','Puerto Corrientes','Argentina','Corrientes','Corrientes','FLUVIAL'),
('AR-GOY','Puerto Goya','Argentina','Corrientes','Goya','FLUVIAL'),
('AR-BAR','Puerto Barranqueras','Argentina','Chaco','Barranqueras','FLUVIAL'),
('AR-FOR','Puerto Formosa','Argentina','Formosa','Formosa','FLUVIAL'),
('AR-REC','Puerto Reconquista','Argentina','Santa Fe','Reconquista','FLUVIAL'),
('AR-CDE','Puerto Concepción del Uruguay','Argentina','Entre Ríos','Concepción del Uruguay','FLUVIAL'),
('AR-DIA','Puerto Diamante','Argentina','Entre Ríos','Diamante','FLUVIAL'),
('AR-PAR','Puerto Paraná','Argentina','Entre Ríos','Paraná','FLUVIAL')
on conflict (codigo) do update set nombre=excluded.nombre,pais=excluded.pais,provincia=excluded.provincia,localidad=excluded.localidad,tipo=excluded.tipo,activo=true;

insert into public.catalogo_lugares_recepcion (codigo,nombre,descripcion,orden) values
('PUERTO','Puerto / Terminal portuaria','Entrega o recepción en puerto o terminal.',10),
('ACOPIO','Acopio','Planta de acopio o centro de recepción.',20),
('PLANTA','Planta industrial','Molinera, aceitera, procesadora, maltería o industria.',30),
('CAMPO','Campo / establecimiento','Recepción o retiro directamente en establecimiento productor.',40),
('DEPOSITO','Depósito / silo','Depósito, silo, elevador o almacenamiento.',50),
('TERMINAL','Terminal logística','Terminal multimodal o centro logístico.',60),
('FRONTERA','Paso fronterizo','Punto de recepción/entrega para comercio internacional terrestre.',70),
('OTRO','Otro lugar','Otro punto acordado entre las partes.',80)
on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,orden=excluded.orden,activo=true;

alter table public.catalogo_puertos enable row level security;
alter table public.catalogo_lugares_recepcion enable row level security;

drop policy if exists catalogo_puertos_select_authenticated on public.catalogo_puertos;
create policy catalogo_puertos_select_authenticated on public.catalogo_puertos
for select to authenticated using (activo=true);

drop policy if exists catalogo_lugares_recepcion_select_authenticated on public.catalogo_lugares_recepcion;
create policy catalogo_lugares_recepcion_select_authenticated on public.catalogo_lugares_recepcion
for select to authenticated using (activo=true);

update public.publicaciones
set puertos = case
  when coalesce(puerto,'') <> '' and cardinality(coalesce(puertos,'{}'::text[])) = 0 then array[puerto]
  else coalesce(puertos,'{}'::text[])
end;

create or replace function public.guardar_publicacion(p_publicacion_id uuid, p_datos jsonb)
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_uid uuid := auth.uid();
  v_empresa uuid;
  v_id uuid;
  v_existing_empresa uuid;
  v_puertos text[];
  v_lugares text[];
begin
  if v_uid is null then raise exception 'No autenticado'; end if;
  select active_company_id into v_empresa from public.profiles where id=v_uid;
  if v_empresa is null or not exists (select 1 from public.company_users where company_id=v_empresa and profile_id=v_uid and activo=true) then
    raise exception 'Empresa activa inválida';
  end if;

  v_puertos := case when p_datos ? 'puertos'
    then coalesce((select array_agg(value order by value) from jsonb_array_elements_text(coalesce(p_datos->'puertos','[]'::jsonb))), '{}'::text[])
    else '{}'::text[] end;

  v_lugares := case when p_datos ? 'lugares_recepcion'
    then coalesce((select array_agg(value order by value) from jsonb_array_elements_text(coalesce(p_datos->'lugares_recepcion','[]'::jsonb))), '{}'::text[])
    else '{}'::text[] end;

  if p_publicacion_id is null then
    if coalesce((p_datos->>'cantidad_tn')::numeric,0)<=0 or coalesce((p_datos->>'precio_tn')::numeric,0)<=0 then
      raise exception 'Cantidad y precio deben ser mayores a cero';
    end if;

    insert into public.publicaciones(
      empresa_id,tipo,producto_id,cantidad_tn,precio_tn,moneda_id,incoterm_id,provincia,localidad,
      puerto,puertos,lugares_recepcion,calidad,humedad,proteina,observaciones,estado
    )
    values(
      v_empresa,p_datos->>'tipo',(p_datos->>'producto_id')::integer,(p_datos->>'cantidad_tn')::numeric,
      (p_datos->>'precio_tn')::numeric,(p_datos->>'moneda_id')::integer,(p_datos->>'incoterm_id')::integer,
      p_datos->>'provincia',p_datos->>'localidad',
      coalesce(nullif(p_datos->>'puerto',''),nullif(v_puertos[1],'')),v_puertos,v_lugares,
      nullif(p_datos->>'calidad',''),nullif(p_datos->>'humedad','')::numeric,
      nullif(p_datos->>'proteina','')::numeric,nullif(p_datos->>'observaciones',''),'PUBLICADA'
    )
    returning id into v_id;
  else
    select empresa_id into v_existing_empresa from public.publicaciones where id=p_publicacion_id for update;
    if v_existing_empresa is distinct from v_empresa then raise exception 'No autorizado'; end if;

    update public.publicaciones set
      tipo=p_datos->>'tipo',
      producto_id=(p_datos->>'producto_id')::integer,
      cantidad_tn=(p_datos->>'cantidad_tn')::numeric,
      precio_tn=(p_datos->>'precio_tn')::numeric,
      moneda_id=(p_datos->>'moneda_id')::integer,
      incoterm_id=(p_datos->>'incoterm_id')::integer,
      provincia=p_datos->>'provincia',
      localidad=p_datos->>'localidad',
      puerto=coalesce(nullif(p_datos->>'puerto',''),nullif(v_puertos[1],'')),
      puertos=v_puertos,
      lugares_recepcion=v_lugares,
      calidad=nullif(p_datos->>'calidad',''),
      humedad=nullif(p_datos->>'humedad','')::numeric,
      proteina=nullif(p_datos->>'proteina','')::numeric,
      observaciones=nullif(p_datos->>'observaciones',''),
      actualizada_en=now()
    where id=p_publicacion_id
    returning id into v_id;
  end if;
  return v_id;
end;
$function$;
