insert into public.paises (codigo_iso,nombre,activo) values
('CA','Canadá',true),
('MX','México',true),
('CO','Colombia',true),
('EC','Ecuador',true),
('VE','Venezuela',true),
('CR','Costa Rica',true),
('GT','Guatemala',true),
('HN','Honduras',true),
('NI','Nicaragua',true),
('PA','Panamá',true),
('DO','República Dominicana',true),
('GB','Reino Unido',true),
('ES','España',true),
('PT','Portugal',true),
('FR','Francia',true),
('DE','Alemania',true),
('IT','Italia',true),
('NL','Países Bajos',true),
('BE','Bélgica',true),
('DK','Dinamarca',true),
('SE','Suecia',true),
('NO','Noruega',true),
('FI','Finlandia',true),
('PL','Polonia',true),
('CZ','Chequia',true),
('AT','Austria',true),
('CH','Suiza',true),
('IE','Irlanda',true),
('RO','Rumania',true),
('HU','Hungría',true),
('GR','Grecia',true),
('TR','Turquía',true),
('UA','Ucrania',true),
('RU','Rusia',true),
('JP','Japón',true),
('KR','Corea del Sur',true),
('VN','Vietnam',true),
('ID','Indonesia',true),
('MY','Malasia',true),
('TH','Tailandia',true),
('PH','Filipinas',true),
('SG','Singapur',true),
('BD','Bangladés',true),
('PK','Pakistán',true),
('AE','Emiratos Árabes Unidos',true),
('SA','Arabia Saudita',true),
('IL','Israel',true),
('EG','Egipto',true),
('MA','Marruecos',true),
('DZ','Argelia',true),
('ZA','Sudáfrica',true),
('NG','Nigeria',true),
('KE','Kenia',true),
('AU','Australia',true),
('NZ','Nueva Zelanda',true) on conflict (codigo_iso) do update set nombre=excluded.nombre, activo=true;
