-- Enforce workflow stage gates for contract and logistics RPCs.
-- Contract: stage 4 only. Delivery confirmation: stage 8 only.

create or replace function public.guardar_contrato_comercial(p_operacion_id uuid,p_datos jsonb)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare v_id uuid; v_uid uuid:=auth.uid(); v_workflow public.operacion_workflow%rowtype; v_orden integer; v_estado text;
begin
 if v_uid is null or not public.usuario_participa_operacion(p_operacion_id) then raise exception 'No autorizado para esta operación.'; end if;
 select * into v_workflow from public.operacion_workflow where operacion_id=p_operacion_id for update; if not found then raise exception 'La operación no tiene workflow.'; end if;
 select orden into v_orden from public.workflow_etapas where id=v_workflow.etapa_actual_id and workflow_id=v_workflow.workflow_id; if v_orden<>4 then raise exception 'El contrato definitivo solo puede gestionarse en la etapa 4.'; end if;
 v_estado:=coalesce(nullif(p_datos->>'estado',''),'BORRADOR'); if v_estado not in('BORRADOR','CONFIRMADO') then raise exception 'Estado de contrato inválido.'; end if;
 insert into public.contratos(operacion_id,acuerdo_id,numero_contrato,tipo_contrato,estado,cantidad_tn,precio_tn,importe_total,lugar_carga,destino,condicion_entrega,forma_pago,plazo_pago,flete,calidad,observaciones,contenido,confirmado_at,updated_at)
 select p_operacion_id,nullif(p_datos->>'acuerdo_id','')::uuid,nullif(p_datos->>'numero_contrato',''),nullif(p_datos->>'tipo_contrato',''),v_estado,(p_datos->>'cantidad_tn')::numeric,(p_datos->>'precio_tn')::numeric,(p_datos->>'importe_total')::numeric,nullif(p_datos->>'lugar_carga',''),nullif(p_datos->>'destino',''),nullif(p_datos->>'condicion_entrega',''),nullif(p_datos->>'forma_pago',''),nullif(p_datos->>'plazo_pago',''),nullif(p_datos->>'flete',''),nullif(p_datos->>'calidad',''),nullif(p_datos->>'observaciones',''),p_datos->>'contenido',case when v_estado='CONFIRMADO' then now() else null end,now()
 on conflict(operacion_id) do update set acuerdo_id=excluded.acuerdo_id,numero_contrato=excluded.numero_contrato,tipo_contrato=excluded.tipo_contrato,estado=excluded.estado,cantidad_tn=excluded.cantidad_tn,precio_tn=excluded.precio_tn,importe_total=excluded.importe_total,lugar_carga=excluded.lugar_carga,destino=excluded.destino,condicion_entrega=excluded.condicion_entrega,forma_pago=excluded.forma_pago,plazo_pago=excluded.plazo_pago,flete=excluded.flete,calidad=excluded.calidad,observaciones=excluded.observaciones,contenido=excluded.contenido,confirmado_at=excluded.confirmado_at,updated_at=excluded.updated_at returning id into v_id;
 return (select to_jsonb(c) from public.contratos c where c.id=v_id);
end;$function$;

create or replace function public.guardar_operacion_logistica(p_operacion_id uuid,p_datos jsonb)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare v_uid uuid:=auth.uid(); v_row public.operacion_logistica; v_id uuid; v_workflow public.operacion_workflow%rowtype; v_orden integer; v_estado text;
begin
 if v_uid is null then raise exception 'AUTH_REQUIRED'; end if; if not public.usuario_participa_operacion(p_operacion_id) then raise exception 'FORBIDDEN'; end if;
 select * into v_workflow from public.operacion_workflow where operacion_id=p_operacion_id for update; if not found then raise exception 'WORKFLOW_NOT_FOUND'; end if;
 select orden into v_orden from public.workflow_etapas where id=v_workflow.etapa_actual_id and workflow_id=v_workflow.workflow_id;
 v_estado:=coalesce(nullif(p_datos->>'estado',''),'PENDIENTE'); if v_estado='ENTREGADA' and v_orden<>8 then raise exception 'La entrega solo puede confirmarse en la etapa 8 Logística / Entrega.'; end if;
 v_id:=nullif(p_datos->>'id','')::uuid; if coalesce((p_datos->>'kilos_entregados')::numeric,0)<0 then raise exception 'INVALID_DELIVERY_QUANTITY'; end if;
 if v_id is not null then update public.operacion_logistica set estado=v_estado,carta_porte_numero=p_datos->>'carta_porte_numero',transportista=p_datos->>'transportista',transportista_cuit=p_datos->>'transportista_cuit',chofer_nombre=p_datos->>'chofer_nombre',chofer_documento=p_datos->>'chofer_documento',patente_camion=p_datos->>'patente_camion',patente_acoplado=p_datos->>'patente_acoplado',fecha_carga=nullif(p_datos->>'fecha_carga','')::date,hora_carga=nullif(p_datos->>'hora_carga','')::time,fecha_estimada_entrega=nullif(p_datos->>'fecha_estimada_entrega','')::date,destino=p_datos->>'destino',numero_turno=p_datos->>'numero_turno',fecha_entrega=nullif(p_datos->>'fecha_entrega','')::timestamptz,kilos_entregados=case when p_datos ? 'kilos_entregados' then (p_datos->>'kilos_entregados')::numeric else kilos_entregados end,observaciones_entrega=p_datos->>'observaciones_entrega',carta_porte_estado=coalesce(p_datos->>'carta_porte_estado',carta_porte_estado),carta_porte_origen=coalesce(p_datos->>'carta_porte_origen',carta_porte_origen),carta_porte_verificada_at=case when p_datos ? 'carta_porte_verificada_at' then nullif(p_datos->>'carta_porte_verificada_at','')::timestamptz else carta_porte_verificada_at end,carta_porte_response=coalesce(p_datos->'carta_porte_response',carta_porte_response),carta_porte_codigo=coalesce(p_datos->>'carta_porte_codigo',carta_porte_codigo),carta_porte_fecha_emision=case when p_datos ? 'carta_porte_fecha_emision' then nullif(p_datos->>'carta_porte_fecha_emision','')::timestamptz else carta_porte_fecha_emision end,carta_porte_fecha_vencimiento=case when p_datos ? 'carta_porte_fecha_vencimiento' then nullif(p_datos->>'carta_porte_fecha_vencimiento','')::timestamptz else carta_porte_fecha_vencimiento end,carta_porte_qr=coalesce(p_datos->>'carta_porte_qr',carta_porte_qr),actualizado_por=v_uid,updated_at=now() where id=v_id and operacion_id=p_operacion_id returning * into v_row;
 else insert into public.operacion_logistica(operacion_id,estado,carta_porte_numero,transportista,transportista_cuit,chofer_nombre,chofer_documento,patente_camion,patente_acoplado,fecha_carga,hora_carga,fecha_estimada_entrega,destino,numero_turno,fecha_entrega,kilos_entregados,observaciones_entrega,creado_por,actualizado_por,creado_at,updated_at,carta_porte_estado,carta_porte_origen,carta_porte_verificada_at,carta_porte_response,carta_porte_codigo,carta_porte_fecha_emision,carta_porte_fecha_vencimiento,carta_porte_qr) values(p_operacion_id,v_estado,p_datos->>'carta_porte_numero',p_datos->>'transportista',p_datos->>'transportista_cuit',p_datos->>'chofer_nombre',p_datos->>'chofer_documento',p_datos->>'patente_camion',p_datos->>'patente_acoplado',nullif(p_datos->>'fecha_carga','')::date,nullif(p_datos->>'hora_carga','')::time,nullif(p_datos->>'fecha_estimada_entrega','')::date,p_datos->>'destino',p_datos->>'numero_turno',nullif(p_datos->>'fecha_entrega','')::timestamptz,(p_datos->>'kilos_entregados')::numeric,p_datos->>'observaciones_entrega',v_uid,v_uid,now(),now(),p_datos->>'carta_porte_estado',p_datos->>'carta_porte_origen',nullif(p_datos->>'carta_porte_verificada_at','')::timestamptz,p_datos->'carta_porte_response',p_datos->>'carta_porte_codigo',nullif(p_datos->>'carta_porte_fecha_emision','')::timestamptz,nullif(p_datos->>'carta_porte_fecha_vencimiento','')::timestamptz,p_datos->>'carta_porte_qr') returning * into v_row; end if;
 if v_row.id is null then raise exception 'LOGISTICS_NOT_FOUND'; end if; return to_jsonb(v_row);
end;$function$;