-- AgroBrokerIA: catálogo ampliado de productos agropecuarios, variedades, harinas, semillas y subproductos.
WITH catalog(nombre,categoria) AS (
VALUES
('Girasol tradicional','Oleaginosa'),('Girasol alto oleico','Oleaginosa'),('Girasol confitero','Oleaginosa'),('Colza / Canola','Oleaginosa'),('Maní tipo runner','Oleaginosa'),('Maní confitero','Oleaginosa'),('Maní industria','Oleaginosa'),('Lino (Linaza)','Oleaginosa'),('Cártamo','Oleaginosa'),('Sésamo (Ajonjolí)','Oleaginosa'),('Algodón (Semilla)','Oleaginosa'),('Ricino (Tártago)','Oleaginosa'),('Chía','Oleaginosa'),('Camelina','Oleaginosa'),('Carinata','Oleaginosa'),('Jatrofa (Piñón de tempate)','Oleaginosa'),('Cáñamo (Hemp)','Oleaginosa'),('Nabón (Colza salvaje)','Oleaginosa'),
('Trigo Pan','Cereal'),('Trigo Candeal / Durum','Cereal'),('Trigo Forrajero','Cereal'),('Maíz Amarillo Común','Cereal'),('Maíz Flint / Colorado','Cereal'),('Maíz Pisingallo (Popcorn)','Cereal'),('Maíz Blanco','Cereal'),('Cebada Cervecera / Maltera','Cereal'),('Cebada Forrajera','Cereal'),('Sorgo Granífero','Cereal'),('Sorgo Forrajero','Cereal'),('Sorgo Silero / Azucarado','Cereal'),('Arroz cáscara (Paddy)','Cereal'),('Arroz largo fino','Cereal'),('Arroz largo ancho','Cereal'),('Arroz doble carolina','Cereal'),('Arroz corto (Sushi)','Cereal'),('Avena Blanca','Cereal'),('Avena Amarilla','Cereal'),('Triticale','Cereal'),
('Arveja Verde','Legumbre'),('Arveja Amarilla','Legumbre'),('Garbanzo tipo Kabuli','Legumbre'),('Garbanzo tipo Desi','Legumbre'),('Lentejón / Lenteja grande','Legumbre'),('Lenteja mediana','Legumbre'),('Lenteja roja / carmesí','Legumbre'),('Poroto Alubia','Legumbre'),('Poroto Negro','Legumbre'),('Poroto Cranberry (Frutilla)','Legumbre'),('Poroto Red Kidney (Rojo)','Legumbre'),('Poroto Mung','Legumbre'),('Poroto Carioca','Legumbre'),('Habas','Legumbre'),('Lupinos','Legumbre'),
('Quinua blanca','Pseudocereal y nicho'),('Quinua roja','Pseudocereal y nicho'),('Quinua negra','Pseudocereal y nicho'),('Amaranto','Pseudocereal y nicho'),('Alforfón (Trigo Sarraceno)','Pseudocereal y nicho'),('Mijo Común (Perla / Amarillo)','Pseudocereal y nicho'),('Mijo Rojo','Pseudocereal y nicho'),('Mijo Panizo (Foxtail)','Pseudocereal y nicho'),('Alpiste tradicional','Pseudocereal y nicho'),('Alpiste libre de fibras de sílice','Pseudocereal y nicho'),('Mostaza blanca','Especialidad'),('Mostaza negra','Especialidad'),('Mostaza marrón','Especialidad'),('Coriandro (Cilantro)','Especialidad'),
('Semilla de Alfalfa Fiscalizada','Semilla forrajera'),('Semilla de Alfalfa Identificada','Semilla forrajera'),('Trébol blanco','Semilla forrajera'),('Trébol rojo','Semilla forrajera'),('Trébol de olor (Melilotus)','Semilla forrajera'),('Trébol encarnado','Semilla forrajera'),('Raigrás anual','Semilla forrajera'),('Raigrás perenne','Semilla forrajera'),('Raigrás híbrido','Semilla forrajera'),('Festuca alta','Semilla forrajera'),('Agropiro alargado','Semilla forrajera'),('Pasto Ovillo','Semilla forrajera'),('Falaris','Semilla forrajera'),('Moha de la India','Semilla forrajera'),('Vicia villosa','Semilla de cobertura'),('Vicia sativa','Semilla de cobertura'),('Rábano Forrajero','Semilla de cobertura'),
('Harina de Trigo 000 (Panificación)','Harina'),('Harina de Trigo 0000 (Repostería)','Harina'),('Harina de Trigo Integral Fina','Harina'),('Harina de Trigo Integral Gruesa','Harina'),('Harina de Trigo Candeal (Sémola / Semolín)','Harina'),('Harina de Trigo Acondicionada / Leudante','Harina'),('Harina de Trigo Industrial Extrafina','Harina'),('Harina de Maíz Degerminada (Polenta)','Harina'),('Harina de Maíz Integral','Harina'),('Harina de Maíz Blanco','Harina'),('Harina de Maíz Tostado (Fariña)','Harina'),('Harina de Maíz Nixtamalizada','Harina'),('Harina de Arroz tradicional','Harina'),('Harina de Arroz Integral','Harina'),('Harina de Avena Integral','Harina'),('Harina de Cebada','Harina'),('Harina de Centeno Fina','Harina'),('Harina de Centeno Integral','Harina'),('Harina de Sorgo Integral','Harina'),('Harina de Garbanzo','Harina'),('Harina de Arveja Verde','Harina'),('Harina de Arveja Amarilla','Harina'),('Harina de Lenteja','Harina'),('Harina de Poroto / Frijol','Harina'),('Harina de Quinua','Harina'),('Harina de Alforfón (Trigo Sarraceno)','Harina'),('Harina de Amaranto','Harina'),('Harina de Algarroba','Harina'),('Harina de Mandioca / Almidón de tapioca','Harina'),
('Aceite de soja crudo','Subproducto'),('Aceite de soja refinado','Subproducto'),('Harina desgrasada de soja (Consumo humano)','Subproducto'),('Harina / Pellets de soja de alta proteína (Forraje)','Subproducto'),('Expeller de soja','Subproducto'),('Cascarilla de soja','Subproducto'),('Aceite de girasol','Subproducto'),('Harina de girasol (Pellets/Expeller)','Subproducto'),('Afrechillo de Trigo / Salvado','Subproducto'),('Semolita de Trigo','Subproducto'),('Burlanda de Maíz húmeda (WDGS)','Subproducto'),('Burlanda de Maíz seca (DDGS)','Subproducto'),('Gluten Feed','Subproducto'),('Gluten Meal','Subproducto'),('Germen de Maíz','Subproducto'),('Malta de Cebada','Subproducto')
), prepared AS (
SELECT left(regexp_replace(upper(nombre),'[^A-Z0-9]+','','g'),16)||'_'||substr(md5(nombre),1,3) AS codigo,nombre,categoria FROM catalog
)
INSERT INTO public.productos(codigo,nombre,categoria,activo)
SELECT p.codigo,p.nombre,p.categoria,true FROM prepared p
WHERE NOT EXISTS (SELECT 1 FROM public.productos x WHERE lower(x.nombre)=lower(p.nombre) OR x.codigo=p.codigo);