"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase/client";
export default function ArcaConfigPage(){
 const[cid,setCid]=useState(""),[company,setCompany]=useState(""),[cuit,setCuit]=useState(""),[env,setEnv]=useState("production"),[pv,setPv]=useState("1"),[enabled,setEnabled]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[checking,setChecking]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesión no disponible.");const{data:p}=await supabase.from("profiles").select("active_company_id").eq("id",user.id).single();if(!p?.active_company_id)throw new Error("No hay empresa activa.");setCid(p.active_company_id);const[{data:c,error:ce},{data:a}]=await Promise.all([supabase.from("companies").select("id,razon_social,cuit").eq("id",p.active_company_id).single(),supabase.from("arca_company_config").select("environment,punto_venta,enabled").eq("company_id",p.active_company_id).maybeSingle()]);if(ce)throw ce;setCompany(c?.razon_social||"");setCuit(c?.cuit||"");if(a){setEnv(a.environment);setPv(String(a.punto_venta));setEnabled(Boolean(a.enabled));}}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar ARCA.");}finally{setLoading(false)}})()},[]);
 async function save(){setSaving(true);setError("");setMsg("");try{if(!cid)throw new Error("Empresa activa no disponible.");if(!cuit)throw new Error("Primero completá el CUIT en Configuración fiscal.");const{error:e}=await supabase.from("arca_company_config").upsert({company_id:cid,environment:env,punto_venta:Number(pv),enabled,cert_secret_name:"ARCA_CERTIFICATE_BASE64",private_key_secret_name:"ARCA_PRIVATE_KEY_BASE64",cuit_secret_name:null},{onConflict:"company_id"});if(e)throw e;setMsg("Configuración ARCA guardada.");}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar ARCA.");}finally{setSaving(false)}}
 async function test(){setChecking(true);setError("");setMsg("");try{const{data,error:e}=await supabase.functions.invoke("arca-facturacion",{body:{action:"test_connection"}});if(e)throw new Error(e.message);if(!data?.ok)throw new Error(data?.error||"ARCA no aceptó la autenticación.");setMsg("ARCA verificado correctamente: WSAA aceptó la autenticación.");}catch(e){setError(e instanceof Error?e.message:"No se pudo verificar ARCA.");}finally{setChecking(false)}}
 if(loading)return <main className="module-page"><div className="module-hero"><h1>Configuración ARCA</h1></div><div className="module-loading">Cargando…</div></main>;
 return <main className="module-page"><div className="module-hero"><div><span className="eyebrow">FACTURACIÓN ELECTRÓNICA</span><h1>Configuración ARCA</h1><p>Configurá el punto de venta y verificá la conexión real con ARCA.</p></div><Link className="module-pill" href="/facturas">← Volver a Facturación</Link></div>
 {error&&<div className="module-alert module-alert-error">{error}</div>}{msg&&<div className="module-alert">{msg}</div>}
 <section className="company-card"><h2>{company||"Empresa activa"}</h2><p>CUIT: <strong>{cuit||"No registrado"}</strong></p><div className="settings-form-grid"><label>Ambiente<select value={env} onChange={e=>setEnv(e.target.value)}><option value="production">Producción</option><option value="homologacion">Homologación</option></select></label><label>Punto de venta ARCA<input type="number" min="1" max="99998" value={pv} onChange={e=>setPv(e.target.value)}/></label></div><label className="settings-toggle"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Habilitar facturación ARCA para esta empresa</label><div className="settings-actions"><button className="module-pill" onClick={save} disabled={saving}>{saving?"Guardando…":"Guardar configuración"}</button><button className="module-pill" onClick={test} disabled={checking}>{checking?"Verificando…":"Verificar conexión real"}</button><Link className="module-pill" href="/configuracion/fiscal">Configurar datos fiscales →</Link></div><div className="settings-note">Las credenciales criptográficas permanecen en los secretos del entorno; no se muestran ni se guardan en el navegador.</div></section></main>;
}